# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.7";
      "sbtVersion" = "1.2.7";
    }];
  "repos" = {
    "nix-public" = "";
  };
  "artifacts" = {
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-javadoc.jar";
      sha256 = "EB80085BB9DB2326E42B4CE74E8B737788D6907687807113A57D82AE83B83519";
    };
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-sources.jar";
      sha256 = "480CB5E99519271C9256716D4BE1A27054047435FF72078D9DEAE5C6A19F63EB";
    };
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-tests.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-tests.jar";
      sha256 = "DE17ABE08312A27F2DC70B05EC7BB528071F9D4E497F49F34FB55B15F2021258";
    };
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar";
      sha256 = "FB53F8539E7FCB8F093A56E138112056EC1DC809EBB020B59D8A36A5EBAC37E0";
    };
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.pom";
      sha256 = "A051EB1A2548B93C99ABCA8EB71D5C75D2FF06976682960348124BC4901A5315";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-javadoc.jar";
      sha256 = "0560248F9CC788A2218BF8D739A3003EA0455E2243ACF399679DCB93C7816207";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-sources.jar";
      sha256 = "1F69B6B638EC551D26B10FEEADE5A2B77ABE347F9759DA95022F0DA9A63A9971";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-tests.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-tests.jar";
      sha256 = "56A67B9087D1363DD722E53E564FBC571B9BD8349FB92889B44C01B114A1E7AA";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar";
      sha256 = "5946D837FE6F960C02A53EDA7A6926ECC3C758BBDD69AA453EE429F858217F22";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.pom";
      sha256 = "DF4D7181EC51655BAAAAB067971180D7681643DDD274139F0C3078DBA14E97E0";
    };
    "nix-public/ch/qos/logback/logback-parent/1.2.3/logback-parent-1.2.3.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-parent/1.2.3/logback-parent-1.2.3.pom";
      sha256 = "79CD021DAFC7B0255D3CDD3FD70CBAA638DF73995749A348EE82C45635EAB26A";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-javadoc.jar";
      sha256 = "EBD162363C0A6CA9E52AF51D7377F78F559D3F2663DC896E0DBF3B16A0188972";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-sources.jar";
      sha256 = "319A840705E1E46ABE579DD3D079B508558791E0236BC78DA01911748E06AF93";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-tests.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-tests.jar";
      sha256 = "AE143A7DC135371F446A44775E8D5337D97151D5FEEC8CA8575F3A718DDF35F3";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar";
      sha256 = "97D1ACAAC82409BE42E622D7A54D3AE9D08517E8AEFDEA3D2BA9791150C2F02D";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom";
      sha256 = "1DF7B6F08DFB81A268D6B93B659A6A9E389C5D8C32BDF0754238BA6483A4E982";
    };
    "nix-public/junit/junit/4.12/junit-4.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12-javadoc.jar";
      sha256 = "84354AA70F995A7FF3C96B144C49B7FE90A0C6E21F818FD23B17F75B17FD1CA9";
    };
    "nix-public/junit/junit/4.12/junit-4.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12-sources.jar";
      sha256 = "9F43FEA92033AD82BCAD2AE44CEC5C82ABC9D6EE4B095CAB921D11EAD98BF2FF";
    };
    "nix-public/junit/junit/4.12/junit-4.12.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar";
      sha256 = "59721F0805E223D84B90677887D9FF567DC534D7C502CA903C0C2B17F05C116A";
    };
    "nix-public/junit/junit/4.12/junit-4.12.pom" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.pom";
      sha256 = "90F163F78E3FFB6F1C7AD97DE9E7EBA4EEA25807141B85D6D12BE67CA25449C4";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-javadoc.jar";
      sha256 = "27F7327AEE87324952DA2405B02094DF40A4E772B48DAE7E419D8B50067CA745";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar";
      sha256 = "E223D2D8FBAFD66057A8848CC94222D63C3CEDD652CC48EDDC0AB5C39C0F84DF";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar";
      sha256 = "66FDEF91E9739348DF7A096AA384A5685F4E875584CCE89386A7A47251C4D8E9";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom";
      sha256 = "FDE386A7905173A1B103DE6AB820727584B50D0E32282E2797787C20A64FFA93";
    };
    "nix-public/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom";
      sha256 = "6D535F94EFB663BDB682C9F27A50335394688009642BA7A9677504BC1BE4129B";
    };
    "nix-public/org/jboss/jboss-parent/9/jboss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/jboss/jboss-parent/9/jboss-parent-9.pom";
      sha256 = "14C747D0A3BBA2F529B3F860B07880FB1CEF202656E6649CDA2CB98DB63EC79E";
    };
    "nix-public/org/jboss/netty/netty/3.2.10.Final/netty-3.2.10.Final-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/jboss/netty/netty/3.2.10.Final/netty-3.2.10.Final-sources.jar";
      sha256 = "C75DC69C0B67CD947D50D83513BFF721B980BDE3E2A5695A2CD0547E8E333D67";
    };
    "nix-public/org/jboss/netty/netty/3.2.10.Final/netty-3.2.10.Final.jar" = {
      url = "https://repo1.maven.org/maven2/org/jboss/netty/netty/3.2.10.Final/netty-3.2.10.Final.jar";
      sha256 = "EF07F5690FE4EA8BCC03B28FCD4978FC6783B3E0097A45F6D13D7DAD7010C503";
    };
    "nix-public/org/jboss/netty/netty/3.2.10.Final/netty-3.2.10.Final.pom" = {
      url = "https://repo1.maven.org/maven2/org/jboss/netty/netty/3.2.10.Final/netty-3.2.10.Final.pom";
      sha256 = "AB746E8C7530129AC6E677C33342862AF6B3E45568103A03B5167273AD53D26F";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar";
      sha256 = "FF42809FBF887885C957B3D368A909C6CCDDEA4C0485E4FE3A6465ED7747B636";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar";
      sha256 = "A7E8AAC79394DF396AFDA98B35537791809D815CE15AB2224F7D31E50C753922";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar";
      sha256 = "7CC3B6CEB56E879CB977E8E043F4BFE2E062F78795EFD7EFA09F85003CB3230A";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom";
      sha256 = "A8FDB9C75E3333D442F2CBE283F1E0F8573FF33F87CFE6DC22D154ABD0D29A0B";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-javadoc.jar";
      sha256 = "6816438CEB8357C14C0202D7B8F1CE9102C610944404E201D8601BD0EF65A9D1";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-sources.jar";
      sha256 = "676F9865EEE108B703D812A21BA0BD9530E166157D431171CDC1964D359D514F";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.jar";
      sha256 = "6E80EF4493127214D31631287A6789170BF6C9A771D6094ACD8DC785E8970270";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.pom";
      sha256 = "4E26B26FF0282A498515FAD296AE3949C071143C64C309FB0E4081DFCB1C46A5";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-javadoc.jar";
      sha256 = "E5B8691423267DDF1343BA45684C53884D67588B83CAC89EDC17C0D5A4FC5057";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-sources.jar";
      sha256 = "51706711A1399F06206745907F188815C31F2DD95B39B01F0E2C2FC78B0E7E3B";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.jar";
      sha256 = "F34E9119F45ABD41E85B9E121BA19DD9288B3B4AF7F7047E86DC70236708D170";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.pom";
      sha256 = "CD113C73BD725B366F196015680C74916F7510E649799D45DED1A7E488D58E7F";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-javadoc.jar";
      sha256 = "BE85F3E1CBC005C4111019D0A84D4AEC2E5438BD1BDDD8CC2EFEF847F1BBE3A9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-sources.jar";
      sha256 = "456B9B5A0CD6581923E8938305EAE7A61976706B4E771EF158FAF25F85F882DC";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar";
      sha256 = "0E72EC4EA955D0BAD7F1A494E8DF95163F1631DF0CE8EC4F9F278FE4D5FD1824";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom";
      sha256 = "093CA3B7FD4C3D48222F30DA4526808E3E8EF2D4456D1E75793F105D437A24EA";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-javadoc.jar";
      sha256 = "0B9578DBE2B2F35DD438546E3A6C1314950FDDC3232220FE250E498148D8E4AE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-sources.jar";
      sha256 = "1631F768D506FAA08E4C4769F5B07DD37BDD92720B44C0DC223F3EDE801F5734";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar";
      sha256 = "8F3DC6091DB688464AD8B1EE6C7343D7AA5940D474EE8B90406C71E45DD74FC0";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom";
      sha256 = "2255FD693D69DDD6954B6B7F614AF4ED93EB6AA6A27EBFE01E65DB194DAECAA9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar";
      sha256 = "9940E7CF343DFBDDDEB60B538E559496B836430400575405FE46C7176B95C78E";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar";
      sha256 = "11482BCB49B2E47BAEE89C3B1AE10C6A40B89E2FBB0DA2A423E062F444E13492";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar";
      sha256 = "321FB55685635C931EBA4BC0D7668349DA3F2C09AEE2DE93A70566066FF25C28";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom";
      sha256 = "22E81EE9D5349BA0E897ADB5C7FCEC25656C9E0B7B86C3E93E9A7AF360481C0D";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-javadoc.jar";
      sha256 = "F9412EED83A4FB68F6839B54DCA545CBA07F127D456060B81EC76C7781300E48";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-sources.jar";
      sha256 = "2B84D948A67FA7F5C4C6CCA9C4AEFB83BC3BED76DB69989D1E2D0977532942C2";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.jar";
      sha256 = "7427D7EE5771E8C36C1DB5A09368FA3078F6ECEB77D7C797A322A088C5DDDB76";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.pom";
      sha256 = "1C5DCB05333F33C0674D039E348789A7525208ED4F8316A9199D255B824E038A";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-javadoc.jar";
      sha256 = "F7D299D01D190E239144A4C74D4EB33FA92C057B1D8F161FB7D75FD07E6426C4";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-sources.jar";
      sha256 = "5C676791217D9B48560496556B8965CCEABCBFDBB65BBEBDC52E99C0A3847735";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar";
      sha256 = "4D6405395C4599CE04CEA08BA082339E3E42135DE9AAE2923C9F5367E957315A";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.pom";
      sha256 = "CBFFFF8D495FFD66C1234469A2965F54A82FA58E6816EE0E5803E896CAC167C3";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-javadoc.jar";
      sha256 = "58CAA3EAE25920DFBA5FACBC0C449CBA01994982E96C992D080E0EE52F886AE2";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-sources.jar";
      sha256 = "4589D87CC22D0C370BD1708F328D31B98B4BAED38D1BAA8F595CA1BD5CA528E6";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.jar";
      sha256 = "C342EAB071B314D125B3AC00C3CE3B2287A478A64639AD210BE7FFC25835CE01";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.pom";
      sha256 = "EBF9B8ED3CCEF14B5D8904401C60D92E32B276C12CD0A152C671D184EFF28C97";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-javadoc.jar";
      sha256 = "9DD282695276A298DB294BE7C50663D750598DDF1F4C07B5B54E9D48DEE5445E";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-sources.jar";
      sha256 = "5EDF42C3DE05267BD79F413EA22CDB7C53B99719395387E4A988D087DE7B2212";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.jar";
      sha256 = "502C7F02FF1F99E7B125537A456601AAF31A24C997BBC265C24CA6DD3B7442BD";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.pom";
      sha256 = "1DBE0A87AE1489F9419A416F96DB4D3EE12B351CB58A09B8EB9C8E8447AE5A92";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-javadoc.jar";
      sha256 = "D3421C2A8450FCF646ECCEADE47B5D8F3280BE3A68D8178C11DC2F8BF2EE0375";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-sources.jar";
      sha256 = "A41F082F90CFE665755AEDB007F0F82BA8499D4EF0F58253AFDD79DD3A1C63BA";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.jar";
      sha256 = "ADB18E5F79A028F2B33506CCC6A4B24500DD985628B05308A7AF5ACBD1EE2CD7";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.pom";
      sha256 = "7DE9EC96F383FCC18C17A0E7513071EC929F21D1CFD81EFC028BB307CC7E9BB7";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar";
      sha256 = "8DC4B97B764D6C5B732479936C6CA28DFE9480C8A9B67E4B26CF95C8C64D77BD";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar";
      sha256 = "C4BC93180A4F0ACEEC3B057A2514ABE04A79F06C174BBED910A2AFB227B79366";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar";
      sha256 = "FB82F52621D9DDAFB135DFF968A75B5BC08C40BA4BE77B5AB8DEA8711A032D72";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar";
      sha256 = "18C4A0095D5C1DA6B817592E767BB23D29DD2F560AD74DF75FF3961DBDE25B79";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom";
      sha256 = "7CD9D7A0B5D93DFD461A148891B43509CF403A9C7F9FB49060D3554DF1C81E1E";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom";
      sha256 = "18F5C52120DB036E88D6136F8839C832D074BDDA95C756C6F429249D2DB54AC6";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
  };
}
