# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.7";
      "sbtVersion" = "1.2.7";
    }];
  "repos" = {
    "nix-public" = "";
  };
  "artifacts" = {
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-javadoc.jar";
      sha256 = "EB80085BB9DB2326E42B4CE74E8B737788D6907687807113A57D82AE83B83519";
    };
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-sources.jar";
      sha256 = "480CB5E99519271C9256716D4BE1A27054047435FF72078D9DEAE5C6A19F63EB";
    };
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-tests.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3-tests.jar";
      sha256 = "DE17ABE08312A27F2DC70B05EC7BB528071F9D4E497F49F34FB55B15F2021258";
    };
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar";
      sha256 = "FB53F8539E7FCB8F093A56E138112056EC1DC809EBB020B59D8A36A5EBAC37E0";
    };
    "nix-public/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.pom";
      sha256 = "A051EB1A2548B93C99ABCA8EB71D5C75D2FF06976682960348124BC4901A5315";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-javadoc.jar";
      sha256 = "0560248F9CC788A2218BF8D739A3003EA0455E2243ACF399679DCB93C7816207";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-sources.jar";
      sha256 = "1F69B6B638EC551D26B10FEEADE5A2B77ABE347F9759DA95022F0DA9A63A9971";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-tests.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3-tests.jar";
      sha256 = "56A67B9087D1363DD722E53E564FBC571B9BD8349FB92889B44C01B114A1E7AA";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar";
      sha256 = "5946D837FE6F960C02A53EDA7A6926ECC3C758BBDD69AA453EE429F858217F22";
    };
    "nix-public/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.pom";
      sha256 = "DF4D7181EC51655BAAAAB067971180D7681643DDD274139F0C3078DBA14E97E0";
    };
    "nix-public/ch/qos/logback/logback-parent/1.2.3/logback-parent-1.2.3.pom" = {
      url = "https://repo1.maven.org/maven2/ch/qos/logback/logback-parent/1.2.3/logback-parent-1.2.3.pom";
      sha256 = "79CD021DAFC7B0255D3CDD3FD70CBAA638DF73995749A348EE82C45635EAB26A";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.12/akka-actor_2.12-2.5.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.12/akka-actor_2.12-2.5.12-javadoc.jar";
      sha256 = "B8C805A7B0C65494BAF65CF42A163405488CECCC60D75190A4BA2E1AA666A589";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.12/akka-actor_2.12-2.5.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.12/akka-actor_2.12-2.5.12-sources.jar";
      sha256 = "BF445518E08A2A351705082FC0D00886C07C3293699C839897D79C19B36D9D4C";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.12/akka-actor_2.12-2.5.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.12/akka-actor_2.12-2.5.12.jar";
      sha256 = "5F766C5CEFE013CA21E52FB17E5C0E2A693CA4E5261F575112D169540823F661";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.12/akka-actor_2.12-2.5.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.12/akka-actor_2.12-2.5.12.pom";
      sha256 = "CFC10BA20E738FCF83DA5DA26426C25B2C59A3214AC943A06E4F5E63357AF263";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.18/akka-actor_2.12-2.5.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.18/akka-actor_2.12-2.5.18-javadoc.jar";
      sha256 = "643FE7469DC07D63A39CAE8C31E8F10416B52B041BD689D9EA5A2C6D9DEAF86A";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.18/akka-actor_2.12-2.5.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.18/akka-actor_2.12-2.5.18-sources.jar";
      sha256 = "5561E79AE4F94AC5280437F5D2A02C04E170DC6685023117C12F56A739CF137A";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.18/akka-actor_2.12-2.5.18.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.18/akka-actor_2.12-2.5.18.jar";
      sha256 = "281092B35B39FF7EE8385E1062D999FE82F08AD1F2500FA89D226EAD671F77E2";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.18/akka-actor_2.12-2.5.18.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.18/akka-actor_2.12-2.5.18.pom";
      sha256 = "2DE003381E4892BB2EBB439208197E8E09CB3386E9F8CA162E9056EDD954F37C";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19-javadoc.jar";
      sha256 = "E01EE501EA07690009422BDDAF607704E193CC0ECA89277C9E418C9ABC18A752";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19-sources.jar";
      sha256 = "5F4A9A2B8E8F258DE65C7B7BEEAF5814E7B946E2A82D947C2DE3EF9F15F55EA5";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19.jar";
      sha256 = "33B5EEF9DB3766A7E7A307457995FDE116967EAD482C88377B2466475D8F703B";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19.pom";
      sha256 = "E901E8A1C7609AD05F99E90234A132BB8EBF095DE991DB29DABD11B0D59CE88A";
    };
    "nix-public/com/typesafe/akka/akka-http-core_2.12/10.1.4/akka-http-core_2.12-10.1.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-core_2.12/10.1.4/akka-http-core_2.12-10.1.4-javadoc.jar";
      sha256 = "D2D371668EA97A8F6B5D9A1E11CF95590999ADB0A6A9F066EF014CF7EAA474D9";
    };
    "nix-public/com/typesafe/akka/akka-http-core_2.12/10.1.4/akka-http-core_2.12-10.1.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-core_2.12/10.1.4/akka-http-core_2.12-10.1.4-sources.jar";
      sha256 = "E532C4922C58C5C7ECE0654694EA4D6F69CB732B5CA833D3466C360ABDD82864";
    };
    "nix-public/com/typesafe/akka/akka-http-core_2.12/10.1.4/akka-http-core_2.12-10.1.4.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-core_2.12/10.1.4/akka-http-core_2.12-10.1.4.jar";
      sha256 = "108F5D6ECB207921FD804ECCEC7DA9853EB0011E540640EF45289CD7C3F1F26D";
    };
    "nix-public/com/typesafe/akka/akka-http-core_2.12/10.1.4/akka-http-core_2.12-10.1.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-core_2.12/10.1.4/akka-http-core_2.12-10.1.4.pom";
      sha256 = "B52C291AF2C041D425011247ACA02568D11FB1D9466B8600AA0A8F97E4402CBF";
    };
    "nix-public/com/typesafe/akka/akka-http-spray-json_2.12/10.1.4/akka-http-spray-json_2.12-10.1.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-spray-json_2.12/10.1.4/akka-http-spray-json_2.12-10.1.4-javadoc.jar";
      sha256 = "5B66047634FF67FA9BC70106A243FC6D7D302A294886E931CEA959CC24CF2793";
    };
    "nix-public/com/typesafe/akka/akka-http-spray-json_2.12/10.1.4/akka-http-spray-json_2.12-10.1.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-spray-json_2.12/10.1.4/akka-http-spray-json_2.12-10.1.4-sources.jar";
      sha256 = "09D4C2F09BEC4049B5EDD3DB5C53989C5DDB6F62E75C21CE0952557D84DE089D";
    };
    "nix-public/com/typesafe/akka/akka-http-spray-json_2.12/10.1.4/akka-http-spray-json_2.12-10.1.4.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-spray-json_2.12/10.1.4/akka-http-spray-json_2.12-10.1.4.jar";
      sha256 = "44699082F3D90D83514BA78C74BAD568433C5C48E5977CCF27C6003ADEEC6CEA";
    };
    "nix-public/com/typesafe/akka/akka-http-spray-json_2.12/10.1.4/akka-http-spray-json_2.12-10.1.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-spray-json_2.12/10.1.4/akka-http-spray-json_2.12-10.1.4.pom";
      sha256 = "994EB3F30FBE4832D68E24030EDAF32708EE7AED259F445CD241E2740B5A4658";
    };
    "nix-public/com/typesafe/akka/akka-http-testkit_2.12/10.1.4/akka-http-testkit_2.12-10.1.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-testkit_2.12/10.1.4/akka-http-testkit_2.12-10.1.4-javadoc.jar";
      sha256 = "A33FB87C8DC0970BD5C4CA4DCD1B15A74582F8D0276FABCB75B7686E4E53F6FE";
    };
    "nix-public/com/typesafe/akka/akka-http-testkit_2.12/10.1.4/akka-http-testkit_2.12-10.1.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-testkit_2.12/10.1.4/akka-http-testkit_2.12-10.1.4-sources.jar";
      sha256 = "B10140169F6B12FA6587543A4D1FDD7279EB26C8579423E71598EB78B0D8AD20";
    };
    "nix-public/com/typesafe/akka/akka-http-testkit_2.12/10.1.4/akka-http-testkit_2.12-10.1.4.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-testkit_2.12/10.1.4/akka-http-testkit_2.12-10.1.4.jar";
      sha256 = "C5B2943C5BBDA36F744D308644FDCAF6AF8BEFF25E97D56C08F01A8539D48A6D";
    };
    "nix-public/com/typesafe/akka/akka-http-testkit_2.12/10.1.4/akka-http-testkit_2.12-10.1.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http-testkit_2.12/10.1.4/akka-http-testkit_2.12-10.1.4.pom";
      sha256 = "82A50D4D9FA9D6C9671BA07C50324E33BB42BF39F5FFFB58548972FEBE25081B";
    };
    "nix-public/com/typesafe/akka/akka-http_2.12/10.1.4/akka-http_2.12-10.1.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http_2.12/10.1.4/akka-http_2.12-10.1.4-javadoc.jar";
      sha256 = "2051622469BCAC1AC808D9920A142DCD44C8430183EABA2E81A914BB35AC9EEA";
    };
    "nix-public/com/typesafe/akka/akka-http_2.12/10.1.4/akka-http_2.12-10.1.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http_2.12/10.1.4/akka-http_2.12-10.1.4-sources.jar";
      sha256 = "55110C6ACF0DDF5E1D19964D220A6823E928197009DB3EE2BD62D4EB5CCECF24";
    };
    "nix-public/com/typesafe/akka/akka-http_2.12/10.1.4/akka-http_2.12-10.1.4.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http_2.12/10.1.4/akka-http_2.12-10.1.4.jar";
      sha256 = "9B8BDC14C3BE4AC3F0032F664036A5D43D0C96C27BF693FBA1FC5EEAF74D079B";
    };
    "nix-public/com/typesafe/akka/akka-http_2.12/10.1.4/akka-http_2.12-10.1.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-http_2.12/10.1.4/akka-http_2.12-10.1.4.pom";
      sha256 = "0586ADC798E625EBF6548744E3C42DA961927B979CB984D42648BD19954304B4";
    };
    "nix-public/com/typesafe/akka/akka-parsing_2.12/10.1.4/akka-parsing_2.12-10.1.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-parsing_2.12/10.1.4/akka-parsing_2.12-10.1.4-javadoc.jar";
      sha256 = "11B16F7122A578753C90B9EF57EA13DC833E22C1A3C633893F60F0905832B88C";
    };
    "nix-public/com/typesafe/akka/akka-parsing_2.12/10.1.4/akka-parsing_2.12-10.1.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-parsing_2.12/10.1.4/akka-parsing_2.12-10.1.4-sources.jar";
      sha256 = "A1E3A7954195497A4F6ACD938829A8ABE3EBA80DC947A2B86B412B70D51B5AB7";
    };
    "nix-public/com/typesafe/akka/akka-parsing_2.12/10.1.4/akka-parsing_2.12-10.1.4.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-parsing_2.12/10.1.4/akka-parsing_2.12-10.1.4.jar";
      sha256 = "D21165EA458ECD78BBB7A92CB2225C0A82E0F3F8C1A543224597B592985EF3C8";
    };
    "nix-public/com/typesafe/akka/akka-parsing_2.12/10.1.4/akka-parsing_2.12-10.1.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-parsing_2.12/10.1.4/akka-parsing_2.12-10.1.4.pom";
      sha256 = "D354BCEB26990073F624EF418435512C0874572585C7F554818C7E44D6278310";
    };
    "nix-public/com/typesafe/akka/akka-protobuf_2.12/2.5.12/akka-protobuf_2.12-2.5.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.12/2.5.12/akka-protobuf_2.12-2.5.12-javadoc.jar";
      sha256 = "5E55DCA3BFD2EE8C2007D69124BE56F79862B45BBF527A10483BD0B0B5BA18DD";
    };
    "nix-public/com/typesafe/akka/akka-protobuf_2.12/2.5.12/akka-protobuf_2.12-2.5.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.12/2.5.12/akka-protobuf_2.12-2.5.12-sources.jar";
      sha256 = "7A72E40681B48F5895D7FDDE4517F58F031D3FFC0F4E8A27E173AF02BEA62C19";
    };
    "nix-public/com/typesafe/akka/akka-protobuf_2.12/2.5.12/akka-protobuf_2.12-2.5.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.12/2.5.12/akka-protobuf_2.12-2.5.12.jar";
      sha256 = "C49017FC3FD97B60F92A6C74026AD29DD913A43415FC19B66D08EC26B176A907";
    };
    "nix-public/com/typesafe/akka/akka-protobuf_2.12/2.5.12/akka-protobuf_2.12-2.5.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.12/2.5.12/akka-protobuf_2.12-2.5.12.pom";
      sha256 = "8723C094047439AB28A9A9EA94D332B1E9B2622AEB69D002A81AEC587DAF53F4";
    };
    "nix-public/com/typesafe/akka/akka-protobuf_2.12/2.5.19/akka-protobuf_2.12-2.5.19-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.12/2.5.19/akka-protobuf_2.12-2.5.19-javadoc.jar";
      sha256 = "AC0AE1343FE8D9F42AC65F0952769B3F0F7683B8ED4AE8AE11382020B919799F";
    };
    "nix-public/com/typesafe/akka/akka-protobuf_2.12/2.5.19/akka-protobuf_2.12-2.5.19-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.12/2.5.19/akka-protobuf_2.12-2.5.19-sources.jar";
      sha256 = "F283B548F63613E034A0841E2EAF347C45D8B1C59BDDCEAC6DD27F346E62F1FD";
    };
    "nix-public/com/typesafe/akka/akka-protobuf_2.12/2.5.19/akka-protobuf_2.12-2.5.19.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.12/2.5.19/akka-protobuf_2.12-2.5.19.jar";
      sha256 = "148401AB94C9B95EFB4AC9F9BBA3915B53C72BB0A05E26B3D5B00BB3DCF80CEE";
    };
    "nix-public/com/typesafe/akka/akka-protobuf_2.12/2.5.19/akka-protobuf_2.12-2.5.19.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-protobuf_2.12/2.5.19/akka-protobuf_2.12-2.5.19.pom";
      sha256 = "AAB203EDC49F365E195A38384CD32F49AB53B7C03BF766C4890B6C00C468A5E6";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19-javadoc.jar";
      sha256 = "07F637E2F1F5E39DE68E30AB56E132A6EF5F71D1D2E9DC0A176AA2C380C48574";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19-sources.jar";
      sha256 = "9C3F15703C2179442C876B50578711607AFDC05715D983ACCA36B8939C534880";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19.jar";
      sha256 = "2676E9D6E9F3B712A49DB3DF0A8C3B0DB3DC89C8846295D12C3CF274C8CDE6DD";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19.pom";
      sha256 = "DA1D7A410E7491511C563BA4AD032C9ACA2A64A598C605AB7DA730D4A91956E7";
    };
    "nix-public/com/typesafe/akka/akka-stream-testkit_2.12/2.5.12/akka-stream-testkit_2.12-2.5.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream-testkit_2.12/2.5.12/akka-stream-testkit_2.12-2.5.12-javadoc.jar";
      sha256 = "AD7BC1F1FD8603F77C3E2DB92D9D5C11EBD1F083643DAEF6F7ED42C4F01AA6F2";
    };
    "nix-public/com/typesafe/akka/akka-stream-testkit_2.12/2.5.12/akka-stream-testkit_2.12-2.5.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream-testkit_2.12/2.5.12/akka-stream-testkit_2.12-2.5.12-sources.jar";
      sha256 = "1B68130A09EF727F1A26EE3A47A26AA7FF83FBFB0B5812961A031505093E24BE";
    };
    "nix-public/com/typesafe/akka/akka-stream-testkit_2.12/2.5.12/akka-stream-testkit_2.12-2.5.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream-testkit_2.12/2.5.12/akka-stream-testkit_2.12-2.5.12.jar";
      sha256 = "BA84F74F4D6FB3CB2ADE3C0A4E96BC5851C748410414B2686D7375E4B8D145EA";
    };
    "nix-public/com/typesafe/akka/akka-stream-testkit_2.12/2.5.12/akka-stream-testkit_2.12-2.5.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream-testkit_2.12/2.5.12/akka-stream-testkit_2.12-2.5.12.pom";
      sha256 = "C846841ED04A77D80225874BE18F2A1509258177D1B1A82F073A541120C7B9D0";
    };
    "nix-public/com/typesafe/akka/akka-stream_2.12/2.5.12/akka-stream_2.12-2.5.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream_2.12/2.5.12/akka-stream_2.12-2.5.12-javadoc.jar";
      sha256 = "0BF89F7E3D86127419A632203BE58DC5F24CDD3D20FAF90333BDFFE1E63E062D";
    };
    "nix-public/com/typesafe/akka/akka-stream_2.12/2.5.12/akka-stream_2.12-2.5.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream_2.12/2.5.12/akka-stream_2.12-2.5.12-sources.jar";
      sha256 = "BDD31DB5E1F7878E19B5A2E81F2F9FC1BF384CACB87A9D9AF0DA535EF85F0C57";
    };
    "nix-public/com/typesafe/akka/akka-stream_2.12/2.5.12/akka-stream_2.12-2.5.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream_2.12/2.5.12/akka-stream_2.12-2.5.12.jar";
      sha256 = "B1BCD6981D8BFCF8C2E3EBE21656FD3EE0398475181397556D169679483AAC1C";
    };
    "nix-public/com/typesafe/akka/akka-stream_2.12/2.5.12/akka-stream_2.12-2.5.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream_2.12/2.5.12/akka-stream_2.12-2.5.12.pom";
      sha256 = "7DA76DA9ED5ADBEFB51057C4815A9C1755BB5017D86F32B8F8994A2BA0F605D5";
    };
    "nix-public/com/typesafe/akka/akka-stream_2.12/2.5.19/akka-stream_2.12-2.5.19-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream_2.12/2.5.19/akka-stream_2.12-2.5.19-javadoc.jar";
      sha256 = "3C03307146777AAFAE9B63B30332C8B150685F0A1790C0EFA5D48DDBEF96192D";
    };
    "nix-public/com/typesafe/akka/akka-stream_2.12/2.5.19/akka-stream_2.12-2.5.19-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream_2.12/2.5.19/akka-stream_2.12-2.5.19-sources.jar";
      sha256 = "4B4721EF336B06B05238ED13EF772BEE2DBC06D3DE2622CF5776B1D6382EC3CB";
    };
    "nix-public/com/typesafe/akka/akka-stream_2.12/2.5.19/akka-stream_2.12-2.5.19.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream_2.12/2.5.19/akka-stream_2.12-2.5.19.jar";
      sha256 = "EB254BE1E088716139E05D9F6D46AB5E6C41EE0771B08789990267EF7B82B309";
    };
    "nix-public/com/typesafe/akka/akka-stream_2.12/2.5.19/akka-stream_2.12-2.5.19.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-stream_2.12/2.5.19/akka-stream_2.12-2.5.19.pom";
      sha256 = "895EF0EB4DD0B431DDA5CE87337F9260B1C99D0AAB4F0338DCB7AF08E63E3562";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.12/akka-testkit_2.12-2.5.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.12/akka-testkit_2.12-2.5.12-javadoc.jar";
      sha256 = "8D2703042DAF5AFA4D3244D3D50FD0D021E41261120FB329EAB1E3FC1E610842";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.12/akka-testkit_2.12-2.5.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.12/akka-testkit_2.12-2.5.12-sources.jar";
      sha256 = "F487EBA825A3316F68C609F7F1AD2F8A22BEADC19893D9B97656CCA89D1D2EA1";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.12/akka-testkit_2.12-2.5.12.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.12/akka-testkit_2.12-2.5.12.jar";
      sha256 = "C36F58FE1F5FA574B9795C9457B07DA068ECDF2A60B3EF85F1E6A4434CC4B26E";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.12/akka-testkit_2.12-2.5.12.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.12/akka-testkit_2.12-2.5.12.pom";
      sha256 = "764FDF34E78CA0BC8C14A0E793584E59A2D48098C1BE2F478BFDF2780BB24780";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.18/akka-testkit_2.12-2.5.18-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.18/akka-testkit_2.12-2.5.18-javadoc.jar";
      sha256 = "D787ECE1605F95888E19262AE446E06EAB0D2D83B35E3CF19F049E50778A6794";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.18/akka-testkit_2.12-2.5.18-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.18/akka-testkit_2.12-2.5.18-sources.jar";
      sha256 = "62F725DAC95BD1C5B992B06DB9ABC86838436715EB37987ADDCC116F60378939";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.18/akka-testkit_2.12-2.5.18.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.18/akka-testkit_2.12-2.5.18.jar";
      sha256 = "F04177F79ED620DE111183A60834058353FA4067F3F7757E74D7E2D226B52D9C";
    };
    "nix-public/com/typesafe/akka/akka-testkit_2.12/2.5.18/akka-testkit_2.12-2.5.18.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-testkit_2.12/2.5.18/akka-testkit_2.12-2.5.18.pom";
      sha256 = "511213409A525E3A42ED504B991BB92FBB015AC26A643205335C9B24255E5B18";
    };
    "nix-public/com/typesafe/config/1.2.0/config-1.2.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.2.0/config-1.2.0-javadoc.jar";
      sha256 = "EDC4331FE63BF5DC7C10D1D8BE87F76360F482EB91B5839622B9BF50692B4ABA";
    };
    "nix-public/com/typesafe/config/1.2.0/config-1.2.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.2.0/config-1.2.0-sources.jar";
      sha256 = "1ACF655899A53E9ACC577CB9D47E466095D83532CDFD1B17DD8E6F5C1C02642C";
    };
    "nix-public/com/typesafe/config/1.2.0/config-1.2.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.2.0/config-1.2.0.jar";
      sha256 = "56F2C2E8ACB95FB1E358B1E3FAEF2D565782C2A528747B01AF8DD8E8BD87BD60";
    };
    "nix-public/com/typesafe/config/1.2.0/config-1.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.2.0/config-1.2.0.pom";
      sha256 = "057A2C5F4D6A0AEEB8B74B0A1A020F8B84B425768DEBE878CEB04E5A6CEEE522";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2-javadoc.jar";
      sha256 = "57619C3DC0DC23DC74F0B1E14DEE7C87C5118B6700ECFE7400D2742D091C099F";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2-sources.jar";
      sha256 = "65995ABD56D6AA99EE7F46E7CDAAAAC2968554B16B26D38BF67E13706A12CA82";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.jar";
      sha256 = "6563D1723F3300BF596F41E40BC03E54986108B5C45D0AC34EBC66D48C2E25A3";
    };
    "nix-public/com/typesafe/config/1.3.2/config-1.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.2/config-1.3.2.pom";
      sha256 = "07EE48EC393761693CB95E2D1778CCAF3AD680312E94EB27C0059B8E06C98DBA";
    };
    "nix-public/com/typesafe/config/1.3.3/config-1.3.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.3/config-1.3.3-javadoc.jar";
      sha256 = "131B1CFF95E3F64FD6DF84695CA0D3C2FC85A9C08CDE9B9D86DB3EDC9E1561ED";
    };
    "nix-public/com/typesafe/config/1.3.3/config-1.3.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.3/config-1.3.3-sources.jar";
      sha256 = "FCD7C3070417C776B313CC559665C035D74E3A2B40A89BBB0E9BFF6E567C9CC8";
    };
    "nix-public/com/typesafe/config/1.3.3/config-1.3.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.3/config-1.3.3.jar";
      sha256 = "B5F1D6071F1548D05BE82F59F9039C7D37A1787BD8E3C677E31EE275AF4A4621";
    };
    "nix-public/com/typesafe/config/1.3.3/config-1.3.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.3/config-1.3.3.pom";
      sha256 = "2C268553F771EB572C41AD89EE043DC288B4A700FA51B6263B04EFF92867781C";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.3/ssl-config-core_2.12-0.2.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.3/ssl-config-core_2.12-0.2.3-javadoc.jar";
      sha256 = "0E22BAFBA55AE5123A87A5027547431C20737BA4E76295542ED74B33F04A4680";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.3/ssl-config-core_2.12-0.2.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.3/ssl-config-core_2.12-0.2.3-sources.jar";
      sha256 = "0A8FA86CA2612045127F28FB543E07607C4CD648C08C620070A186679F60BB98";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.3/ssl-config-core_2.12-0.2.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.3/ssl-config-core_2.12-0.2.3.jar";
      sha256 = "A01C3A3972EDA913FCC5C459F1E7AB0C13327984B9DEF207C147F8567790EEF4";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.2.3/ssl-config-core_2.12-0.2.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.2.3/ssl-config-core_2.12-0.2.3.pom";
      sha256 = "50E7FD074FF01366757C386D65CDD5261A7FFDF15EC0FD8BA1765ED471CDF732";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.3.6/ssl-config-core_2.12-0.3.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.3.6/ssl-config-core_2.12-0.3.6-javadoc.jar";
      sha256 = "1967A4C6E1371BE091EEB5858D7C04C5A01194D2CD8B171C365667694DE220A5";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.3.6/ssl-config-core_2.12-0.3.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.3.6/ssl-config-core_2.12-0.3.6-sources.jar";
      sha256 = "1357AC5D5BDBAC879EAA8C29136D570789670634E6635634E84C51E32D71801F";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.3.6/ssl-config-core_2.12-0.3.6.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.3.6/ssl-config-core_2.12-0.3.6.jar";
      sha256 = "EE78ABC0773E1044A141631C08F9A8396A77034E69AD0524394EC99597CDC193";
    };
    "nix-public/com/typesafe/ssl-config-core_2.12/0.3.6/ssl-config-core_2.12-0.3.6.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/ssl-config-core_2.12/0.3.6/ssl-config-core_2.12-0.3.6.pom";
      sha256 = "3B10CB521F4BDFF518E6898FFFD38D7710624EF7C444C6645053CE14AD098243";
    };
    "nix-public/commons-codec/commons-codec/1.14/commons-codec-1.14-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.14/commons-codec-1.14-javadoc.jar";
      sha256 = "9F66EA5729A912701729D1A1F6FCD1CD467E4B7EEEED224E74AD060241A8089B";
    };
    "nix-public/commons-codec/commons-codec/1.14/commons-codec-1.14-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.14/commons-codec-1.14-sources.jar";
      sha256 = "8F039D63B9E02A66F47C8BDA13D389F2C7CA6FDD115F6294C58A0B628F7E568A";
    };
    "nix-public/commons-codec/commons-codec/1.14/commons-codec-1.14-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.14/commons-codec-1.14-tests.jar";
      sha256 = "263967D029763055C55C0264E912D5EA747DF584AF74D418B3540F1310563CFD";
    };
    "nix-public/commons-codec/commons-codec/1.14/commons-codec-1.14.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.14/commons-codec-1.14.jar";
      sha256 = "A128E4F93FABE5381DED64CF2873019E06030B718EB43CEEAE0B0E5D17AD33E9";
    };
    "nix-public/commons-codec/commons-codec/1.14/commons-codec-1.14.pom" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.14/commons-codec-1.14.pom";
      sha256 = "968560C2F849976FF8BEC6C0C81AE1BCA2085EC30CBFB36B3AFA1CAE0610B7A6";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.4/spray-json_2.12-1.3.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.4/spray-json_2.12-1.3.4-javadoc.jar";
      sha256 = "6A880487ABC31642E8596E0C6B7CF06B96E471D50554C1E6BDF44DC9AB4096A7";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.4/spray-json_2.12-1.3.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.4/spray-json_2.12-1.3.4-sources.jar";
      sha256 = "B7C8DF2C2035CA677AEAE1DA2B9E40E63CB34964F59B5765D6ED3075F598DC7F";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.4/spray-json_2.12-1.3.4.jar" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.4/spray-json_2.12-1.3.4.jar";
      sha256 = "339784F9E67A9EABC1D366925909E4C74FFBC6D6539BA1F22896242F0F8A5CC6";
    };
    "nix-public/io/spray/spray-json_2.12/1.3.4/spray-json_2.12-1.3.4.pom" = {
      url = "https://repo1.maven.org/maven2/io/spray/spray-json_2.12/1.3.4/spray-json_2.12-1.3.4.pom";
      sha256 = "769A5C51DF3A7B04A0BFE8DF11FDB4A6B51EA60BF67B458A32E8649BCBD67F3A";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-javadoc.jar";
      sha256 = "EBD162363C0A6CA9E52AF51D7377F78F559D3F2663DC896E0DBF3B16A0188972";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-sources.jar";
      sha256 = "319A840705E1E46ABE579DD3D079B508558791E0236BC78DA01911748E06AF93";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-tests.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-tests.jar";
      sha256 = "AE143A7DC135371F446A44775E8D5337D97151D5FEEC8CA8575F3A718DDF35F3";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar";
      sha256 = "97D1ACAAC82409BE42E622D7A54D3AE9D08517E8AEFDEA3D2BA9791150C2F02D";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom";
      sha256 = "1DF7B6F08DFB81A268D6B93B659A6A9E389C5D8C32BDF0754238BA6483A4E982";
    };
    "nix-public/junit/junit/4.12/junit-4.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12-javadoc.jar";
      sha256 = "84354AA70F995A7FF3C96B144C49B7FE90A0C6E21F818FD23B17F75B17FD1CA9";
    };
    "nix-public/junit/junit/4.12/junit-4.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12-sources.jar";
      sha256 = "9F43FEA92033AD82BCAD2AE44CEC5C82ABC9D6EE4B095CAB921D11EAD98BF2FF";
    };
    "nix-public/junit/junit/4.12/junit-4.12.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar";
      sha256 = "59721F0805E223D84B90677887D9FF567DC534D7C502CA903C0C2B17F05C116A";
    };
    "nix-public/junit/junit/4.12/junit-4.12.pom" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.pom";
      sha256 = "90F163F78E3FFB6F1C7AD97DE9E7EBA4EEA25807141B85D6D12BE67CA25449C4";
    };
    "nix-public/org/apache/apache/21/apache-21.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/21/apache-21.pom";
      sha256 = "AF10C108DA014F17CAFAC7B52B2B4B5A3A1C18265FA2AF97A325D9143537B380";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-javadoc.jar";
      sha256 = "0C58DB4A8025C70D5CB3E068E0917144823211F041C60C60A99D65D4931506FB";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-sources.jar";
      sha256 = "D97341CE0A7554028DB3403E407BB51F4D902BF3287F64F709D7A8156EAF1910";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-tests.jar";
      sha256 = "25A3DBC30E9DFF627F088ED61995DA3C2912E2173C79A45CE85B60CDF93B22D9";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar";
      sha256 = "DE2E1DCDCF3EF917A8CE858661A06726A9A944F28E33AD7F9E08BEA44DC3C230";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.pom";
      sha256 = "A4022429B98425B430181915721279A52F610F34648BDAC487D4CACBBE8DFEB5";
    };
    "nix-public/org/apache/commons/commons-parent/48/commons-parent-48.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/48/commons-parent-48.pom";
      sha256 = "1E1F7DE9370A7B7901F128F1DACD1422BE74E3F47F9558B0F79E04C0637CA0B4";
    };
    "nix-public/org/apache/commons/commons-parent/50/commons-parent-50.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/50/commons-parent-50.pom";
      sha256 = "7B7A2DB3F747074B5867F553D5EFC8072BE26EDE32879D052C347E7C81117F06";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-javadoc.jar";
      sha256 = "27F7327AEE87324952DA2405B02094DF40A4E772B48DAE7E419D8B50067CA745";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar";
      sha256 = "E223D2D8FBAFD66057A8848CC94222D63C3CEDD652CC48EDDC0AB5C39C0F84DF";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar";
      sha256 = "66FDEF91E9739348DF7A096AA384A5685F4E875584CCE89386A7A47251C4D8E9";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom";
      sha256 = "FDE386A7905173A1B103DE6AB820727584B50D0E32282E2797787C20A64FFA93";
    };
    "nix-public/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom";
      sha256 = "6D535F94EFB663BDB682C9F27A50335394688009642BA7A9677504BC1BE4129B";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-javadoc.jar";
      sha256 = "D6FDA7686D9B8C7A4A2FDBB7C8E17036D07A090C2C701D6CB0AB58A1812A4003";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2-sources.jar";
      sha256 = "963A6480F46A64013D0F144BA41C6C6E63C4D34B655761717A436492886F3667";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar";
      sha256 = "CC09AB0B140E0D0496C2165D4B32CE24F4D6446C0A26C5DC77B06BDF99EE8FAE";
    };
    "nix-public/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.pom";
      sha256 = "5B626A99E5734BA8D0C0C8C3FC6258AFA0624F4CE61AE1192247D03C57463DED";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-javadoc.jar";
      sha256 = "9175A09E404F75EC013219B54A51DF8788F890E0443BAE7A96FFC1AE74EF24F2";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-sources.jar";
      sha256 = "C0926003987A5C21108748FDA401023485085EAA9FE90A41A40BCF67596FFF34";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar";
      sha256 = "D9D5DFD1BC49A8158E6E0A90B2ED08FA602984D815C00AF16CEC53557E83EF8E";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.pom";
      sha256 = "49E2711154CE9BA76962E043F4F8A6D0B890CD9E2FC6D0E99C3A0E6AD6C1950E";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.0/scala-parser-combinators_2.12-1.1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.0/scala-parser-combinators_2.12-1.1.0-javadoc.jar";
      sha256 = "E5D248EB7E7F228616DA446E221E1B58E88676B458B5979040E1B560CA00125C";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.0/scala-parser-combinators_2.12-1.1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.0/scala-parser-combinators_2.12-1.1.0-sources.jar";
      sha256 = "08D173EC107691C45A2CDDF698DF21600DEA1C720EF3B0DBEB84B42D133D7290";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.0/scala-parser-combinators_2.12-1.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.0/scala-parser-combinators_2.12-1.1.0.jar";
      sha256 = "102F2A13EFAE9486CB4FC01AA4EB92C0543DBD8403F825041746C689F80556E3";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.0/scala-parser-combinators_2.12-1.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.0/scala-parser-combinators_2.12-1.1.0.pom";
      sha256 = "5F197D494FBB2D7399BDC88E11C772F6171630400BC08B2065C0629B792FD965";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.1/scala-parser-combinators_2.12-1.1.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.1/scala-parser-combinators_2.12-1.1.1-javadoc.jar";
      sha256 = "EE8441088E133BA160A5809A2986745D18D94E160994EA86307B4DBC5ADF95D4";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.1/scala-parser-combinators_2.12-1.1.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.1/scala-parser-combinators_2.12-1.1.1-sources.jar";
      sha256 = "B005FF7606449700F8EC6D8B5866E1A7D62B80B00B80C005BB4D2677EB353624";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.1/scala-parser-combinators_2.12-1.1.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.1/scala-parser-combinators_2.12-1.1.1.jar";
      sha256 = "A8A2C6B31457C9EF15C63F5F1AC6B45E6B979059627E38C24416A900098FFB2E";
    };
    "nix-public/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.1/scala-parser-combinators_2.12-1.1.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.12/1.1.1/scala-parser-combinators_2.12-1.1.1.pom";
      sha256 = "9B6BA98C00BB49399F0E0C50BE5BF13B4E0AB96612837ECA2E635A4B3B58440B";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar";
      sha256 = "FF42809FBF887885C957B3D368A909C6CCDDEA4C0485E4FE3A6465ED7747B636";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar";
      sha256 = "A7E8AAC79394DF396AFDA98B35537791809D815CE15AB2224F7D31E50C753922";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar";
      sha256 = "7CC3B6CEB56E879CB977E8E043F4BFE2E062F78795EFD7EFA09F85003CB3230A";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom";
      sha256 = "A8FDB9C75E3333D442F2CBE283F1E0F8573FF33F87CFE6DC22D154ABD0D29A0B";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-javadoc.jar";
      sha256 = "6816438CEB8357C14C0202D7B8F1CE9102C610944404E201D8601BD0EF65A9D1";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-sources.jar";
      sha256 = "676F9865EEE108B703D812A21BA0BD9530E166157D431171CDC1964D359D514F";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.jar";
      sha256 = "6E80EF4493127214D31631287A6789170BF6C9A771D6094ACD8DC785E8970270";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.pom";
      sha256 = "4E26B26FF0282A498515FAD296AE3949C071143C64C309FB0E4081DFCB1C46A5";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-javadoc.jar";
      sha256 = "E5B8691423267DDF1343BA45684C53884D67588B83CAC89EDC17C0D5A4FC5057";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-sources.jar";
      sha256 = "51706711A1399F06206745907F188815C31F2DD95B39B01F0E2C2FC78B0E7E3B";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.jar";
      sha256 = "F34E9119F45ABD41E85B9E121BA19DD9288B3B4AF7F7047E86DC70236708D170";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.pom";
      sha256 = "CD113C73BD725B366F196015680C74916F7510E649799D45DED1A7E488D58E7F";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-javadoc.jar";
      sha256 = "BE85F3E1CBC005C4111019D0A84D4AEC2E5438BD1BDDD8CC2EFEF847F1BBE3A9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-sources.jar";
      sha256 = "456B9B5A0CD6581923E8938305EAE7A61976706B4E771EF158FAF25F85F882DC";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar";
      sha256 = "0E72EC4EA955D0BAD7F1A494E8DF95163F1631DF0CE8EC4F9F278FE4D5FD1824";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom";
      sha256 = "093CA3B7FD4C3D48222F30DA4526808E3E8EF2D4456D1E75793F105D437A24EA";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1-javadoc.jar";
      sha256 = "7F6BF6122E13E034507118BAB9D61C3BD41637E24C2120D41690C2D8F542FACA";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1-sources.jar";
      sha256 = "4F73F24D18108DF3641A6333A1F2BE4F43FCCA982A3A769A5F6C8F99558293CD";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.jar";
      sha256 = "9DAB78F3F205A038F48183B2391F8A593235F794D8129A479E06AF3E6BC50EF8";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.pom";
      sha256 = "E2C373E1C000D8431BD625729DB33DCE68B379D3537769D29E18514CB2B3050C";
    };
    "nix-public/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3-javadoc.jar";
      sha256 = "41060AC769EA5450965D3896E36024CC1239BF38EA18A2BD60600381099123F1";
    };
    "nix-public/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3-sources.jar";
      sha256 = "625126C241E93801CD2F293AAFA60670B196CF93DC740E18AB324AF18B3DE5C7";
    };
    "nix-public/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.jar";
      sha256 = "A8DD181A996DCC53A8C0BBB554BEF7A1A9017CA09A377603167CF15444A85404";
    };
    "nix-public/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.3/scala-library-2.12.3.pom";
      sha256 = "38CA83C7A1EE7BCEAD63C4114C712E92B39125C8E8D463D36EE13125E39BA7D5";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-javadoc.jar";
      sha256 = "23443C33B32E3CC9FF6BABB69012E4CD0D4D68CB2AA6B19ADDE1FB274BD45F58";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-sources.jar";
      sha256 = "B9C34CF968A0E348ECEC32837797A794FFEADE2FE016323474FE756CB7D74042";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar";
      sha256 = "17824FCEE4D3F46CFAA4DA84EBAD4F58496426C2B9BC9E341F812AB23A667D5D";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.pom";
      sha256 = "63BDCD46CED3D72F03C38DFCDAF610BB94A286E317C072078D8E0B729B55A099";
    };
    "nix-public/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5-javadoc.jar";
      sha256 = "81EE9FCE5DB0E48FE2FCAA2431FCEC7A3E34E2AD96AA5D729E81399D3DD45AD9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5-sources.jar";
      sha256 = "0866105EC1FDFC0CA8C7EF04DE70BC1628E585D5496FA7B3FB7B2A9661119D30";
    };
    "nix-public/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.jar";
      sha256 = "C2636320D6479C82F2DA6B8D76A820DE9345A61327E648D4298A0048154FB87C";
    };
    "nix-public/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.5/scala-library-2.12.5.pom";
      sha256 = "0C524D9C1E14F0C6AEB58A03FFC0F7D3428DA3E3BD6B727D2F80E52603438719";
    };
    "nix-public/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6-javadoc.jar";
      sha256 = "19ADE75C094BA520EE7748DFDA58A5259E16342C9E79AE1EC217D330CE7ACDF2";
    };
    "nix-public/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6-sources.jar";
      sha256 = "E1B905FD404095BCFF7E26E750C396C7B4B193044F60555147142D24427AEAF6";
    };
    "nix-public/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.jar";
      sha256 = "F81D7144F0CE1B8123335B72BA39003C4BE2870767ACA15DD0888BA3DAB65E98";
    };
    "nix-public/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.pom";
      sha256 = "B8572EF09B9778332370F6C6F3D89029D371CA3245271664162349FFBBEAA0B1";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-javadoc.jar";
      sha256 = "0B9578DBE2B2F35DD438546E3A6C1314950FDDC3232220FE250E498148D8E4AE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-sources.jar";
      sha256 = "1631F768D506FAA08E4C4769F5B07DD37BDD92720B44C0DC223F3EDE801F5734";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar";
      sha256 = "8F3DC6091DB688464AD8B1EE6C7343D7AA5940D474EE8B90406C71E45DD74FC0";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom";
      sha256 = "2255FD693D69DDD6954B6B7F614AF4ED93EB6AA6A27EBFE01E65DB194DAECAA9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar";
      sha256 = "9940E7CF343DFBDDDEB60B538E559496B836430400575405FE46C7176B95C78E";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar";
      sha256 = "11482BCB49B2E47BAEE89C3B1AE10C6A40B89E2FBB0DA2A423E062F444E13492";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar";
      sha256 = "321FB55685635C931EBA4BC0D7668349DA3F2C09AEE2DE93A70566066FF25C28";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom";
      sha256 = "22E81EE9D5349BA0E897ADB5C7FCEC25656C9E0B7B86C3E93E9A7AF360481C0D";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1-javadoc.jar";
      sha256 = "A4644B9F06986C8619CEE3216D7383D974F5C1100364C7776357F3533DC4A4E9";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1-sources.jar";
      sha256 = "DF915BF043F037C8FF5A6F0A88DD8CFC3A927212AE93A61D18049F0A54477E06";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.jar";
      sha256 = "D8A2B9D6D78C7457A40E394DC0C4FA6D6244ACF0D156BBBCB311A9D497B85EEC";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.pom";
      sha256 = "808B17C95D7E260A375615992CD1FCE7D759B6FDEF5E64D7B70E3942AE014261";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-javadoc.jar";
      sha256 = "5DE7917046C0DA3BA5766563B14B0B75EE23E87FDC2426771EF2885CADA9912B";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-sources.jar";
      sha256 = "7B4DC73DC3CB46AC9AC948A0C231CCD989BED6CEFB137C302A8EC8D6811E8148";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.jar";
      sha256 = "EA70FE0E550E24D23FC52A18963B2BE9C3B24283F4CB18B98327EB72746567CC";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.pom";
      sha256 = "9BB07CA874C7EC1A945E32A02D4308BD3D655A3ABD7A23CEB1F109C795339CE0";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-javadoc.jar";
      sha256 = "F9412EED83A4FB68F6839B54DCA545CBA07F127D456060B81EC76C7781300E48";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-sources.jar";
      sha256 = "2B84D948A67FA7F5C4C6CCA9C4AEFB83BC3BED76DB69989D1E2D0977532942C2";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.jar";
      sha256 = "7427D7EE5771E8C36C1DB5A09368FA3078F6ECEB77D7C797A322A088C5DDDB76";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.pom";
      sha256 = "1C5DCB05333F33C0674D039E348789A7525208ED4F8316A9199D255B824E038A";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-javadoc.jar";
      sha256 = "F7D299D01D190E239144A4C74D4EB33FA92C057B1D8F161FB7D75FD07E6426C4";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-sources.jar";
      sha256 = "5C676791217D9B48560496556B8965CCEABCBFDBB65BBEBDC52E99C0A3847735";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar";
      sha256 = "4D6405395C4599CE04CEA08BA082339E3E42135DE9AAE2923C9F5367E957315A";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.pom";
      sha256 = "CBFFFF8D495FFD66C1234469A2965F54A82FA58E6816EE0E5803E896CAC167C3";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-javadoc.jar";
      sha256 = "58CAA3EAE25920DFBA5FACBC0C449CBA01994982E96C992D080E0EE52F886AE2";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-sources.jar";
      sha256 = "4589D87CC22D0C370BD1708F328D31B98B4BAED38D1BAA8F595CA1BD5CA528E6";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.jar";
      sha256 = "C342EAB071B314D125B3AC00C3CE3B2287A478A64639AD210BE7FFC25835CE01";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.pom";
      sha256 = "EBF9B8ED3CCEF14B5D8904401C60D92E32B276C12CD0A152C671D184EFF28C97";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-javadoc.jar";
      sha256 = "9DD282695276A298DB294BE7C50663D750598DDF1F4C07B5B54E9D48DEE5445E";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-sources.jar";
      sha256 = "5EDF42C3DE05267BD79F413EA22CDB7C53B99719395387E4A988D087DE7B2212";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.jar";
      sha256 = "502C7F02FF1F99E7B125537A456601AAF31A24C997BBC265C24CA6DD3B7442BD";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.pom";
      sha256 = "1DBE0A87AE1489F9419A416F96DB4D3EE12B351CB58A09B8EB9C8E8447AE5A92";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-javadoc.jar";
      sha256 = "D3421C2A8450FCF646ECCEADE47B5D8F3280BE3A68D8178C11DC2F8BF2EE0375";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-sources.jar";
      sha256 = "A41F082F90CFE665755AEDB007F0F82BA8499D4EF0F58253AFDD79DD3A1C63BA";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.jar";
      sha256 = "ADB18E5F79A028F2B33506CCC6A4B24500DD985628B05308A7AF5ACBD1EE2CD7";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.pom";
      sha256 = "7DE9EC96F383FCC18C17A0E7513071EC929F21D1CFD81EFC028BB307CC7E9BB7";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3-javadoc.jar";
      sha256 = "E97F63A7F7042A20EA41030E5AC6956C60F33638F762634C0EF2ED1DCE4B8514";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3-sources.jar";
      sha256 = "EB82A1E68E67DF4FE357EA65FB230F3A2CF1A225020888489313BBE0D4ECACEE";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.jar";
      sha256 = "245AD1BAAB6661AEE70C137C5E1625771C2624596B349B305801D94618673292";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.pom";
      sha256 = "0B33F9E2D47FA7F829E7E1646BD3EE3D4A4FF4E8A61775F345449E1D5757EB46";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5-javadoc.jar";
      sha256 = "80C7CBB0BD10830E0A4281FB0ACB00355BEB461420203F7D379B14494E1AEDFD";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5-sources.jar";
      sha256 = "0455EAECAA2B8CE0BE537120C2CCD407C4606CBE53E63CB6A7FC8B31B5B65461";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5.jar";
      sha256 = "57E25B4FD969B1758FE042595112C874DFEA99DCA5CC48EEBE07AC38772A0C41";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5.pom";
      sha256 = "A7DE321F1250ECC528CD8E1249541EAD9C423E93E2D04F682C3029EFDA3198DE";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5-javadoc.jar";
      sha256 = "057D6F58CD601EF10C678D653CA5E734BAA1CB809325CBC04914D02C563E784E";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5-sources.jar";
      sha256 = "22081EE83810098ADC9AF4D84D05DD5891D7C0E15F9095BCDAF4AC7A228B92DF";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5.jar";
      sha256 = "B416B5BCEF6720DA469A8D8A5726E457FC2D1CD5D316E1BC283AA75A2AE005E5";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5.pom";
      sha256 = "D573B5D2F00A26F0B6B7E8BE0E52B11EFCF76F0BCEC1BB2AC48CB0DC164E02AB";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar";
      sha256 = "8DC4B97B764D6C5B732479936C6CA28DFE9480C8A9B67E4B26CF95C8C64D77BD";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar";
      sha256 = "C4BC93180A4F0ACEEC3B057A2514ABE04A79F06C174BBED910A2AFB227B79366";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar";
      sha256 = "FB82F52621D9DDAFB135DFF968A75B5BC08C40BA4BE77B5AB8DEA8711A032D72";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar";
      sha256 = "18C4A0095D5C1DA6B817592E767BB23D29DD2F560AD74DF75FF3961DBDE25B79";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom";
      sha256 = "7CD9D7A0B5D93DFD461A148891B43509CF403A9C7F9FB49060D3554DF1C81E1E";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom";
      sha256 = "18F5C52120DB036E88D6136F8839C832D074BDDA95C756C6F429249D2DB54AC6";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
  };
}
