# This file was automatically generated by Sbtix. Do not edit manually.
{
  "versioning" = [{
      "scalaVersion" = "2.12.7";
      "sbtVersion" = "1.2.7";
    }];
  "repos" = {
    "nix-public" = "";
  };
  "artifacts" = {
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.11.0/jackson-annotations-2.11.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.11.0/jackson-annotations-2.11.0-javadoc.jar";
      sha256 = "8C34822AFB4D7B617429D5ADB187F477748BDE05E65605BC071EDA834AFA6274";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.11.0/jackson-annotations-2.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.11.0/jackson-annotations-2.11.0-sources.jar";
      sha256 = "F14DB3BC503A945B6A9CAF078B341237EB5A278D65FFB11681E9B8F040A3324F";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.11.0/jackson-annotations-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.11.0/jackson-annotations-2.11.0.jar";
      sha256 = "B3B1FCA6CB6469D4EA06635D964AAEA91F86CC22FE42A9757C8A315148589E8E";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-annotations/2.11.0/jackson-annotations-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-annotations/2.11.0/jackson-annotations-2.11.0.pom";
      sha256 = "C050143721729E8A9D062FB4D6559A43DACA41ABB19DC62824AFAF2E835AF1A1";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.11.0/jackson-core-2.11.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.11.0/jackson-core-2.11.0-javadoc.jar";
      sha256 = "F2F5F99D44CB0E4CD795E4F5B56D7DB8FADC7711F5E554344B14FBB98B698314";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.11.0/jackson-core-2.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.11.0/jackson-core-2.11.0-sources.jar";
      sha256 = "EFD98F7F308F2BD060DCDEDC336094EFE23C37C95A24247BDAB92ABCEEECBCE7";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.11.0/jackson-core-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.11.0/jackson-core-2.11.0.jar";
      sha256 = "B504D81351FB088F1E1BBEF6A701FAA88D2CFC4350483AEAA19384C39A8133FD";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-core/2.11.0/jackson-core-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.11.0/jackson-core-2.11.0.pom";
      sha256 = "46610691A52641FF31885241AD267F6C1E006F9CB37270AA21CB35A8F875EBC2";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.11.0/jackson-databind-2.11.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.11.0/jackson-databind-2.11.0-javadoc.jar";
      sha256 = "95BC98AE03AA4656512DED720082AD345343559FD8FFAF40A03C13C889B0AFBE";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.11.0/jackson-databind-2.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.11.0/jackson-databind-2.11.0-sources.jar";
      sha256 = "E40715A657019F7622B050A8283D3EECC4F8B7F2123A20AF9834EF919FE7C83E";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.11.0/jackson-databind-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.11.0/jackson-databind-2.11.0.jar";
      sha256 = "54E72B9FA38FC37986AE7F6FC30EF704EEC8010206BCD4D63546DCCBBB47F4D1";
    };
    "nix-public/com/fasterxml/jackson/core/jackson-databind/2.11.0/jackson-databind-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-databind/2.11.0/jackson-databind-2.11.0.pom";
      sha256 = "7F17BB8BFF0A5E8B80CCFAB131B4ABD15F638766F8FFE685FA1DBE521F62A02B";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.0/jackson-dataformat-xml-2.11.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.0/jackson-dataformat-xml-2.11.0-javadoc.jar";
      sha256 = "28AC31B87177A2A6C136C717045401AE7D70F2882466A17B81DDF11FD8259715";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.0/jackson-dataformat-xml-2.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.0/jackson-dataformat-xml-2.11.0-sources.jar";
      sha256 = "F9B863BE61D0C6F54245D00B71A306D8EF8CCA849CC093D05094FD5DD7094486";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.0/jackson-dataformat-xml-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.0/jackson-dataformat-xml-2.11.0.jar";
      sha256 = "D3B3B8556B5E57066D19F646320A9A291C1F59A80AB8A03DA9C019409BCC8734";
    };
    "nix-public/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.0/jackson-dataformat-xml-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.11.0/jackson-dataformat-xml-2.11.0.pom";
      sha256 = "AD880310057CB7109C7301CE200C122E72B69D85CCF2849321F0FEECA35C1A50";
    };
    "nix-public/com/fasterxml/jackson/jackson-base/2.11.0/jackson-base-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-base/2.11.0/jackson-base-2.11.0.pom";
      sha256 = "A4306F903647322BBBA0054937B89A0C6424756A7FA029C85F2CBD756FDE80CA";
    };
    "nix-public/com/fasterxml/jackson/jackson-bom/2.11.0/jackson-bom-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.11.0/jackson-bom-2.11.0.pom";
      sha256 = "5C90FB02E96E8BAB2F32EB9492DD350968E294558431AC5A9A10AFA6726133CB";
    };
    "nix-public/com/fasterxml/jackson/jackson-parent/2.11/jackson-parent-2.11.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-parent/2.11/jackson-parent-2.11.pom";
      sha256 = "C1B0A13D8CFE63B40B0FAE8458B99463169ED0C60F7FC963EF3F05257150CBE8";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.0/jackson-module-jaxb-annotations-2.11.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.0/jackson-module-jaxb-annotations-2.11.0-javadoc.jar";
      sha256 = "FFD66CE82A6B80F4C86F8F9C84220AFA17DF8CB02B6D56387D4A40A65D9F0252";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.0/jackson-module-jaxb-annotations-2.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.0/jackson-module-jaxb-annotations-2.11.0-sources.jar";
      sha256 = "63396903E243767C3AEC162CB899A9CED489D47BDEA11E1D0F40CDF55B7C7459";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.0/jackson-module-jaxb-annotations-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.0/jackson-module-jaxb-annotations-2.11.0.jar";
      sha256 = "73E0447FA708BEE956A6E53911C017B95070EFB11DD88FF2987643D399ADF170";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.0/jackson-module-jaxb-annotations-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-jaxb-annotations/2.11.0/jackson-module-jaxb-annotations-2.11.0.pom";
      sha256 = "4333B8153A840ECF8557FF3C05B055E34E7EA8B90BE2F8C0CD2E71E83337A603";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-paranamer/2.11.0/jackson-module-paranamer-2.11.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-paranamer/2.11.0/jackson-module-paranamer-2.11.0-javadoc.jar";
      sha256 = "290EB9FAF6D017AC3DB46618DD8171CDCA1B5D4CCE38E38DD5A59D4704CB4FB4";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-paranamer/2.11.0/jackson-module-paranamer-2.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-paranamer/2.11.0/jackson-module-paranamer-2.11.0-sources.jar";
      sha256 = "2B524DD17252B3732D1CF58309F55B460362B36927AB9B1E239C7035AAAA1574";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-paranamer/2.11.0/jackson-module-paranamer-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-paranamer/2.11.0/jackson-module-paranamer-2.11.0.jar";
      sha256 = "83CCAE0A723936617F7146EADA771AF81FA7E6A9B05FDB9213E52A548D74FD00";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-paranamer/2.11.0/jackson-module-paranamer-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-paranamer/2.11.0/jackson-module-paranamer-2.11.0.pom";
      sha256 = "0ED20AED49AC864EBDA2D57BAC7C99F55FEF5714E9D78E144209EC7E423DF84E";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.11.0/jackson-module-scala_2.12-2.11.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.11.0/jackson-module-scala_2.12-2.11.0-javadoc.jar";
      sha256 = "872FCAF35CC033F44CFD1D5F9CE5C63D425DDD15FCA38476B602E578E3664C5F";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.11.0/jackson-module-scala_2.12-2.11.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.11.0/jackson-module-scala_2.12-2.11.0-sources.jar";
      sha256 = "FE5CB5B77F389CB3226E5A514981D12E13B8BB455A3E64E7E2A08B652ECF5B30";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.11.0/jackson-module-scala_2.12-2.11.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.11.0/jackson-module-scala_2.12-2.11.0.jar";
      sha256 = "80BD7B501B1E3821C49F6FA885CAB255B75DA4C7C276E77D1DA2E6465EF60C60";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.11.0/jackson-module-scala_2.12-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-module-scala_2.12/2.11.0/jackson-module-scala_2.12-2.11.0.pom";
      sha256 = "4B26D4D173E61596B286E1A820AAAEF948A87B127639148EC2A041AE0DBF0892";
    };
    "nix-public/com/fasterxml/jackson/module/jackson-modules-base/2.11.0/jackson-modules-base-2.11.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/jackson/module/jackson-modules-base/2.11.0/jackson-modules-base-2.11.0.pom";
      sha256 = "81E619B65269065D97AA03AB328B4FB3EFC803735ED76EC3C981C0749FF5CE95";
    };
    "nix-public/com/fasterxml/oss-parent/35/oss-parent-35.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/35/oss-parent-35.pom";
      sha256 = "AFC05ED21064EACAC8DE3002530CB192208BD114EB248417DAD1886CBF54056E";
    };
    "nix-public/com/fasterxml/oss-parent/38/oss-parent-38.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/oss-parent/38/oss-parent-38.pom";
      sha256 = "C83F8F45DFDCA8D0B6B3661C60B3F84780F671B12E06F91AD5D1C1A1D1F966E8";
    };
    "nix-public/com/fasterxml/woodstox/woodstox-core/6.2.0/woodstox-core-6.2.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/woodstox/woodstox-core/6.2.0/woodstox-core-6.2.0-javadoc.jar";
      sha256 = "100A40A8C89D18447B13C5A7BDF62DAA116739D891F509C93A0E6FF5758D5D56";
    };
    "nix-public/com/fasterxml/woodstox/woodstox-core/6.2.0/woodstox-core-6.2.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/woodstox/woodstox-core/6.2.0/woodstox-core-6.2.0-sources.jar";
      sha256 = "72FC06C6AB8FF8ECD3A0C139308C25B515773CAFC883D942CF4586F0A065D7D7";
    };
    "nix-public/com/fasterxml/woodstox/woodstox-core/6.2.0/woodstox-core-6.2.0.jar" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/woodstox/woodstox-core/6.2.0/woodstox-core-6.2.0.jar";
      sha256 = "078F8F918344F2C195917339060DEDFB758CEC1E014F96C6082FE0BDB6037AF5";
    };
    "nix-public/com/fasterxml/woodstox/woodstox-core/6.2.0/woodstox-core-6.2.0.pom" = {
      url = "https://repo1.maven.org/maven2/com/fasterxml/woodstox/woodstox-core/6.2.0/woodstox-core-6.2.0.pom";
      sha256 = "1C2B1A5AAF1B9162102250C261D6FCE32136AB525A09A6B86E5404417E5237A8";
    };
    "nix-public/com/github/virtuald/curvesapi/1.06/curvesapi-1.06-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/virtuald/curvesapi/1.06/curvesapi-1.06-javadoc.jar";
      sha256 = "61F3DFDBEDC0C16BDCAD541A897E1DDB7776B29F794C47A07A9355FB42CEC626";
    };
    "nix-public/com/github/virtuald/curvesapi/1.06/curvesapi-1.06-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/virtuald/curvesapi/1.06/curvesapi-1.06-sources.jar";
      sha256 = "680A9F14F9C744B986A50935251799E2DA8613B6FFAB91E3DF6894F7B90E9C24";
    };
    "nix-public/com/github/virtuald/curvesapi/1.06/curvesapi-1.06.jar" = {
      url = "https://repo1.maven.org/maven2/com/github/virtuald/curvesapi/1.06/curvesapi-1.06.jar";
      sha256 = "38BB45C99E6153260C19B97B99B6A7370A067DE63344DE6D1EA11922ACAED86B";
    };
    "nix-public/com/github/virtuald/curvesapi/1.06/curvesapi-1.06.pom" = {
      url = "https://repo1.maven.org/maven2/com/github/virtuald/curvesapi/1.06/curvesapi-1.06.pom";
      sha256 = "C3EA7B0DF569F61945BF814906AB595A86EB20B9213C39AAAE86C52C7B247D7E";
    };
    "nix-public/com/google/code/gson/gson-parent/2.8.5/gson-parent-2.8.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/google/code/gson/gson-parent/2.8.5/gson-parent-2.8.5.pom";
      sha256 = "8F1FEC72B91A71EA39EC39F5F778C4D1124B6B097C6D55B3A50B554A52237B27";
    };
    "nix-public/com/google/code/gson/gson/2.8.5/gson-2.8.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5-javadoc.jar";
      sha256 = "C32E90CCB6CADC8C4162BF807A4F1DF630A7C907186337DCD06CF982EDE71284";
    };
    "nix-public/com/google/code/gson/gson/2.8.5/gson-2.8.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5-sources.jar";
      sha256 = "512B4BF6927F4864ACC419B8C5109C23361C30ED1F5798170248D33040DE068E";
    };
    "nix-public/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar" = {
      url = "https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.jar";
      sha256 = "233A0149FC365C9F6EDBD683CFE266B19BDC773BE98EABDAF6B3C924B48E7D81";
    };
    "nix-public/com/google/code/gson/gson/2.8.5/gson-2.8.5.pom" = {
      url = "https://repo1.maven.org/maven2/com/google/code/gson/gson/2.8.5/gson-2.8.5.pom";
      sha256 = "B8308557A7FCCC92D9FE7C8CD0599258B361285D2ECDE7689EDA98843255A092";
    };
    "nix-public/com/novocode/junit-interface/0.11/junit-interface-0.11-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11-javadoc.jar";
      sha256 = "595FFA648A68D48B31D11A49C4620271934CF76C6F20996047EC7031E16F27B2";
    };
    "nix-public/com/novocode/junit-interface/0.11/junit-interface-0.11-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11-sources.jar";
      sha256 = "246E6CF2552F906EF9F366D991700B4EA99963E93013470D8DB6FDF19A5021DE";
    };
    "nix-public/com/novocode/junit-interface/0.11/junit-interface-0.11.jar" = {
      url = "https://repo1.maven.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11.jar";
      sha256 = "29E923226A0D10E9142BBD81073EF52F601277001FCF9014389BF0AF3DC33DC3";
    };
    "nix-public/com/novocode/junit-interface/0.11/junit-interface-0.11.pom" = {
      url = "https://repo1.maven.org/maven2/com/novocode/junit-interface/0.11/junit-interface-0.11.pom";
      sha256 = "8188F536152ED6472345F5E6104D2D38FFF9C327C5C4825B8E866249CB6F97E0";
    };
    "nix-public/com/sun/activation/all/1.2.1/all-1.2.1.pom" = {
      url = "https://repo1.maven.org/maven2/com/sun/activation/all/1.2.1/all-1.2.1.pom";
      sha256 = "360883BF64486ECEF161B8F282F6503536DD1A670D53A0A871C8FB20170E6795";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer-parent/2.8/paranamer-parent-2.8.pom" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer-parent/2.8/paranamer-parent-2.8.pom";
      sha256 = "F094F01C1B5BD2A28D27063291A6DC20EA99D8209C037C990264396BCC08F7CD";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8-javadoc.jar";
      sha256 = "1B2189513997272379EC8D0D77B9A64FC0B6AAC91C118718731BF5264C5FCD93";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8-sources.jar";
      sha256 = "8A4BFC21755C36CCDD70F96D7AB891D842D5AEBD6AFA1B74E0EFC6441E3DF39C";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.jar";
      sha256 = "688CB118A6021D819138E855208C956031688BE4B47A24BB615BECC63ACEDF07";
    };
    "nix-public/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.pom" = {
      url = "https://repo1.maven.org/maven2/com/thoughtworks/paranamer/paranamer/2.8/paranamer-2.8.pom";
      sha256 = "D5DB404DE0552D8DCE641621132DA55539D5125C3152BFEC4043A16526D93856";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19-javadoc.jar";
      sha256 = "E01EE501EA07690009422BDDAF607704E193CC0ECA89277C9E418C9ABC18A752";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19-sources.jar";
      sha256 = "5F4A9A2B8E8F258DE65C7B7BEEAF5814E7B946E2A82D947C2DE3EF9F15F55EA5";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19.jar";
      sha256 = "33B5EEF9DB3766A7E7A307457995FDE116967EAD482C88377B2466475D8F703B";
    };
    "nix-public/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-actor_2.12/2.5.19/akka-actor_2.12-2.5.19.pom";
      sha256 = "E901E8A1C7609AD05F99E90234A132BB8EBF095DE991DB29DABD11B0D59CE88A";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19-javadoc.jar";
      sha256 = "07F637E2F1F5E39DE68E30AB56E132A6EF5F71D1D2E9DC0A176AA2C380C48574";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19-sources.jar";
      sha256 = "9C3F15703C2179442C876B50578711607AFDC05715D983ACCA36B8939C534880";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19.jar";
      sha256 = "2676E9D6E9F3B712A49DB3DF0A8C3B0DB3DC89C8846295D12C3CF274C8CDE6DD";
    };
    "nix-public/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/akka/akka-slf4j_2.12/2.5.19/akka-slf4j_2.12-2.5.19.pom";
      sha256 = "DA1D7A410E7491511C563BA4AD032C9ACA2A64A598C605AB7DA730D4A91956E7";
    };
    "nix-public/com/typesafe/config/1.3.3/config-1.3.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.3/config-1.3.3-javadoc.jar";
      sha256 = "131B1CFF95E3F64FD6DF84695CA0D3C2FC85A9C08CDE9B9D86DB3EDC9E1561ED";
    };
    "nix-public/com/typesafe/config/1.3.3/config-1.3.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.3/config-1.3.3-sources.jar";
      sha256 = "FCD7C3070417C776B313CC559665C035D74E3A2B40A89BBB0E9BFF6E567C9CC8";
    };
    "nix-public/com/typesafe/config/1.3.3/config-1.3.3.jar" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.3/config-1.3.3.jar";
      sha256 = "B5F1D6071F1548D05BE82F59F9039C7D37A1787BD8E3C677E31EE275AF4A4621";
    };
    "nix-public/com/typesafe/config/1.3.3/config-1.3.3.pom" = {
      url = "https://repo1.maven.org/maven2/com/typesafe/config/1.3.3/config-1.3.3.pom";
      sha256 = "2C268553F771EB572C41AD89EE043DC288B4A700FA51B6263B04EFF92867781C";
    };
    "nix-public/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2-javadoc.jar";
      sha256 = "32CC55C7518702C02737904CDDA6A6740CD0540EB6B6986246679F14D1DF7473";
    };
    "nix-public/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2-sources.jar";
      sha256 = "37F98063027DD2B1434BE7C6444D5506F67AEF3F7579C6EDDEB01D4B42187EC5";
    };
    "nix-public/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2.jar" = {
      url = "https://repo1.maven.org/maven2/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2.jar";
      sha256 = "91E6B318C901A0F2DD1F6CE781D62474435AE627D22FBAC9B21BBC39FFD804B6";
    };
    "nix-public/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2.pom" = {
      url = "https://repo1.maven.org/maven2/com/zaxxer/SparseBitSet/1.2/SparseBitSet-1.2.pom";
      sha256 = "EFEB17C9FDE5289D079FE23635E566AB801940CC2313C407DB9DAD7BD645329B";
    };
    "nix-public/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4-javadoc.jar";
      sha256 = "50C36166E4127C439B2764B686E0DAB7BB11CC502411001C6561DEECD5136174";
    };
    "nix-public/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4-sources.jar";
      sha256 = "E9D60EF0F35EA1FDE6F19D57679EA8A82306CCFA07CDE23C7DE1FAC986D5A4E0";
    };
    "nix-public/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4.jar" = {
      url = "https://repo1.maven.org/maven2/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4.jar";
      sha256 = "1E56122FF6DBA06F58DC97829FD1CBD2C5E82C99E0E1BC66214BFC3159838DD9";
    };
    "nix-public/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4.pom" = {
      url = "https://repo1.maven.org/maven2/com/zaxxer/nuprocess/1.2.4/nuprocess-1.2.4.pom";
      sha256 = "A85AF3D78CDB98F3DE3EFEF47717881B5AEC306882B62B15A845089FBCB5ACEC";
    };
    "nix-public/commons-codec/commons-codec/1.10/commons-codec-1.10-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10-javadoc.jar";
      sha256 = "F6AF892A0D6428336AF6764ADAA9BAC90155A3A23CFBEE3BA2D6A84E7B19A6A3";
    };
    "nix-public/commons-codec/commons-codec/1.10/commons-codec-1.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10-sources.jar";
      sha256 = "DFAE68268CE86F1A18FC45B99317C13D6C9D252F001D37961E79A51076808986";
    };
    "nix-public/commons-codec/commons-codec/1.10/commons-codec-1.10-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10-tests.jar";
      sha256 = "CFF493D703E0705C6150CEB9F2D47B34488E54B7359C400B05E254015EE7BF64";
    };
    "nix-public/commons-codec/commons-codec/1.10/commons-codec-1.10.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.jar";
      sha256 = "4241DFA94E711D435F29A4604A3E2DE5C4AA3C165E23BD066BE6FC1FC4309569";
    };
    "nix-public/commons-codec/commons-codec/1.10/commons-codec-1.10.pom" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.10/commons-codec-1.10.pom";
      sha256 = "BDB8DB7012D112A6E3EA8FDB7C510B300D99EFF0819D27DDDBA9C43397EA4CFB";
    };
    "nix-public/commons-codec/commons-codec/1.13/commons-codec-1.13-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.13/commons-codec-1.13-javadoc.jar";
      sha256 = "3492A2DFF88CE739F5BCCD0D5A64917B9B2EBE697A4EBDF5043F8C6BAC5CF2C0";
    };
    "nix-public/commons-codec/commons-codec/1.13/commons-codec-1.13-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.13/commons-codec-1.13-sources.jar";
      sha256 = "09A72795A920C1A9C0209CFB8395F8D97089832D249CBA8C0938A3423B3ED1D1";
    };
    "nix-public/commons-codec/commons-codec/1.13/commons-codec-1.13-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.13/commons-codec-1.13-tests.jar";
      sha256 = "E31DB961A7F54C80213D71556C86F64DD7476DA5FA1EE479228B852210EA0E1C";
    };
    "nix-public/commons-codec/commons-codec/1.13/commons-codec-1.13.jar" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.13/commons-codec-1.13.jar";
      sha256 = "61F7A3079E92B9FDD605238D0295AF5FD11AC411A0A0AF48DEACE1F6C5FFA072";
    };
    "nix-public/commons-codec/commons-codec/1.13/commons-codec-1.13.pom" = {
      url = "https://repo1.maven.org/maven2/commons-codec/commons-codec/1.13/commons-codec-1.13.pom";
      sha256 = "C2E2A902D38230CF3031D0B434D5DE2614FA0FF26D384B6D282AAB56C7D3FC69";
    };
    "nix-public/commons-io/commons-io/2.6/commons-io-2.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.6/commons-io-2.6-javadoc.jar";
      sha256 = "1D31FCF399C143901186D4B46216DB982A2B88C677109887B85254EBE1D6A702";
    };
    "nix-public/commons-io/commons-io/2.6/commons-io-2.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.6/commons-io-2.6-sources.jar";
      sha256 = "71BC251EB4BD011B60B5CE6ADC8F473DE10E4851207A40C14434604B288B31BF";
    };
    "nix-public/commons-io/commons-io/2.6/commons-io-2.6-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.6/commons-io-2.6-tests.jar";
      sha256 = "C3C50EBBCB2C528F71C0E4C2310A90D5FBD4BE26B3309E46E14A3BC685524D4A";
    };
    "nix-public/commons-io/commons-io/2.6/commons-io-2.6.jar" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.6/commons-io-2.6.jar";
      sha256 = "F877D304660AC2A142F3865BADFC971DEC7ED73C747C7F8D5D2F5139CA736513";
    };
    "nix-public/commons-io/commons-io/2.6/commons-io-2.6.pom" = {
      url = "https://repo1.maven.org/maven2/commons-io/commons-io/2.6/commons-io-2.6.pom";
      sha256 = "0C23863893A2291F5A7AFDBD8D15923B3948AFD87E563FA341CDCF6EAE338A60";
    };
    "nix-public/commons-logging/commons-logging/1.2/commons-logging-1.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2-javadoc.jar";
      sha256 = "BD93F2B39BF8F2800727EDA522239BE378F2A8AE7B13F1858F1A1215525FF60D";
    };
    "nix-public/commons-logging/commons-logging/1.2/commons-logging-1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2-sources.jar";
      sha256 = "44347ACFE5860461728E9CB33251E97345BE36F8A0DFD5C5130C172559455F41";
    };
    "nix-public/commons-logging/commons-logging/1.2/commons-logging-1.2-tests.jar" = {
      url = "https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2-tests.jar";
      sha256 = "C68AB601527EFAF7F399B7DC8918207D4638ADF8DB19444D13969B9EFD03092F";
    };
    "nix-public/commons-logging/commons-logging/1.2/commons-logging-1.2.jar" = {
      url = "https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.jar";
      sha256 = "DADDEA1EA0BE0F56978AB3006B8AC92834AFEEFBD9B7E4E6316FCA57DF0FA636";
    };
    "nix-public/commons-logging/commons-logging/1.2/commons-logging-1.2.pom" = {
      url = "https://repo1.maven.org/maven2/commons-logging/commons-logging/1.2/commons-logging-1.2.pom";
      sha256 = "C91AB5AA570D86F6FD07CC158EC6BC2C50080402972EE9179FE24100739FBB20";
    };
    "nix-public/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1-javadoc.jar";
      sha256 = "BC8CF4DE021294AB41D55442C4439C7F3F67BFC9C7B1C70B839E4FF668F818E4";
    };
    "nix-public/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1-sources.jar";
      sha256 = "E9638B764202C0DEF1B4D54BD37A984C681B2ED46A548AE94EF3F7E4A4B58A31";
    };
    "nix-public/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar" = {
      url = "https://repo1.maven.org/maven2/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.jar";
      sha256 = "8B0A0F52FA8B05C5431921A063ED866EFAA41DADF2E3A7EE3E1961F2B0D9645B";
    };
    "nix-public/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.pom" = {
      url = "https://repo1.maven.org/maven2/jakarta/activation/jakarta.activation-api/1.2.1/jakarta.activation-api-1.2.1.pom";
      sha256 = "42585CB07DDA7F23AA04EB5E0940061944A246A67AD3D16942FBE569FF03CD31";
    };
    "nix-public/jakarta/xml/bind/jakarta.xml.bind-api-parent/2.3.2/jakarta.xml.bind-api-parent-2.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api-parent/2.3.2/jakarta.xml.bind-api-parent-2.3.2.pom";
      sha256 = "15A55B7D537C9F9970AEAD28D2AF97C059F65FF6102F76BBD29F1247DD8A6DFB";
    };
    "nix-public/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2-javadoc.jar";
      sha256 = "13A144F22AF3E84760A6CF2EB4D1ED4028BF57A5A3267431F0E9FC2E15960AD5";
    };
    "nix-public/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2-sources.jar";
      sha256 = "61CEB3ED35ECF99F1803EAC9C4B8F12103C7531952BEAE38BA53CC727F405532";
    };
    "nix-public/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar" = {
      url = "https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.jar";
      sha256 = "69156304079BDEED9FC0AE3B39389F19B3CC4BA4443BC80508995394EAD742EA";
    };
    "nix-public/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.pom" = {
      url = "https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/2.3.2/jakarta.xml.bind-api-2.3.2.pom";
      sha256 = "B537B388DBAB4CC0690B9D2FB0C74124D672531734567ACF6E53130EAB131AD6";
    };
    "nix-public/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0-javadoc.jar";
      sha256 = "B753810B1DE5289FAF8C7485A193635957EE05B864D25AE64B6AD39AB4AED80C";
    };
    "nix-public/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0-sources.jar";
      sha256 = "5C6D640F01E8E7FFDBA21B2B75C0F64F0C30FD1FC3372123750C034CB363012A";
    };
    "nix-public/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.jar";
      sha256 = "AF456B2DD41C4E82CF54F3E743BC678973D9FE35BD4D3071FA05C7E5333B8482";
    };
    "nix-public/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.1.0/javax.servlet-api-3.1.0.pom";
      sha256 = "B31109E22EA3F2DF1AD7955432E718A35DEF50AE6C19698034AFA8A0CF9E9069";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-javadoc.jar";
      sha256 = "EBD162363C0A6CA9E52AF51D7377F78F559D3F2663DC896E0DBF3B16A0188972";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-sources.jar";
      sha256 = "319A840705E1E46ABE579DD3D079B508558791E0236BC78DA01911748E06AF93";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6-tests.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6-tests.jar";
      sha256 = "AE143A7DC135371F446A44775E8D5337D97151D5FEEC8CA8575F3A718DDF35F3";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.jar" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.jar";
      sha256 = "97D1ACAAC82409BE42E622D7A54D3AE9D08517E8AEFDEA3D2BA9791150C2F02D";
    };
    "nix-public/jline/jline/2.14.6/jline-2.14.6.pom" = {
      url = "https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom";
      sha256 = "1DF7B6F08DFB81A268D6B93B659A6A9E389C5D8C32BDF0754238BA6483A4E982";
    };
    "nix-public/junit/junit/4.11/junit-4.11-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11-javadoc.jar";
      sha256 = "5827E285721B8D79A811473FF942359A28E67AAE2D08AF19E1E83F0BA5ACA547";
    };
    "nix-public/junit/junit/4.11/junit-4.11-sources.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11-sources.jar";
      sha256 = "694F4694A51F67DADEA4D2045742D38FB4EFB92D82D42744B15E26CE653BCD3E";
    };
    "nix-public/junit/junit/4.11/junit-4.11.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.jar";
      sha256 = "90A8E1603EECA48E7E879F3AFBC9560715322985F39A274F6F6070B43F9D06FE";
    };
    "nix-public/junit/junit/4.11/junit-4.11.pom" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.11/junit-4.11.pom";
      sha256 = "18AD8B0AE9E65A9195D04E25427DFE8B58175ABCDAE875A5A406AEE38BDDFB26";
    };
    "nix-public/junit/junit/4.12/junit-4.12-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12-javadoc.jar";
      sha256 = "84354AA70F995A7FF3C96B144C49B7FE90A0C6E21F818FD23B17F75B17FD1CA9";
    };
    "nix-public/junit/junit/4.12/junit-4.12-sources.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12-sources.jar";
      sha256 = "9F43FEA92033AD82BCAD2AE44CEC5C82ABC9D6EE4B095CAB921D11EAD98BF2FF";
    };
    "nix-public/junit/junit/4.12/junit-4.12.jar" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.jar";
      sha256 = "59721F0805E223D84B90677887D9FF567DC534D7C502CA903C0C2B17F05C116A";
    };
    "nix-public/junit/junit/4.12/junit-4.12.pom" = {
      url = "https://repo1.maven.org/maven2/junit/junit/4.12/junit-4.12.pom";
      sha256 = "90F163F78E3FFB6F1C7AD97DE9E7EBA4EEA25807141B85D6D12BE67CA25449C4";
    };
    "nix-public/net/java/dev/jna/jna/4.5.1/jna-4.5.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.5.1/jna-4.5.1-javadoc.jar";
      sha256 = "FEDD5607C27509D784C74BAA9E88584EE689A768E031F13F1497FFA83E0DE497";
    };
    "nix-public/net/java/dev/jna/jna/4.5.1/jna-4.5.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.5.1/jna-4.5.1-sources.jar";
      sha256 = "74145556F7B10BE10303B76E9BFB12A7D0D43934C60788ED006A7A8AED5517F4";
    };
    "nix-public/net/java/dev/jna/jna/4.5.1/jna-4.5.1.jar" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.5.1/jna-4.5.1.jar";
      sha256 = "FBC9DE96A0CC193A125B4008DBC348E9ED54E5E13FC67B8ED40E645D303CC51B";
    };
    "nix-public/net/java/dev/jna/jna/4.5.1/jna-4.5.1.pom" = {
      url = "https://repo1.maven.org/maven2/net/java/dev/jna/jna/4.5.1/jna-4.5.1.pom";
      sha256 = "A2BAE04BB469E14213CE6C94BE413684646E00965ADA85EC03563801BF0C2408";
    };
    "nix-public/net/java/jvnet-parent/3/jvnet-parent-3.pom" = {
      url = "https://repo1.maven.org/maven2/net/java/jvnet-parent/3/jvnet-parent-3.pom";
      sha256 = "30F5789EFA39DDBF96095AADA3FC1260C4561FAF2F714686717CB2DC5049475A";
    };
    "nix-public/org/apache/apache/13/apache-13.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/13/apache-13.pom";
      sha256 = "FF513DB0361FD41237BEF4784968BC15AAE478D4EC0A9496F811072CCAF3841D";
    };
    "nix-public/org/apache/apache/15/apache-15.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/15/apache-15.pom";
      sha256 = "36C2F2F979AC67B450C0CB480E4E9BAF6B40F3A681F22BA9692287D1139AD494";
    };
    "nix-public/org/apache/apache/16/apache-16.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/16/apache-16.pom";
      sha256 = "9F85FF2FD7D6CB3097AA47FB419EE7F0EBE869109F98ABA9F4ECA3F49E74A40E";
    };
    "nix-public/org/apache/apache/17/apache-17.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/17/apache-17.pom";
      sha256 = "398044B74B5A719326BE218AE08124E5E2F3318AB5D78FE199D504EFC2E0D43F";
    };
    "nix-public/org/apache/apache/18/apache-18.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/18/apache-18.pom";
      sha256 = "7831307285FD475BBC36B20AE38E7882F11C3153B1D5930F852D44EDA8F33C17";
    };
    "nix-public/org/apache/apache/21/apache-21.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/apache/21/apache-21.pom";
      sha256 = "AF10C108DA014F17CAFAC7B52B2B4B5A3A1C18265FA2AF97A325D9143537B380";
    };
    "nix-public/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4-javadoc.jar";
      sha256 = "218D39C563B1CAABCF139A0348DD90E05F8D05A788A7C2EF94C11073AB06580F";
    };
    "nix-public/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4-sources.jar";
      sha256 = "93B4FF13EE810830A247DFA83BF5B73C401A591AF4C11F3EFB9B9DA581E70452";
    };
    "nix-public/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4-tests.jar";
      sha256 = "1822F4AF92BD1E21F8220736AB4CCE4C06E10A5817ED73A94B6AE5703A5CCD38";
    };
    "nix-public/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.jar";
      sha256 = "1DF8B9430B5C8ED143D7815E403E33EF5371B2400AADBE9BDA0883762E0846D1";
    };
    "nix-public/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-collections4/4.4/commons-collections4-4.4.pom";
      sha256 = "271BD673839AF46E73AFF957E2918D4BF96F5AC4F6C6CF4D5BE93FD1F1271C4D";
    };
    "nix-public/org/apache/commons/commons-compress/1.19/commons-compress-1.19-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.19/commons-compress-1.19-javadoc.jar";
      sha256 = "AFF72B1713B4C5227F18182FB927DFAF76C0B9DABDC8EA1C101E0D981490C250";
    };
    "nix-public/org/apache/commons/commons-compress/1.19/commons-compress-1.19-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.19/commons-compress-1.19-sources.jar";
      sha256 = "3952FB4E01EA5FC03AE25E0DAB2F3D5B4F71A71D3750C7F03DFFA6ABA8075757";
    };
    "nix-public/org/apache/commons/commons-compress/1.19/commons-compress-1.19-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.19/commons-compress-1.19-tests.jar";
      sha256 = "A92B92E2B4C7EA4167E50BAC4F55A3F03301164D0E52F33D0DB357DACF0166F6";
    };
    "nix-public/org/apache/commons/commons-compress/1.19/commons-compress-1.19.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.19/commons-compress-1.19.jar";
      sha256 = "FF2D59FAD74E867630FBC7DAAB14C432654712AC624DBEE468D220677B124DD5";
    };
    "nix-public/org/apache/commons/commons-compress/1.19/commons-compress-1.19.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-compress/1.19/commons-compress-1.19.pom";
      sha256 = "9D5A690D1DEA6A747E0DD8E74E64447167F395CB8F148010B8241334F58B525B";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-javadoc.jar";
      sha256 = "0C58DB4A8025C70D5CB3E068E0917144823211F041C60C60A99D65D4931506FB";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-sources.jar";
      sha256 = "D97341CE0A7554028DB3403E407BB51F4D902BF3287F64F709D7A8156EAF1910";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9-tests.jar";
      sha256 = "25A3DBC30E9DFF627F088ED61995DA3C2912E2173C79A45CE85B60CDF93B22D9";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.jar";
      sha256 = "DE2E1DCDCF3EF917A8CE858661A06726A9A944F28E33AD7F9E08BEA44DC3C230";
    };
    "nix-public/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-lang3/3.9/commons-lang3-3.9.pom";
      sha256 = "A4022429B98425B430181915721279A52F610F34648BDAC487D4CACBBE8DFEB5";
    };
    "nix-public/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1-javadoc.jar";
      sha256 = "10ED884E29CA17CB59D6940A49E6FFE72B87A59078C53F07C2A173ED325BCA34";
    };
    "nix-public/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1-sources.jar";
      sha256 = "E2FF85A3C360D56C51A7021614A194F3FBAF224054642AC535016F118322934D";
    };
    "nix-public/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1-tests.jar";
      sha256 = "DB86156018E7287FD3C62F256AAE1C61A6B36298F400E45D66E6DCEDC1AA122D";
    };
    "nix-public/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.jar";
      sha256 = "1E56D7B058D28B65ABD256B8458E3885B674C1D588FA43CD7D1CBB9C7EF2B308";
    };
    "nix-public/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-math3/3.6.1/commons-math3-3.6.1.pom";
      sha256 = "FAD72336EA7D7DD06DA103144E3740DB508FA4B17D9C54D7847737EDC24A7E60";
    };
    "nix-public/org/apache/commons/commons-parent/34/commons-parent-34.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/34/commons-parent-34.pom";
      sha256 = "3A2E69D06D641D1F3B293126DC9E2E4EA6563BF8C36C87E0AB6FA4292D04B79C";
    };
    "nix-public/org/apache/commons/commons-parent/35/commons-parent-35.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/35/commons-parent-35.pom";
      sha256 = "7098A1AB8336ECD4C9DC21CBBCAC869F82C66F64B8AC4F7988D41B4FCB44E49A";
    };
    "nix-public/org/apache/commons/commons-parent/39/commons-parent-39.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/39/commons-parent-39.pom";
      sha256 = "87CD27E1A02A5C3EB6D85059CE98696BB1B44C2B8B650F0567C86DF60FA61DA7";
    };
    "nix-public/org/apache/commons/commons-parent/42/commons-parent-42.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/42/commons-parent-42.pom";
      sha256 = "CD313494C670B483EC256972AF1698B330E598F807002354EB765479F604B09C";
    };
    "nix-public/org/apache/commons/commons-parent/48/commons-parent-48.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-parent/48/commons-parent-48.pom";
      sha256 = "1E1F7DE9370A7B7901F128F1DACD1422BE74E3F47F9558B0F79E04C0637CA0B4";
    };
    "nix-public/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0-javadoc.jar";
      sha256 = "72AFD2595880E8287DCA3EC6C23EB2878C334CE3E64C5EC920BEEBDFDBE707C0";
    };
    "nix-public/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0-sources.jar";
      sha256 = "66E9CCCF7458256C7663A244DEDDD1D3D43B2445EA82671CC314A50FFEFCA0AA";
    };
    "nix-public/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0-tests.jar";
      sha256 = "7F62D0BEAC1C820BE8F4B56440ED268458FD6DC17AE048901EEE5B98FE4B4044";
    };
    "nix-public/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0.jar";
      sha256 = "5EFA9FBB54A58B1A12205A5FAC565F6982ABFEB0FF45BDBC318748EF5FD3A3FF";
    };
    "nix-public/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/commons/commons-pool2/2.8.0/commons-pool2-2.8.0.pom";
      sha256 = "8171DDDAAF77917AE73655EEC864ED8E4382F7B9B49068247EBDCFC6B4249D34";
    };
    "nix-public/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4-sources.jar";
      sha256 = "86690E2A80DD1E5C77EE7E38EA8E9ABED093F8BE2A3D4C24BB9099764D5A4A4C";
    };
    "nix-public/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.jar";
      sha256 = "50E981A8E567A16EBDAD104605B156540A863459FA127B8BA647F310DFC83EF8";
    };
    "nix-public/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpasyncclient/4.1.4/httpasyncclient-4.1.4.pom";
      sha256 = "34F24EF986B89D51B80A090387AA3D0C824D40F087AE5CCFAD47FF3C262C2E47";
    };
    "nix-public/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6-javadoc.jar";
      sha256 = "FAAA3FF3E14214A7145483EF54E73B0D159270862BDD40A2007ACC091F5042C8";
    };
    "nix-public/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6-sources.jar";
      sha256 = "6A8076D9A98A5BE9F1A055011166F9055B0AEE2DE133699DB3CCF20377533E58";
    };
    "nix-public/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6-tests.jar";
      sha256 = "2C0A4D96200A940262B01141ED36150F0734E0931DD6187369168D8C8725D9DF";
    };
    "nix-public/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.jar";
      sha256 = "C03F813195E7A80E3608D0DDD8DA80B21696A4C92A6A2298865BF149071551C7";
    };
    "nix-public/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpclient/4.5.6/httpclient-4.5.6.pom";
      sha256 = "7EFC1241E73E7FBB268BFD33242D11EBD3CA07061D7D85F2962DC32A0F0B8855";
    };
    "nix-public/org/apache/httpcomponents/httpcomponents-asyncclient/4.1.4/httpcomponents-asyncclient-4.1.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-asyncclient/4.1.4/httpcomponents-asyncclient-4.1.4.pom";
      sha256 = "E965EB369AF1D8B5A68B7D4B7861D53A52616AE803E13162E8DF842261700180";
    };
    "nix-public/org/apache/httpcomponents/httpcomponents-client/4.5.6/httpcomponents-client-4.5.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-client/4.5.6/httpcomponents-client-4.5.6.pom";
      sha256 = "B042B41F2391EDB00D35F7F4E509AED2123648C1D246CE58D0F7B905C9FE1F73";
    };
    "nix-public/org/apache/httpcomponents/httpcomponents-core/4.4.10/httpcomponents-core-4.4.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-core/4.4.10/httpcomponents-core-4.4.10.pom";
      sha256 = "61E9427D4BE326C307A7F16BA828D1CB3B14713C9B04FC8BA992A58F376C3136";
    };
    "nix-public/org/apache/httpcomponents/httpcomponents-parent/10/httpcomponents-parent-10.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcomponents-parent/10/httpcomponents-parent-10.pom";
      sha256 = "CAAF967D94AFB21753F36082C6086206BD1F48825FF596932CCEBA72B65D39FA";
    };
    "nix-public/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10-javadoc.jar";
      sha256 = "EE5F5FB66FA83CDD0CA6FA9337B9059E23C91B02E80481506930F583BA8F1BFF";
    };
    "nix-public/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10-sources.jar";
      sha256 = "CF4E224F2C9CC2B8CFF6B34D6874DB9A26EF994DEF12828CC8362847738C28D5";
    };
    "nix-public/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.jar";
      sha256 = "DEBEE7E9572C02A16CE0CAA4F565A9ECEB1290D33CD7A1E3297087BD467DAFF4";
    };
    "nix-public/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore-nio/4.4.10/httpcore-nio-4.4.10.pom";
      sha256 = "A4C995B738D104B75CC8B1164DB600533156C047ECCB4C8EE5D927B21A17EC73";
    };
    "nix-public/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10-javadoc.jar";
      sha256 = "7A2ADC8ACF41F802A972B952EC83525914561CF186D156A6A3A1CA7135ACCC81";
    };
    "nix-public/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10-sources.jar";
      sha256 = "9C790A045566DA7CE0A53276816D09E08543CCB46BA99DB1CB8F5D3742DFAA1F";
    };
    "nix-public/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10-tests.jar";
      sha256 = "B4AD915D4A1341D70863345259646993920ED3ED781B6DB6140CF731E3CEFA61";
    };
    "nix-public/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.jar";
      sha256 = "78BA1096561957DB1B55200A159B648876430342D15D461277E62360DA19F6FD";
    };
    "nix-public/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.10/httpcore-4.4.10.pom";
      sha256 = "C5C12066DF2B3B88A89A2C8602B81EA9A61627E976E5129EEA1899EBBAEA392B";
    };
    "nix-public/org/apache/httpcomponents/project/7/project-7.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/httpcomponents/project/7/project-7.pom";
      sha256 = "3D6EBA428555A558DE046B5D76EACC1F5A54B4F5F20B84D636ED7AFF18AA48C3";
    };
    "nix-public/org/apache/poi/poi-ooxml-schemas/4.1.2/poi-ooxml-schemas-4.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml-schemas/4.1.2/poi-ooxml-schemas-4.1.2.jar";
      sha256 = "B4C579F34C377008EC16A5A784539B73776A1DCEDF15196F88A80F1B208D9BB2";
    };
    "nix-public/org/apache/poi/poi-ooxml-schemas/4.1.2/poi-ooxml-schemas-4.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml-schemas/4.1.2/poi-ooxml-schemas-4.1.2.pom";
      sha256 = "C0234EB007660E41A7774940280CDE8B7BF242255052DA01AAFEBA6D54B8A7D2";
    };
    "nix-public/org/apache/poi/poi-ooxml/4.1.2/poi-ooxml-4.1.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml/4.1.2/poi-ooxml-4.1.2-javadoc.jar";
      sha256 = "CCB02F4F3D74A4D0F8397FBAD91071F62D3394269537DF646E2144C99EE894E5";
    };
    "nix-public/org/apache/poi/poi-ooxml/4.1.2/poi-ooxml-4.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml/4.1.2/poi-ooxml-4.1.2-sources.jar";
      sha256 = "995FEF27171DBCDCD5A32ABD8878345A529ADB12B0A04690CE1B6555881E4A6E";
    };
    "nix-public/org/apache/poi/poi-ooxml/4.1.2/poi-ooxml-4.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml/4.1.2/poi-ooxml-4.1.2.jar";
      sha256 = "0AAAEEEE3F5831B036B7053F8048B0F83AA9FA8897771FFD871DDFC84653EBA1";
    };
    "nix-public/org/apache/poi/poi-ooxml/4.1.2/poi-ooxml-4.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi-ooxml/4.1.2/poi-ooxml-4.1.2.pom";
      sha256 = "CF8965D0F33FA13B26C696DA578EB7911A9F176A5F2A6B5281631972717FD8E0";
    };
    "nix-public/org/apache/poi/poi/4.1.2/poi-4.1.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi/4.1.2/poi-4.1.2-javadoc.jar";
      sha256 = "DF53C08346D77368653BF9FF4F3F9577D76147D3F2B4E0DAB4FBF6A882D3C11F";
    };
    "nix-public/org/apache/poi/poi/4.1.2/poi-4.1.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi/4.1.2/poi-4.1.2-sources.jar";
      sha256 = "5D6BDACC3697E10529C14CBFE9374CD0F814C96E5E92AB4E1351313ECE4C7D2F";
    };
    "nix-public/org/apache/poi/poi/4.1.2/poi-4.1.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi/4.1.2/poi-4.1.2.jar";
      sha256 = "AB1612406541968434044B2DEFAD58AA8B657CAD073BAA22A04FAAF9D7FB9D1C";
    };
    "nix-public/org/apache/poi/poi/4.1.2/poi-4.1.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/poi/poi/4.1.2/poi-4.1.2.pom";
      sha256 = "F74B68589484D31DA2B3E3EEB53D920FF896FB32DDDB32479AE3D365A8A863AE";
    };
    "nix-public/org/apache/xmlbeans/xmlbeans/3.1.0/xmlbeans-3.1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/xmlbeans/xmlbeans/3.1.0/xmlbeans-3.1.0-javadoc.jar";
      sha256 = "B51885D19D7D7B34ADB1D54BA52E000E65CC1217D9F5E234660ADF69C9D66A64";
    };
    "nix-public/org/apache/xmlbeans/xmlbeans/3.1.0/xmlbeans-3.1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/xmlbeans/xmlbeans/3.1.0/xmlbeans-3.1.0-sources.jar";
      sha256 = "BE30967A0851A18239F504C24B85254273A6125ED5911603A9C8F897D2409E0B";
    };
    "nix-public/org/apache/xmlbeans/xmlbeans/3.1.0/xmlbeans-3.1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/apache/xmlbeans/xmlbeans/3.1.0/xmlbeans-3.1.0.jar";
      sha256 = "A19EA1EC835A101165F7AA3C55427E81B5F2B187BFE7689A19277C51402620B0";
    };
    "nix-public/org/apache/xmlbeans/xmlbeans/3.1.0/xmlbeans-3.1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/apache/xmlbeans/xmlbeans/3.1.0/xmlbeans-3.1.0.pom";
      sha256 = "784CBF2ED28153046C74DBC99B9296999559D77C98A169CB7FDD8921AC8438D9";
    };
    "nix-public/org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2-javadoc.jar";
      sha256 = "AEB3A99777C1B321C3CC207306FCCE609CB6B9CD132CA0AF72951864F170971D";
    };
    "nix-public/org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2-sources.jar";
      sha256 = "888CF1D3C4499715D45D14326FB73BA13CCB5E8469DE15E94A200216E484D019";
    };
    "nix-public/org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2.jar";
      sha256 = "BADF6081A0BB526FD2C01951DFEFAD91B6846B6DD0EB0048587E30D1DD334E68";
    };
    "nix-public/org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/codehaus/woodstox/stax2-api/4.2/stax2-api-4.2.pom";
      sha256 = "6215B474BD3714F1B9CF4DB5EA2837F4BAAF3B8DAF91210E87EA8CEA65A5097C";
    };
    "nix-public/org/eclipse/ee4j/project/1.0.2/project-1.0.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/eclipse/ee4j/project/1.0.2/project-1.0.2.pom";
      sha256 = "7495A07A797E88E43C3BC1A87421BD8B1FC55E32291FA18E4E32D8031DDC873F";
    };
    "nix-public/org/eclipse/ee4j/project/1.0.5/project-1.0.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/eclipse/ee4j/project/1.0.5/project-1.0.5.pom";
      sha256 = "916B4794D8D8220A59A3FDF6A64DBE794AEB23395E888B81AE36A9B5A2C591A6";
    };
    "nix-public/org/freemarker/freemarker/2.3.28/freemarker-2.3.28-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/freemarker/freemarker/2.3.28/freemarker-2.3.28-javadoc.jar";
      sha256 = "E52200EC493808CF265C73F91739149E4F294BEAF583551654AD0C7692889AC1";
    };
    "nix-public/org/freemarker/freemarker/2.3.28/freemarker-2.3.28-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/freemarker/freemarker/2.3.28/freemarker-2.3.28-sources.jar";
      sha256 = "A855AB20A0B72D1A876F708E2C377F549D9B46527E7E5845CF3CD02DC906668D";
    };
    "nix-public/org/freemarker/freemarker/2.3.28/freemarker-2.3.28.jar" = {
      url = "https://repo1.maven.org/maven2/org/freemarker/freemarker/2.3.28/freemarker-2.3.28.jar";
      sha256 = "DE92D103D3A86C2287307218FF50DC1C941DE283F7B9E1FB23E93FC7220838BF";
    };
    "nix-public/org/freemarker/freemarker/2.3.28/freemarker-2.3.28.pom" = {
      url = "https://repo1.maven.org/maven2/org/freemarker/freemarker/2.3.28/freemarker-2.3.28.pom";
      sha256 = "D61B2D74F2E335CB4F9A33FDCCC1784C1D99328AEB58D2DDC2515CCF0B4DEE91";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-javadoc.jar";
      sha256 = "27F7327AEE87324952DA2405B02094DF40A4E772B48DAE7E419D8B50067CA745";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3-sources.jar";
      sha256 = "E223D2D8FBAFD66057A8848CC94222D63C3CEDD652CC48EDDC0AB5C39C0F84DF";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar";
      sha256 = "66FDEF91E9739348DF7A096AA384A5685F4E875584CCE89386A7A47251C4D8E9";
    };
    "nix-public/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.pom";
      sha256 = "FDE386A7905173A1B103DE6AB820727584B50D0E32282E2797787C20A64FFA93";
    };
    "nix-public/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/hamcrest/hamcrest-parent/1.3/hamcrest-parent-1.3.pom";
      sha256 = "6D535F94EFB663BDB682C9F27A50335394688009642BA7A9677504BC1BE4129B";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-javadoc.jar";
      sha256 = "9175A09E404F75EC013219B54A51DF8788F890E0443BAE7A96FFC1AE74EF24F2";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0-sources.jar";
      sha256 = "C0926003987A5C21108748FDA401023485085EAA9FE90A41A40BCF67596FFF34";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.jar";
      sha256 = "D9D5DFD1BC49A8158E6E0A90B2ED08FA602984D815C00AF16CEC53557E83EF8E";
    };
    "nix-public/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_2.12/0.8.0/scala-java8-compat_2.12-0.8.0.pom";
      sha256 = "49E2711154CE9BA76962E043F4F8A6D0B890CD9E2FC6D0E99C3A0E6AD6C1950E";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-javadoc.jar";
      sha256 = "FF42809FBF887885C957B3D368A909C6CCDDEA4C0485E4FE3A6465ED7747B636";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6-sources.jar";
      sha256 = "A7E8AAC79394DF396AFDA98B35537791809D815CE15AB2224F7D31E50C753922";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.jar";
      sha256 = "7CC3B6CEB56E879CB977E8E043F4BFE2E062F78795EFD7EFA09F85003CB3230A";
    };
    "nix-public/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.0.6/scala-xml_2.12-1.0.6.pom";
      sha256 = "A8FDB9C75E3333D442F2CBE283F1E0F8573FF33F87CFE6DC22D154ABD0D29A0B";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-javadoc.jar";
      sha256 = "6816438CEB8357C14C0202D7B8F1CE9102C610944404E201D8601BD0EF65A9D1";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7-sources.jar";
      sha256 = "676F9865EEE108B703D812A21BA0BD9530E166157D431171CDC1964D359D514F";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.jar";
      sha256 = "6E80EF4493127214D31631287A6789170BF6C9A771D6094ACD8DC785E8970270";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.7/scala-compiler-2.12.7.pom";
      sha256 = "4E26B26FF0282A498515FAD296AE3949C071143C64C309FB0E4081DFCB1C46A5";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-javadoc.jar";
      sha256 = "E5B8691423267DDF1343BA45684C53884D67588B83CAC89EDC17C0D5A4FC5057";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8-sources.jar";
      sha256 = "51706711A1399F06206745907F188815C31F2DD95B39B01F0E2C2FC78B0E7E3B";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.jar";
      sha256 = "F34E9119F45ABD41E85B9E121BA19DD9288B3B4AF7F7047E86DC70236708D170";
    };
    "nix-public/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.12.8/scala-compiler-2.12.8.pom";
      sha256 = "CD113C73BD725B366F196015680C74916F7510E649799D45DED1A7E488D58E7F";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-javadoc.jar";
      sha256 = "BE85F3E1CBC005C4111019D0A84D4AEC2E5438BD1BDDD8CC2EFEF847F1BBE3A9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0-sources.jar";
      sha256 = "456B9B5A0CD6581923E8938305EAE7A61976706B4E771EF158FAF25F85F882DC";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.jar";
      sha256 = "0E72EC4EA955D0BAD7F1A494E8DF95163F1631DF0CE8EC4F9F278FE4D5FD1824";
    };
    "nix-public/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.0/scala-library-2.12.0.pom";
      sha256 = "093CA3B7FD4C3D48222F30DA4526808E3E8EF2D4456D1E75793F105D437A24EA";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1-javadoc.jar";
      sha256 = "7F6BF6122E13E034507118BAB9D61C3BD41637E24C2120D41690C2D8F542FACA";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1-sources.jar";
      sha256 = "4F73F24D18108DF3641A6333A1F2BE4F43FCCA982A3A769A5F6C8F99558293CD";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.jar";
      sha256 = "9DAB78F3F205A038F48183B2391F8A593235F794D8129A479E06AF3E6BC50EF8";
    };
    "nix-public/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.1/scala-library-2.12.1.pom";
      sha256 = "E2C373E1C000D8431BD625729DB33DCE68B379D3537769D29E18514CB2B3050C";
    };
    "nix-public/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11-javadoc.jar";
      sha256 = "D54EB306E7150299B545627FA66CEE7E501B1A22824148A584DD61CD42172B25";
    };
    "nix-public/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11-sources.jar";
      sha256 = "9BDBD6A182ED1E4B42ACB9F5BA87867C9E0A37EF8AF7FB781502765C00027010";
    };
    "nix-public/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11.jar";
      sha256 = "DBFE77A3FC7A16C0C7CB6CB2B91FECEC5438F2803112A744CB1B187926A138BE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.11/scala-library-2.12.11.pom";
      sha256 = "6C715A63EFE14767694FF1BD19782F02BF062C8CDB40CE2C56B0B1F3CAC901B6";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-javadoc.jar";
      sha256 = "23443C33B32E3CC9FF6BABB69012E4CD0D4D68CB2AA6B19ADDE1FB274BD45F58";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4-sources.jar";
      sha256 = "B9C34CF968A0E348ECEC32837797A794FFEADE2FE016323474FE756CB7D74042";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar";
      sha256 = "17824FCEE4D3F46CFAA4DA84EBAD4F58496426C2B9BC9E341F812AB23A667D5D";
    };
    "nix-public/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.pom";
      sha256 = "63BDCD46CED3D72F03C38DFCDAF610BB94A286E317C072078D8E0B729B55A099";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-javadoc.jar";
      sha256 = "0B9578DBE2B2F35DD438546E3A6C1314950FDDC3232220FE250E498148D8E4AE";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7-sources.jar";
      sha256 = "1631F768D506FAA08E4C4769F5B07DD37BDD92720B44C0DC223F3EDE801F5734";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.jar";
      sha256 = "8F3DC6091DB688464AD8B1EE6C7343D7AA5940D474EE8B90406C71E45DD74FC0";
    };
    "nix-public/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/scala-library-2.12.7.pom";
      sha256 = "2255FD693D69DDD6954B6B7F614AF4ED93EB6AA6A27EBFE01E65DB194DAECAA9";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-javadoc.jar";
      sha256 = "9940E7CF343DFBDDDEB60B538E559496B836430400575405FE46C7176B95C78E";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8-sources.jar";
      sha256 = "11482BCB49B2E47BAEE89C3B1AE10C6A40B89E2FBB0DA2A423E062F444E13492";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.jar";
      sha256 = "321FB55685635C931EBA4BC0D7668349DA3F2C09AEE2DE93A70566066FF25C28";
    };
    "nix-public/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.8/scala-library-2.12.8.pom";
      sha256 = "22E81EE9D5349BA0E897ADB5C7FCEC25656C9E0B7B86C3E93E9A7AF360481C0D";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1-javadoc.jar";
      sha256 = "A4644B9F06986C8619CEE3216D7383D974F5C1100364C7776357F3533DC4A4E9";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1-sources.jar";
      sha256 = "DF915BF043F037C8FF5A6F0A88DD8CFC3A927212AE93A61D18049F0A54477E06";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.jar";
      sha256 = "D8A2B9D6D78C7457A40E394DC0C4FA6D6244ACF0D156BBBCB311A9D497B85EEC";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.1/scala-reflect-2.12.1.pom";
      sha256 = "808B17C95D7E260A375615992CD1FCE7D759B6FDEF5E64D7B70E3942AE014261";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-javadoc.jar";
      sha256 = "5DE7917046C0DA3BA5766563B14B0B75EE23E87FDC2426771EF2885CADA9912B";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4-sources.jar";
      sha256 = "7B4DC73DC3CB46AC9AC948A0C231CCD989BED6CEFB137C302A8EC8D6811E8148";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.jar";
      sha256 = "EA70FE0E550E24D23FC52A18963B2BE9C3B24283F4CB18B98327EB72746567CC";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.4/scala-reflect-2.12.4.pom";
      sha256 = "9BB07CA874C7EC1A945E32A02D4308BD3D655A3ABD7A23CEB1F109C795339CE0";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-javadoc.jar";
      sha256 = "F9412EED83A4FB68F6839B54DCA545CBA07F127D456060B81EC76C7781300E48";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7-sources.jar";
      sha256 = "2B84D948A67FA7F5C4C6CCA9C4AEFB83BC3BED76DB69989D1E2D0977532942C2";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.jar";
      sha256 = "7427D7EE5771E8C36C1DB5A09368FA3078F6ECEB77D7C797A322A088C5DDDB76";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.7/scala-reflect-2.12.7.pom";
      sha256 = "1C5DCB05333F33C0674D039E348789A7525208ED4F8316A9199D255B824E038A";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-javadoc.jar";
      sha256 = "F7D299D01D190E239144A4C74D4EB33FA92C057B1D8F161FB7D75FD07E6426C4";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8-sources.jar";
      sha256 = "5C676791217D9B48560496556B8965CCEABCBFDBB65BBEBDC52E99C0A3847735";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.jar";
      sha256 = "4D6405395C4599CE04CEA08BA082339E3E42135DE9AAE2923C9F5367E957315A";
    };
    "nix-public/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.12.8/scala-reflect-2.12.8.pom";
      sha256 = "CBFFFF8D495FFD66C1234469A2965F54A82FA58E6816EE0E5803E896CAC167C3";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-javadoc.jar";
      sha256 = "58CAA3EAE25920DFBA5FACBC0C449CBA01994982E96C992D080E0EE52F886AE2";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5-sources.jar";
      sha256 = "4589D87CC22D0C370BD1708F328D31B98B4BAED38D1BAA8F595CA1BD5CA528E6";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.jar";
      sha256 = "C342EAB071B314D125B3AC00C3CE3B2287A478A64639AD210BE7FFC25835CE01";
    };
    "nix-public/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-bridge_2.12/1.2.5/compiler-bridge_2.12-1.2.5.pom";
      sha256 = "EBF9B8ED3CCEF14B5D8904401C60D92E32B276C12CD0A152C671D184EFF28C97";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-javadoc.jar";
      sha256 = "9DD282695276A298DB294BE7C50663D750598DDF1F4C07B5B54E9D48DEE5445E";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5-sources.jar";
      sha256 = "5EDF42C3DE05267BD79F413EA22CDB7C53B99719395387E4A988D087DE7B2212";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.jar";
      sha256 = "502C7F02FF1F99E7B125537A456601AAF31A24C997BBC265C24CA6DD3B7442BD";
    };
    "nix-public/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/compiler-interface/1.2.5/compiler-interface-1.2.5.pom";
      sha256 = "1DBE0A87AE1489F9419A416F96DB4D3EE12B351CB58A09B8EB9C8E8447AE5A92";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-javadoc.jar";
      sha256 = "A63861B771C20DF0DAB78F26A4FDD573C065FC569DDEF9C907A427B2F57C98A5";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0-sources.jar";
      sha256 = "C314491C9DF4F0BD9DD125EF1D51228D70BD466EE57848DF1CD1B96AEA18A5AD";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar";
      sha256 = "15F70B38BB95F3002FEC9AEA54030F19BB4ECFBAD64C67424B5E5FEA09CD749E";
    };
    "nix-public/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.pom";
      sha256 = "61BA06A9D0C226E10F048004FCEBFB300FDD9B077D05ED502E9875324C8B762E";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-javadoc.jar";
      sha256 = "D3421C2A8450FCF646ECCEADE47B5D8F3280BE3A68D8178C11DC2F8BF2EE0375";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2-sources.jar";
      sha256 = "A41F082F90CFE665755AEDB007F0F82BA8499D4EF0F58253AFDD79DD3A1C63BA";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.jar" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.jar";
      sha256 = "ADB18E5F79A028F2B33506CCC6A4B24500DD985628B05308A7AF5ACBD1EE2CD7";
    };
    "nix-public/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.pom" = {
      url = "https://repo1.maven.org/maven2/org/scala-sbt/util-interface/1.2.2/util-interface-1.2.2.pom";
      sha256 = "7DE9EC96F383FCC18C17A0E7513071EC929F21D1CFD81EFC028BB307CC7E9BB7";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3-javadoc.jar";
      sha256 = "E97F63A7F7042A20EA41030E5AC6956C60F33638F762634C0EF2ED1DCE4B8514";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3-sources.jar";
      sha256 = "EB82A1E68E67DF4FE357EA65FB230F3A2CF1A225020888489313BBE0D4ECACEE";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.jar";
      sha256 = "245AD1BAAB6661AEE70C137C5E1625771C2624596B349B305801D94618673292";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.3/scalactic_2.12-3.0.3.pom";
      sha256 = "0B33F9E2D47FA7F829E7E1646BD3EE3D4A4FF4E8A61775F345449E1D5757EB46";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5-javadoc.jar";
      sha256 = "80C7CBB0BD10830E0A4281FB0ACB00355BEB461420203F7D379B14494E1AEDFD";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5-sources.jar";
      sha256 = "0455EAECAA2B8CE0BE537120C2CCD407C4606CBE53E63CB6A7FC8B31B5B65461";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5.jar";
      sha256 = "57E25B4FD969B1758FE042595112C874DFEA99DCA5CC48EEBE07AC38772A0C41";
    };
    "nix-public/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalactic/scalactic_2.12/3.0.5/scalactic_2.12-3.0.5.pom";
      sha256 = "A7DE321F1250ECC528CD8E1249541EAD9C423E93E2D04F682C3029EFDA3198DE";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5-javadoc.jar";
      sha256 = "057D6F58CD601EF10C678D653CA5E734BAA1CB809325CBC04914D02C563E784E";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5-sources.jar";
      sha256 = "22081EE83810098ADC9AF4D84D05DD5891D7C0E15F9095BCDAF4AC7A228B92DF";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5.jar" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5.jar";
      sha256 = "B416B5BCEF6720DA469A8D8A5726E457FC2D1CD5D316E1BC283AA75A2AE005E5";
    };
    "nix-public/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5.pom" = {
      url = "https://repo1.maven.org/maven2/org/scalatest/scalatest_2.12/3.0.5/scalatest_2.12-3.0.5.pom";
      sha256 = "D573B5D2F00A26F0B6B7E8BE0E52B11EFCF76F0BCEC1BB2AC48CB0DC164E02AB";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-javadoc.jar";
      sha256 = "8DC4B97B764D6C5B732479936C6CA28DFE9480C8A9B67E4B26CF95C8C64D77BD";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-sources.jar";
      sha256 = "C4BC93180A4F0ACEEC3B057A2514ABE04A79F06C174BBED910A2AFB227B79366";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25-tests.jar";
      sha256 = "FB82F52621D9DDAFB135DFF968A75B5BC08C40BA4BE77B5AB8DEA8711A032D72";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.jar";
      sha256 = "18C4A0095D5C1DA6B817592E767BB23D29DD2F560AD74DF75FF3961DBDE25B79";
    };
    "nix-public/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.25/slf4j-api-1.7.25.pom";
      sha256 = "7CD9D7A0B5D93DFD461A148891B43509CF403A9C7F9FB49060D3554DF1C81E1E";
    };
    "nix-public/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom" = {
      url = "https://repo1.maven.org/maven2/org/slf4j/slf4j-parent/1.7.25/slf4j-parent-1.7.25.pom";
      sha256 = "18F5C52120DB036E88D6136F8839C832D074BDDA95C756C6F429249D2DB54AC6";
    };
    "nix-public/org/sonatype/oss/oss-parent/7/oss-parent-7.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/7/oss-parent-7.pom";
      sha256 = "B51F8867C92B6A722499557FC3A1FDEA77BDF9EF574722FE90CE436A29559454";
    };
    "nix-public/org/sonatype/oss/oss-parent/9/oss-parent-9.pom" = {
      url = "https://repo1.maven.org/maven2/org/sonatype/oss/oss-parent/9/oss-parent-9.pom";
      sha256 = "FB40265F982548212FF82E362E59732B2187EC6F0D80182885C14EF1F982827A";
    };
  };
}
