# This file has been generated by node2nix 1.9.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "async-1.0.0" = {
      name = "async";
      packageName = "async";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.0.0.tgz";
        sha1 = "f8fc04ca3a13784ade9e1641af98578cfbd647a9";
      };
    };
    "async-2.6.3" = {
      name = "async";
      packageName = "async";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.3.tgz";
        sha512 = "zflvls11DCy+dQWzTW2dzuilv8Z5X/pjfmZOWba6TNIVDm+2UDaJmXSOXlasHKfNBs8oo3M0aT50fDEWfKZjXg==";
      };
    };
    "async-limiter-1.0.1" = {
      name = "async-limiter";
      packageName = "async-limiter";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-limiter/-/async-limiter-1.0.1.tgz";
        sha512 = "csOlWGAcRFJaI6m+F2WKdnMKr4HhdhFVBk0H/QbJFMCr+uO2kwohwXQPxw/9OCxp05r5ghVBFSyioixx3gfkNQ==";
      };
    };
    "backoff-2.3.0" = {
      name = "backoff";
      packageName = "backoff";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/backoff/-/backoff-2.3.0.tgz";
        sha1 = "ee7c7e38093f92e472859db635e7652454fc21ea";
      };
    };
    "bintrees-1.0.1" = {
      name = "bintrees";
      packageName = "bintrees";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bintrees/-/bintrees-1.0.1.tgz";
        sha1 = "0e655c9b9c2435eaab68bf4027226d2b55a34524";
      };
    };
    "bufferutil-4.0.3" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.3.tgz";
        sha512 = "yEYTwGndELGvfXsImMBLop58eaGW+YdONi1fNjTINSY98tmMmFijBG6WXgdkfuLNt4imzQNtIE+eBp1PVpMCSw==";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "commander-2.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.1.0.tgz";
        sha1 = "d121bbae860d9992a3d517ba96f56588e47c6781";
      };
    };
    "config-3.3.6" = {
      name = "config";
      packageName = "config";
      version = "3.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/config/-/config-3.3.6.tgz";
        sha512 = "Hj5916C5HFawjYJat1epbyY2PlAgLpBtDUlr0MxGLgo3p5+7kylyvnRY18PqJHgnNWXcdd0eWDemT7eYWuFgwg==";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "denque-1.5.0" = {
      name = "denque";
      packageName = "denque";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/denque/-/denque-1.5.0.tgz";
        sha512 = "CYiCSgIF1p6EUByQPlGkKnP1M9g0ZV3qMIrqMqZqdwazygIA/YP2vrbcyl1h/WppKJTdl1F85cXIle+394iDAQ==";
      };
    };
    "es-abstract-1.15.0" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.15.0.tgz";
        sha512 = "bhkEqWJ2t2lMeaJDuk7okMkJWI/yqgH/EoGwpcvv0XW9RWQsRspI4wt6xuyuvMvvQE3gg/D9HXppgk21w78GyQ==";
      };
    };
    "es-to-primitive-1.2.0" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.0.tgz";
        sha512 = "qZryBOJjV//LaxLTV6UC//WewneB3LcXOL9NP++ozKVXsIIIpm/2c13UDiD9Jp2eThsecw9m3jPqDwTyobcdbg==";
      };
    };
    "es6-promise-4.2.8" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-4.2.8.tgz";
        sha512 = "HJDGx5daxeIvxdBxvG2cb9g4tEvwIk3i8+nhX0yGrYmZUzbkdg8QbDevheDB8gd0//uPj4c1EQua8Q+MViT0/w==";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "eventemitter2-4.1.2" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-4.1.2.tgz";
        sha1 = "0e1a8477af821a6ef3995b311bf74c23a5247f15";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-symbols-1.0.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.0.tgz";
        sha1 = "ba1a8f1af2a0fc39650f5c850367704122063b44";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "ipaddr.js-1.9.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
        sha512 = "0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
      };
    };
    "is-callable-1.1.4" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.1.4.tgz";
        sha512 = "r5p9sxJjYnArLjObpjA4xu5EKI3CuKHkJXMhT7kwbpUyIFD1n5PMAsoPvWnvtZiNz7LjkYDRZhd7FlI0eMijEA==";
      };
    };
    "is-date-object-1.0.1" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.1.tgz";
        sha1 = "9aa20eb6aeebbff77fbd33e74ca01b33581d3a16";
      };
    };
    "is-regex-1.0.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.0.4.tgz";
        sha1 = "5517489b547091b0930e095654ced25ee97e9491";
      };
    };
    "is-symbol-1.0.2" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.2.tgz";
        sha512 = "HS8bZ9ox60yCJLH9snBpIwv9pYUAkcuLhSA1oero1UB5y9aiQpRA8y2ex945AOtCZL1lJDeIk3G5LthswI46Lw==";
      };
    };
    "isbuffer-0.0.0" = {
      name = "isbuffer";
      packageName = "isbuffer";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isbuffer/-/isbuffer-0.0.0.tgz";
        sha1 = "38c146d9df528b8bf9b0701c3d43cf12df3fc39b";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "js-yaml-3.13.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.13.1.tgz";
        sha512 = "YfbcO7jXDdyj0DGxYVSlSeQNHbD7XPWvrVWeVUujrQEoZzWJIRrCPoyk6kL6IAjAG2IolMK4T0hNUe0HOUs5Jw==";
      };
    };
    "json5-2.2.0" = {
      name = "json5";
      packageName = "json5";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-2.2.0.tgz";
        sha512 = "f+8cldu7X/y7RAJurMEJmdoKXGB/X550w2Nr3tTbezL6RwEE/iMcm+tZnXeoZtKuOq6ft8+CqzEkrIgx1fPoQA==";
      };
    };
    "kurento-client-6.16.0" = {
      name = "kurento-client";
      packageName = "kurento-client";
      version = "6.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kurento-client/-/kurento-client-6.16.0.tgz";
        sha512 = "vZDJ/qAH2XiCYTvfC+gWTyPgzr2ZbzPA89z5wWKB0Me/05VV4Z2MGGJ19Q2reQVir3s7LFFDzOIB/0FX5xMA6Q==";
      };
    };
    "kurento-client-core-6.16.0" = {
      name = "kurento-client-core";
      packageName = "kurento-client-core";
      version = "6.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kurento-client-core/-/kurento-client-core-6.16.0.tgz";
        sha512 = "TMpniXf0G/fIdFkwAn/coUkbVnhzwv7OBUco+KDtm1Xb7VED15rx20tl0ieswKVGm12wB4xegt1rRcZHoEJJ+g==";
      };
    };
    "kurento-client-elements-6.16.0" = {
      name = "kurento-client-elements";
      packageName = "kurento-client-elements";
      version = "6.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kurento-client-elements/-/kurento-client-elements-6.16.0.tgz";
        sha512 = "lsZiUIRrTh8PA+0DivTmDWlTJLTrgy2BRs6l3ImhFgZpSXg+iaGk7xITsczp6VMnDzLuA5DkOwquPqiMHJVBcg==";
      };
    };
    "kurento-client-filters-6.16.0" = {
      name = "kurento-client-filters";
      packageName = "kurento-client-filters";
      version = "6.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kurento-client-filters/-/kurento-client-filters-6.16.0.tgz";
        sha512 = "Wi+Pginw8YeBLfJfBfQUp4/YCEWnwXAaatysnBygdWt21Uz3oqbEiLJOOIBwefUXP1FwKoI+bMPRevkosuimZw==";
      };
    };
    "kurento-jsonrpc-6.16.0" = {
      name = "kurento-jsonrpc";
      packageName = "kurento-jsonrpc";
      version = "6.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kurento-jsonrpc/-/kurento-jsonrpc-6.16.0.tgz";
        sha512 = "Z6LAh033dHuL2HiQGxbLvVKwSMKwUVnEEZE4nuDBbr9ZdtAeqr5aaUu+B7bpbeGhondkS1gvDLJHwqWinFszjQ==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "mcs-js-git+https://github.com/mconf/mcs-js.git#a134f18ead5f5de1a9f60d0e8cc547ed19dfd39f" = {
      name = "mcs-js";
      packageName = "mcs-js";
      version = "0.0.11";
      src = fetchgit {
        url = "https://github.com/mconf/mcs-js.git";
        rev = "a134f18ead5f5de1a9f60d0e8cc547ed19dfd39f";
        sha256 = "a6991a8c66ae8278d705ed20b4e8b97fd072564c5f88de7c3733ea5bb1f57209";
      };
    };
    "minimist-1.2.5" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.5.tgz";
        sha512 = "FM9nNUYrRBAELZQT3xeZQ7fmMOBg6nWNmJKTcgsJeaLstP/UODVpGsr5OhXhhXg6f+qtJ8uiZ+PUxkDWcgIXLw==";
      };
    };
    "modesl-1.2.1" = {
      name = "modesl";
      packageName = "modesl";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/modesl/-/modesl-1.2.1.tgz";
        sha512 = "B4ROC+xyZ9guF91dYSMQFLccHogjbMOA5Z3z17DLX1i2Dx8H+fIrTfoc1LWLAltqGf0WlnXZoosbC8BEPYY31w==";
      };
    };
    "nan-1.0.0" = {
      name = "nan";
      packageName = "nan";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-1.0.0.tgz";
        sha1 = "ae24f8850818d662fcab5acf7f3b95bfaa2ccf38";
      };
    };
    "nanoid-1.3.4" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-1.3.4.tgz";
        sha512 = "4ug4BsuHxiVHoRUe1ud6rUFT3WUMmjXt1W0quL0CviZQANdan7D8kqN5/maw53hmAApY/jfzMRkC57BNNs60ZQ==";
      };
    };
    "node-gyp-build-4.2.3" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "4.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-4.2.3.tgz";
        sha512 = "MN6ZpzmfNCRM+3t57PTJHgHyw/h4OWnZ6mR8P5j/uZtqQr46RRuDE/P+g3n0YR/AiYXeWixZZzaip77gdICfRg==";
      };
    };
    "object-inspect-1.6.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.6.0.tgz";
        sha512 = "GJzfBZ6DgDAmnuaM3104jR4s1Myxr3Y3zfIyN4z3UdqN69oSRacNK8UhnobDdC+7J2AHCjGwxQubNJfE70SXXQ==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.getownpropertydescriptors-2.0.3" = {
      name = "object.getownpropertydescriptors";
      packageName = "object.getownpropertydescriptors";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.0.3.tgz";
        sha1 = "8758c846f5b407adab0f236e0986f14b051caa16";
      };
    };
    "options-0.0.6" = {
      name = "options";
      packageName = "options";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/options/-/options-0.0.6.tgz";
        sha1 = "ec22d312806bb53e731773e7cdaefcf1c643128f";
      };
    };
    "pegjs-0.8.0" = {
      name = "pegjs";
      packageName = "pegjs";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pegjs/-/pegjs-0.8.0.tgz";
        sha1 = "976f067da13e5c5b1501c017925668a253811561";
      };
    };
    "prom-client-13.1.0" = {
      name = "prom-client";
      packageName = "prom-client";
      version = "13.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prom-client/-/prom-client-13.1.0.tgz";
        sha512 = "jT9VccZCWrJWXdyEtQddCDszYsiuWj5T0ekrPszi/WEegj3IZy6Mm09iOOVM86A4IKMWq8hZkT2dD9MaSe+sng==";
      };
    };
    "promiscuous-0.6.0" = {
      name = "promiscuous";
      packageName = "promiscuous";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promiscuous/-/promiscuous-0.6.0.tgz";
        sha1 = "54014cd3d62cafe831e3354990c05ff5b78c8892";
      };
    };
    "promise-7.1.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.1.1.tgz";
        sha1 = "489654c692616b8aa55b0724fa809bb7db49c5bf";
      };
    };
    "promisecallback-0.0.4" = {
      name = "promisecallback";
      packageName = "promisecallback";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/promisecallback/-/promisecallback-0.0.4.tgz";
        sha1 = "b934f13c04e443622b4d66de4e42ea5f6ce66e74";
      };
    };
    "queue-6.0.1" = {
      name = "queue";
      packageName = "queue";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue/-/queue-6.0.1.tgz";
        sha512 = "AJBQabRCCNr9ANq8v77RJEv73DPbn55cdTb+Giq4X0AVnNVZvMHlYp7XlQiN+1npCZj1DuSmaA2hYVUUDgxFDg==";
      };
    };
    "readable-id-1.0.0" = {
      name = "readable-id";
      packageName = "readable-id";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-id/-/readable-id-1.0.0.tgz";
        sha512 = "RXwuv4YQNYByl+PpQVA4PR4H+aGTWOtpRx56LrxJ2Ypxf96u9WaIdKGOCqu7MPBt8iqQkYPQUk4KGbL55n78YQ==";
      };
    };
    "reconnect-core-git://github.com/kurentoforks/reconnect-core#921d43e91578abb2fb2613f585c010c1939cf734" = {
      name = "reconnect-core";
      packageName = "reconnect-core";
      version = "1.0.0";
      src = fetchgit {
        url = "git://github.com/kurentoforks/reconnect-core";
        rev = "921d43e91578abb2fb2613f585c010c1939cf734";
        sha256 = "03341b99f9373f70fee254e507357461231fa98f086cccba6bc54688cfccd6e7";
      };
    };
    "reconnect-ws-git://github.com/kurentoforks/reconnect-ws#f287385d75861654528c352e60221f95c9209f8a" = {
      name = "reconnect-ws";
      packageName = "reconnect-ws";
      version = "0.0.0";
      src = fetchgit {
        url = "git://github.com/kurentoforks/reconnect-ws";
        rev = "f287385d75861654528c352e60221f95c9209f8a";
        sha256 = "3739bfef3fea45d7c914aa5adc7111c4fd281dbe720fb3041ab1935a99c43506";
      };
    };
    "redis-3.1.2" = {
      name = "redis";
      packageName = "redis";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis/-/redis-3.1.2.tgz";
        sha512 = "grn5KoZLr/qrRQVwoSkmzdbw6pwF+/rwODtrOr6vuBRiR/f3rjSTGupbF90Zpqm2oenix8Do6RV7pYEkGwlKkw==";
      };
    };
    "redis-commands-1.7.0" = {
      name = "redis-commands";
      packageName = "redis-commands";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-commands/-/redis-commands-1.7.0.tgz";
        sha512 = "nJWqw3bTFy21hX/CPKHth6sfhZbdiHP6bTawSgQBlKOVRG7EZkfHbbHwQJnrE4vsQf0CMNE+3gJ4Fmm16vdVlQ==";
      };
    };
    "redis-errors-1.2.0" = {
      name = "redis-errors";
      packageName = "redis-errors";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-errors/-/redis-errors-1.2.0.tgz";
        sha1 = "eb62d2adb15e4eaf4610c04afe1529384250abad";
      };
    };
    "redis-parser-3.0.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-3.0.0.tgz";
        sha1 = "b66d828cdcafe6b4b8a428a7def4c6bcac31c8b4";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "sdp-transform-2.13.0" = {
      name = "sdp-transform";
      packageName = "sdp-transform";
      version = "2.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sdp-transform/-/sdp-transform-2.13.0.tgz";
        sha512 = "3zT7pcjR090E0WCV9eOtFX06iojoNKsyMXqXs7clOs8sy+RoegR0cebmCuCrTKdY2jw1XhT9jkraygJrqAUwzA==";
      };
    };
    "sip.js-git+https://github.com/mconf/sip.js.git#ae6c71b09813210c3da9f5b46e8076f3b324e948" = {
      name = "sip.js";
      packageName = "sip.js";
      version = "0.7.5";
      src = fetchgit {
        url = "https://github.com/mconf/sip.js.git";
        rev = "ae6c71b09813210c3da9f5b46e8076f3b324e948";
        sha256 = "b366c3b40a85b1bbdc7f05a9a426ae9219626ebcc233d9e37db401864f5c6e70";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "string.prototype.trimleft-2.1.0" = {
      name = "string.prototype.trimleft";
      packageName = "string.prototype.trimleft";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimleft/-/string.prototype.trimleft-2.1.0.tgz";
        sha512 = "FJ6b7EgdKxxbDxc79cOlok6Afd++TTs5szo+zJTUyow3ycrRfJVE2pq3vcN53XexvKZu/DJMDfeI/qMiZTrjTw==";
      };
    };
    "string.prototype.trimright-2.1.0" = {
      name = "string.prototype.trimright";
      packageName = "string.prototype.trimright";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimright/-/string.prototype.trimright-2.1.0.tgz";
        sha512 = "fXZTSV55dNBwv16uw+hh5jkghxSnc5oHq+5K/gXgizHwAvMetdAJlHqqoFC1FSDVPYWLkAKl2cxpUT41sV7nSg==";
      };
    };
    "tdigest-0.1.1" = {
      name = "tdigest";
      packageName = "tdigest";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tdigest/-/tdigest-0.1.1.tgz";
        sha1 = "2e3cb2c39ea449e55d1e6cd91117accca4588021";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "tinycolor-0.0.1" = {
      name = "tinycolor";
      packageName = "tinycolor";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinycolor/-/tinycolor-0.0.1.tgz";
        sha1 = "320b5a52d83abb5978d81a3e887d4aefb15a6164";
      };
    };
    "util.promisify-1.0.0" = {
      name = "util.promisify";
      packageName = "util.promisify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/util.promisify/-/util.promisify-1.0.0.tgz";
        sha512 = "i+6qA2MPhvoKLuxnJNpXAGhg7HphQOSUq2LKMZD0m15EiskXUkMvKdF4Uui0WYeCUGea+o2cw/ZuwehtfsrNkA==";
      };
    };
    "uuid-3.4.0" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.4.0.tgz";
        sha512 = "HjSDRw6gZE5JMggctHBcjVak08+KEVhSIiDzFnT9S9aegmp85S/bReBVTb4QTFaRNptJ9kuYaNhnbNEOkbKb/A==";
      };
    };
    "uuid-8.3.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "8.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-8.3.1.tgz";
        sha512 = "FOmRr+FmWEIG8uhZv6C2bTgEVXsHk08kE7mPlrBbEe+c3r9pjceVPgupIfNIhc4yx55H69OXANrUaSuu9eInKg==";
      };
    };
    "websocket-stream-0.5.1" = {
      name = "websocket-stream";
      packageName = "websocket-stream";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-stream/-/websocket-stream-0.5.1.tgz";
        sha1 = "622cd1f0566fb84ce0a4d6f854526f3dc4d70e48";
      };
    };
    "winston-2.4.5" = {
      name = "winston";
      packageName = "winston";
      version = "2.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-2.4.5.tgz";
        sha512 = "TWoamHt5yYvsMarGlGEQE59SbJHqGsZV8/lwC+iCcGeAe0vUaOh+Lv6SYM17ouzC/a/LB1/hz/7sxFBtlu1l4A==";
      };
    };
    "ws-0.4.32" = {
      name = "ws";
      packageName = "ws";
      version = "0.4.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-0.4.32.tgz";
        sha1 = "787a6154414f3c99ed83c5772153b20feb0cec32";
      };
    };
    "ws-6.2.2" = {
      name = "ws";
      packageName = "ws";
      version = "6.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-6.2.2.tgz";
        sha512 = "zmhltoSR8u1cnDsD43TX59mzoMZsLKqUweyYBAIvTngR3shc0W6aOZylZmq/7hqyVxPdi+5Ud2QInblgyE72fw==";
      };
    };
    "ws-7.4.6" = {
      name = "ws";
      packageName = "ws";
      version = "7.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.4.6.tgz";
        sha512 = "YmhHDO4MzaDLB+M9ym/mDA5z0naX8j7SIlT8f8z+I0VtzsRbekxEutHSme7NPS2qE8StCYQNUnfWdXta/Yu85A==";
      };
    };
    "xml2js-0.4.22" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.22.tgz";
        sha512 = "MWTbxAQqclRSTnehWWe5nMKzI3VmJ8ltiJEco8akcC6j3miOhjjfzKum5sId+CWhfxdOs/1xauYr8/ZDBtQiRw==";
      };
    };
    "xmlbuilder-11.0.1" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-11.0.1.tgz";
        sha512 = "fDlsI/kFEx7gLvbecc0/ohLG50fugQp8ryHzMTuW9vSa1GJ0XYWKnhsUx7oie3G98+r56aTQIUB4kht42R3JvA==";
      };
    };
  };
  args = {
    name = "bbb-webrtc-sfu";
    packageName = "bbb-webrtc-sfu";
    version = "2.5.2";
    src = ./.;
    dependencies = [
      sources."argparse-1.0.10"
      sources."asap-2.0.6"
      sources."async-2.6.3"
      sources."async-limiter-1.0.1"
      sources."backoff-2.3.0"
      sources."bintrees-1.0.1"
      sources."bufferutil-4.0.3"
      sources."colors-1.0.3"
      sources."commander-2.1.0"
      sources."config-3.3.6"
      sources."cycle-1.0.3"
      sources."define-properties-1.1.3"
      sources."denque-1.5.0"
      sources."es-abstract-1.15.0"
      sources."es-to-primitive-1.2.0"
      sources."es6-promise-4.2.8"
      sources."esprima-4.0.1"
      sources."eventemitter2-4.1.2"
      sources."extend-3.0.2"
      sources."eyes-0.1.8"
      sources."function-bind-1.1.1"
      sources."has-1.0.3"
      sources."has-symbols-1.0.0"
      sources."inherits-2.0.4"
      sources."ipaddr.js-1.9.1"
      sources."is-callable-1.1.4"
      sources."is-date-object-1.0.1"
      sources."is-regex-1.0.4"
      sources."is-symbol-1.0.2"
      sources."isbuffer-0.0.0"
      sources."isstream-0.1.2"
      sources."js-yaml-3.13.1"
      sources."json5-2.2.0"
      sources."kurento-client-6.16.0"
      sources."kurento-client-core-6.16.0"
      sources."kurento-client-elements-6.16.0"
      sources."kurento-client-filters-6.16.0"
      sources."kurento-jsonrpc-6.16.0"
      sources."lodash-4.17.21"
      sources."mcs-js-git+https://github.com/mconf/mcs-js.git#a134f18ead5f5de1a9f60d0e8cc547ed19dfd39f"
      sources."minimist-1.2.5"
      (sources."modesl-1.2.1" // {
        dependencies = [
          sources."uuid-3.4.0"
        ];
      })
      sources."nan-1.0.0"
      sources."nanoid-1.3.4"
      sources."node-gyp-build-4.2.3"
      sources."object-inspect-1.6.0"
      sources."object-keys-1.1.1"
      sources."object.getownpropertydescriptors-2.0.3"
      sources."options-0.0.6"
      sources."pegjs-0.8.0"
      sources."prom-client-13.1.0"
      sources."promiscuous-0.6.0"
      sources."promise-7.1.1"
      sources."promisecallback-0.0.4"
      sources."queue-6.0.1"
      sources."readable-id-1.0.0"
      sources."reconnect-core-git://github.com/kurentoforks/reconnect-core#921d43e91578abb2fb2613f585c010c1939cf734"
      sources."reconnect-ws-git://github.com/kurentoforks/reconnect-ws#f287385d75861654528c352e60221f95c9209f8a"
      sources."redis-3.1.2"
      sources."redis-commands-1.7.0"
      sources."redis-errors-1.2.0"
      sources."redis-parser-3.0.0"
      sources."sax-1.2.4"
      sources."sdp-transform-2.13.0"
      (sources."sip.js-git+https://github.com/mconf/sip.js.git#ae6c71b09813210c3da9f5b46e8076f3b324e948" // {
        dependencies = [
          sources."ws-6.2.2"
        ];
      })
      sources."sprintf-js-1.0.3"
      sources."stack-trace-0.0.10"
      sources."string.prototype.trimleft-2.1.0"
      sources."string.prototype.trimright-2.1.0"
      sources."tdigest-0.1.1"
      sources."through-2.3.8"
      sources."tinycolor-0.0.1"
      sources."util.promisify-1.0.0"
      sources."uuid-8.3.1"
      (sources."websocket-stream-0.5.1" // {
        dependencies = [
          sources."ws-0.4.32"
        ];
      })
      (sources."winston-2.4.5" // {
        dependencies = [
          sources."async-1.0.0"
        ];
      })
      sources."ws-7.4.6"
      sources."xml2js-0.4.22"
      sources."xmlbuilder-11.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
