# This file has been generated by node2nix 1.8.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "@kubernetes/client-node-0.8.2" = {
      name = "_at_kubernetes_slash_client-node";
      packageName = "@kubernetes/client-node";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@kubernetes/client-node/-/client-node-0.8.2.tgz";
        sha512 = "crS3h59+fOGXQgxVdq3XH81ytY7FV2HnB5z/+lSWD3bi5D5lHKu3PVN2PHCDMNExPy0KthcfqBoIVFVy4CoG3A==";
      };
    };
    "@types/caseless-0.12.2" = {
      name = "_at_types_slash_caseless";
      packageName = "@types/caseless";
      version = "0.12.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/caseless/-/caseless-0.12.2.tgz";
        sha512 = "6ckxMjBBD8URvjB6J3NcnuAn5Pkl7t3TizAg+xdlzzQGSPSmBcXf8KoIH0ua/i+tio+ZRUHEXp0HEmvaR4kt0w==";
      };
    };
    "@types/js-yaml-3.12.1" = {
      name = "_at_types_slash_js-yaml";
      packageName = "@types/js-yaml";
      version = "3.12.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/js-yaml/-/js-yaml-3.12.1.tgz";
        sha512 = "SGGAhXLHDx+PK4YLNcNGa6goPf9XRWQNAUUbffkwVGGXIxmDKWyGGL4inzq2sPmExu431Ekb9aEMn9BkPqEYFA==";
      };
    };
    "@types/node-10.14.20" = {
      name = "_at_types_slash_node";
      packageName = "@types/node";
      version = "10.14.20";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/node/-/node-10.14.20.tgz";
        sha512 = "An+MXSV8CGXz/BO9C1KKsoJ/8WDrvlNUaRMsm2h+IHZuSyQkM8U5bJJkb8ItLKA73VePG/nUK+t+EuW2IWuhsQ==";
      };
    };
    "@types/request-2.48.3" = {
      name = "_at_types_slash_request";
      packageName = "@types/request";
      version = "2.48.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/request/-/request-2.48.3.tgz";
        sha512 = "3Wo2jNYwqgXcIz/rrq18AdOZUQB8cQ34CXZo+LUwPJNpvRAL86+Kc2wwI8mqpz9Cr1V+enIox5v+WZhy/p3h8w==";
      };
    };
    "@types/tough-cookie-2.3.5" = {
      name = "_at_types_slash_tough-cookie";
      packageName = "@types/tough-cookie";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/tough-cookie/-/tough-cookie-2.3.5.tgz";
        sha512 = "SCcK7mvGi3+ZNz833RRjFIxrn4gI1PPR3NtuIS+6vMkvmsGjosqTJwRt5bAEFLRz+wtJMWv8+uOnZf2hi2QXTg==";
      };
    };
    "@types/underscore-1.9.3" = {
      name = "_at_types_slash_underscore";
      packageName = "@types/underscore";
      version = "1.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/underscore/-/underscore-1.9.3.tgz";
        sha512 = "SwbHKB2DPIDlvYqtK5O+0LFtZAyrUSw4c0q+HWwmH1Ve3KMQ0/5PlV3RX97+3dP7yMrnNQ8/bCWWvQpPl03Mug==";
      };
    };
    "@types/ws-6.0.3" = {
      name = "_at_types_slash_ws";
      packageName = "@types/ws";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/ws/-/ws-6.0.3.tgz";
        sha512 = "yBTM0P05Tx9iXGq00BbJPo37ox68R5vaGTXivs6RGh/BQ6QP5zqZDGWdAO6JbRE/iR1l80xeGAwCQS2nMV9S/w==";
      };
    };
    "JSONStream-0.10.0" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "0.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-0.10.0.tgz";
        sha1 = "74349d0d89522b71f30f0a03ff9bd20ca6f12ac0";
      };
    };
    "abort-controller-3.0.0" = {
      name = "abort-controller";
      packageName = "abort-controller";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/abort-controller/-/abort-controller-3.0.0.tgz";
        sha512 = "h8lQ8tacZYnR3vNQTgibj+tODHI5/+l06Au2Pcriv/Gmet0eaj4TwWH41sO9wnHDiQsEj19q0drzdWdeAHtweg==";
      };
    };
    "agent-base-4.3.0" = {
      name = "agent-base";
      packageName = "agent-base";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/agent-base/-/agent-base-4.3.0.tgz";
        sha512 = "salcGninV0nPrwpGNn4VTXBb1SOuXQBiqbrNXoeizJsHrsL6ERFM2Ne3JUSBWRE6aeNJI2ROP/WEEIDUiDe3cg==";
      };
    };
    "ajv-6.10.2" = {
      name = "ajv";
      packageName = "ajv";
      version = "6.10.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-6.10.2.tgz";
        sha512 = "TXtUUEYHuaTEbLZWIKUr5pmBuhDLy+8KYtPYdcV8qC+pOZL+NKqYwvWSRrVXHn+ZmRRAu8vJTAznH7Oag6RVRw==";
      };
    };
    "argparse-1.0.10" = {
      name = "argparse";
      packageName = "argparse";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-1.0.10.tgz";
        sha512 = "o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==";
      };
    };
    "arrify-2.0.1" = {
      name = "arrify";
      packageName = "arrify";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/arrify/-/arrify-2.0.1.tgz";
        sha512 = "3duEwti880xqi4eAMN8AyR4a0ByT90zoYdLlevfrvU43vb0YZwZVfxOgxWrLXXXpyugL0hNZc9G6BiB5B3nUug==";
      };
    };
    "asap-2.0.6" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.6.tgz";
        sha1 = "e50347611d7e690943208bbdafebcbc2fb866d46";
      };
    };
    "asn1-0.2.4" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.4.tgz";
        sha512 = "jxwzQpLQjSmWXgwaCZE9Nz+glAG01yF1QnWgbhGwHI5A6FRIEY6IVqtHhIepHqI7/kyEyQEagBC5mBEFlIYvdg==";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "async-1.0.0" = {
      name = "async";
      packageName = "async";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-1.0.0.tgz";
        sha1 = "f8fc04ca3a13784ade9e1641af98578cfbd647a9";
      };
    };
    "async-2.6.3" = {
      name = "async";
      packageName = "async";
      version = "2.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.6.3.tgz";
        sha512 = "zflvls11DCy+dQWzTW2dzuilv8Z5X/pjfmZOWba6TNIVDm+2UDaJmXSOXlasHKfNBs8oo3M0aT50fDEWfKZjXg==";
      };
    };
    "async-limiter-1.0.1" = {
      name = "async-limiter";
      packageName = "async-limiter";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-limiter/-/async-limiter-1.0.1.tgz";
        sha512 = "csOlWGAcRFJaI6m+F2WKdnMKr4HhdhFVBk0H/QbJFMCr+uO2kwohwXQPxw/9OCxp05r5ghVBFSyioixx3gfkNQ==";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "aws-sign2-0.7.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.7.0.tgz";
        sha1 = "b46e890934a9591f2d2f6f86d7e6a9f1b3fe76a8";
      };
    };
    "aws4-1.8.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.8.0.tgz";
        sha512 = "ReZxvNHIOv88FlT7rxcXIIC0fPt4KZqZbOlivyWtXLt8ESx84zd3kMC6iK5jVeS2qt+g7ftS7ye4fi06X5rtRQ==";
      };
    };
    "backoff-2.3.0" = {
      name = "backoff";
      packageName = "backoff";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/backoff/-/backoff-2.3.0.tgz";
        sha1 = "ee7c7e38093f92e472859db635e7652454fc21ea";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "base64-js-1.3.1" = {
      name = "base64-js";
      packageName = "base64-js";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/base64-js/-/base64-js-1.3.1.tgz";
        sha512 = "mLQ4i2QO1ytvGWFWmcngKO//JXAQueZvwEKtjgQFM4jIK0kU+ytMfplL8j+n5mspOfjHwoAg+9yhb7BwAHm36g==";
      };
    };
    "bbb-promise-1.2.0" = {
      name = "bbb-promise";
      packageName = "bbb-promise";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/bbb-promise/-/bbb-promise-1.2.0.tgz";
        sha512 = "Ox+L3yDXiRk+Our/cEKndKkGEIJbWxa7cvgx5rWLZy9qrz33xd9nFTQnD4+C6KM+AFAhwWpLJ3iM8xDX8hAyxQ==";
      };
    };
    "bcrypt-pbkdf-1.0.2" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.2.tgz";
        sha1 = "a4301d389b6a43f9b67ff3ca11a3f6637e360e9e";
      };
    };
    "bignumber.js-7.2.1" = {
      name = "bignumber.js";
      packageName = "bignumber.js";
      version = "7.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bignumber.js/-/bignumber.js-7.2.1.tgz";
        sha512 = "S4XzBk5sMB+Rcb/LNcpzXr57VRTxgAvaAEDAl1AwRx27j00hT84O6OkteE7u8UB3NuaaygCRrEpqox4uDOrbdQ==";
      };
    };
    "bluebird-3.7.1" = {
      name = "bluebird";
      packageName = "bluebird";
      version = "3.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bluebird/-/bluebird-3.7.1.tgz";
        sha512 = "DdmyoGCleJnkbp3nkbxTLJ18rjDsE4yCggEwKNXkeV123sPNfOCYeDoeuOY+F2FrSjO1YXcTU+dsy96KMy+gcg==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "buffer-equal-constant-time-1.0.1" = {
      name = "buffer-equal-constant-time";
      packageName = "buffer-equal-constant-time";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-equal-constant-time/-/buffer-equal-constant-time-1.0.1.tgz";
        sha1 = "f8e71132f7ffe6e01a5c9697a4c6f3e48d5cc819";
      };
    };
    "bufferutil-4.0.1" = {
      name = "bufferutil";
      packageName = "bufferutil";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bufferutil/-/bufferutil-4.0.1.tgz";
        sha512 = "xowrxvpxojqkagPcWRQVXZl0YXhRhAtBEIq3VoER1NH5Mw1n1o0ojdspp+GS2J//2gCVyrzQDApQ4unGF+QOoA==";
      };
    };
    "build-url-1.3.3" = {
      name = "build-url";
      packageName = "build-url";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/build-url/-/build-url-1.3.3.tgz";
        sha512 = "uSC8d+d4SlbXTu/9nBhwEKi33CE0KQgCvfy8QwyrrO5vCuXr9hN021ZBh8ip5vxPbMOrZiPwgqcupuhezxiP3g==";
      };
    };
    "byline-5.0.0" = {
      name = "byline";
      packageName = "byline";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/byline/-/byline-5.0.0.tgz";
        sha1 = "741c5216468eadc457b03410118ad77de8c1ddb1";
      };
    };
    "caseless-0.12.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.12.0.tgz";
        sha1 = "1b681c21ff84033c826543090689420d187151dc";
      };
    };
    "charenc-0.0.2" = {
      name = "charenc";
      packageName = "charenc";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/charenc/-/charenc-0.0.2.tgz";
        sha1 = "c0a1d2f3a7092e03774bfa83f14c0fc5790a8667";
      };
    };
    "colors-1.0.3" = {
      name = "colors";
      packageName = "colors";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-1.0.3.tgz";
        sha1 = "0433f44d809680fdeb60ed260f1b0c262e82a40b";
      };
    };
    "combined-stream-1.0.8" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.8.tgz";
        sha512 = "FQN4MRfuJeHf7cBbBMJFXhKSDq+2kAArBlmRBvcvFE5BB1HZKXtSFASDhdlz9zOYwxh8lDdnvmMOe/+5cdoEdg==";
      };
    };
    "commander-2.1.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.1.0.tgz";
        sha1 = "d121bbae860d9992a3d517ba96f56588e47c6781";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "config-1.30.0" = {
      name = "config";
      packageName = "config";
      version = "1.30.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/config/-/config-1.30.0.tgz";
        sha1 = "1d60a9f35348a13c175798d384e81a5a16c3ba6e";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "crypt-0.0.2" = {
      name = "crypt";
      packageName = "crypt";
      version = "0.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/crypt/-/crypt-0.0.2.tgz";
        sha1 = "88d7ff7ec0dfb86f713dc87bbb42d044d3e6c41b";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "debug-2.6.9" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.9.tgz";
        sha512 = "bC7ElrdJaJnPbAP+1EotYvqZsb3ecl5wi6Bfi6BJTUcNowp6cvspg0jXznRTKDjm/E7AdgFBVeAPVMNcKGsHMA==";
      };
    };
    "debug-3.2.6" = {
      name = "debug";
      packageName = "debug";
      version = "3.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-3.2.6.tgz";
        sha512 = "mel+jf7nrtEl5Pn1Qx46zARXKDpBbvzezse7p7LqINmdoIk8PYP5SySaxEmYv6TZ0JyEKA1hsCId6DIhgITtWQ==";
      };
    };
    "deep-is-0.1.3" = {
      name = "deep-is";
      packageName = "deep-is";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/deep-is/-/deep-is-0.1.3.tgz";
        sha1 = "b369d6fb5dbc13eecf524f91b070feedc357cf34";
      };
    };
    "define-properties-1.1.3" = {
      name = "define-properties";
      packageName = "define-properties";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/define-properties/-/define-properties-1.1.3.tgz";
        sha512 = "3MqfYKj2lLzdMSf8ZIZE/V+Zuy+BgD6f164e8K2w7dgnpKArBDerGYpM46IYYcjnkdPNMjPk9A6VFB8+3SKlXQ==";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "docker-modem-0.3.7" = {
      name = "docker-modem";
      packageName = "docker-modem";
      version = "0.3.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/docker-modem/-/docker-modem-0.3.7.tgz";
        sha1 = "3f510d09f5d334dc2134228f92bd344671227df4";
      };
    };
    "double-ended-queue-2.1.0-0" = {
      name = "double-ended-queue";
      packageName = "double-ended-queue";
      version = "2.1.0-0";
      src = fetchurl {
        url = "https://registry.npmjs.org/double-ended-queue/-/double-ended-queue-2.1.0-0.tgz";
        sha1 = "103d3527fd31528f40188130c841efdd78264e5c";
      };
    };
    "ecc-jsbn-0.1.2" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.2.tgz";
        sha1 = "3a83a904e54353287874c564b7549386849a98c9";
      };
    };
    "ecdsa-sig-formatter-1.0.11" = {
      name = "ecdsa-sig-formatter";
      packageName = "ecdsa-sig-formatter";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecdsa-sig-formatter/-/ecdsa-sig-formatter-1.0.11.tgz";
        sha512 = "nagl3RYrbNv6kQkeJIpt6NJZy8twLB/2vtz6yN9Z4vRKHN4/QZJIEbqohALSgwKdnksuY3k5Addp5lg8sVoVcQ==";
      };
    };
    "error-tojson-0.0.1" = {
      name = "error-tojson";
      packageName = "error-tojson";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/error-tojson/-/error-tojson-0.0.1.tgz";
        sha1 = "a7b1aa94ffc00e9078c2eba26e204bd87cf2cbb9";
      };
    };
    "es-abstract-1.15.0" = {
      name = "es-abstract";
      packageName = "es-abstract";
      version = "1.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-abstract/-/es-abstract-1.15.0.tgz";
        sha512 = "bhkEqWJ2t2lMeaJDuk7okMkJWI/yqgH/EoGwpcvv0XW9RWQsRspI4wt6xuyuvMvvQE3gg/D9HXppgk21w78GyQ==";
      };
    };
    "es-to-primitive-1.2.0" = {
      name = "es-to-primitive";
      packageName = "es-to-primitive";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es-to-primitive/-/es-to-primitive-1.2.0.tgz";
        sha512 = "qZryBOJjV//LaxLTV6UC//WewneB3LcXOL9NP++ozKVXsIIIpm/2c13UDiD9Jp2eThsecw9m3jPqDwTyobcdbg==";
      };
    };
    "es6-promise-4.2.8" = {
      name = "es6-promise";
      packageName = "es6-promise";
      version = "4.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promise/-/es6-promise-4.2.8.tgz";
        sha512 = "HJDGx5daxeIvxdBxvG2cb9g4tEvwIk3i8+nhX0yGrYmZUzbkdg8QbDevheDB8gd0//uPj4c1EQua8Q+MViT0/w==";
      };
    };
    "es6-promisify-5.0.0" = {
      name = "es6-promisify";
      packageName = "es6-promisify";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-promisify/-/es6-promisify-5.0.0.tgz";
        sha1 = "5109d62f3e56ea967c4b63505aef08291c8a5203";
      };
    };
    "escodegen-1.12.0" = {
      name = "escodegen";
      packageName = "escodegen";
      version = "1.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escodegen/-/escodegen-1.12.0.tgz";
        sha512 = "TuA+EhsanGcme5T3R0L80u4t8CpbXQjegRmf7+FPTJrtCTErXFeelblRgHQa1FofEzqYYJmJ/OqjTwREp9qgmg==";
      };
    };
    "esprima-1.2.2" = {
      name = "esprima";
      packageName = "esprima";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-1.2.2.tgz";
        sha1 = "76a0fd66fcfe154fd292667dc264019750b1657b";
      };
    };
    "esprima-3.1.3" = {
      name = "esprima";
      packageName = "esprima";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-3.1.3.tgz";
        sha1 = "fdca51cee6133895e3c88d535ce49dbff62a4633";
      };
    };
    "esprima-4.0.1" = {
      name = "esprima";
      packageName = "esprima";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/esprima/-/esprima-4.0.1.tgz";
        sha512 = "eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==";
      };
    };
    "estraverse-4.3.0" = {
      name = "estraverse";
      packageName = "estraverse";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estraverse/-/estraverse-4.3.0.tgz";
        sha512 = "39nnKffWz8xN1BU/2c79n9nB9HDzo0niYUqx6xyqUnyoAnQyyWpOTdZEeiCch8BBu515t4wp9ZmgVfVhn9EBpw==";
      };
    };
    "esutils-2.0.3" = {
      name = "esutils";
      packageName = "esutils";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/esutils/-/esutils-2.0.3.tgz";
        sha512 = "kVscqXk4OCp68SZ0dkgEKVi6/8ij300KBWTJq32P/dYeWTSwK41WyTxalN1eRmA5Z9UU/LX9D7FWSmV9SAYx6g==";
      };
    };
    "event-target-shim-5.0.1" = {
      name = "event-target-shim";
      packageName = "event-target-shim";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/event-target-shim/-/event-target-shim-5.0.1.tgz";
        sha512 = "i/2XbnSz/uxRCU6+NdVJgKWDTM427+MqYbkQzD321DuCQJUqOuJKIA0IM2+W2xtYHdKOmZ4dR6fExsd4SXL+WQ==";
      };
    };
    "eventemitter2-4.1.2" = {
      name = "eventemitter2";
      packageName = "eventemitter2";
      version = "4.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/eventemitter2/-/eventemitter2-4.1.2.tgz";
        sha1 = "0e1a8477af821a6ef3995b311bf74c23a5247f15";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "extsprintf-1.3.0" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.3.0.tgz";
        sha1 = "96918440e3041a7a414f8c52e3c574eb3c3e1e05";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "fast-deep-equal-2.0.1" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-2.0.1.tgz";
        sha1 = "7b05218ddf9667bf7f370bf7fdb2cb15fdd0aa49";
      };
    };
    "fast-json-stable-stringify-2.0.0" = {
      name = "fast-json-stable-stringify";
      packageName = "fast-json-stable-stringify";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-json-stable-stringify/-/fast-json-stable-stringify-2.0.0.tgz";
        sha1 = "d5142c0caee6b1189f87d3a76111064f86c8bbf2";
      };
    };
    "fast-levenshtein-2.0.6" = {
      name = "fast-levenshtein";
      packageName = "fast-levenshtein";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-levenshtein/-/fast-levenshtein-2.0.6.tgz";
        sha1 = "3d8a5c66883a16a30ca8643e851f19baa7797917";
      };
    };
    "fast-text-encoding-1.0.0" = {
      name = "fast-text-encoding";
      packageName = "fast-text-encoding";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-text-encoding/-/fast-text-encoding-1.0.0.tgz";
        sha512 = "R9bHCvweUxxwkDwhjav5vxpFvdPGlVngtqmx4pIZfSUhM/Q4NiIUHB456BAf+Q1Nwu3HEZYONtu+Rya+af4jiQ==";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.3.3" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.3.3.tgz";
        sha512 = "1lLKB2Mu3aGP1Q/2eCOx0fNbRMe7XdwktwOruhfqqd0rIJWwN4Dh+E3hrPSlDCXnSR7UtZ1N38rVXm+6+MEhJQ==";
      };
    };
    "form-data-2.5.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.5.1.tgz";
        sha512 = "m21N3WOmEEURgk6B9GLOE4RuWOFf28Lhh9qGYeNlGq4VDXUlJy2th2slBNU8Gp8EzloYZOibZJ7t5ecIrFSjVA==";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "function-bind-1.1.1" = {
      name = "function-bind";
      packageName = "function-bind";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/function-bind/-/function-bind-1.1.1.tgz";
        sha512 = "yIovAzMX49sF8Yl58fSCWJ5svSLuaibPxXQJFLmBObTuCr0Mf1KiPopGM9NiFjiYBCbfaa2Fh6breQ6ANVTI0A==";
      };
    };
    "gaxios-2.1.0" = {
      name = "gaxios";
      packageName = "gaxios";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gaxios/-/gaxios-2.1.0.tgz";
        sha512 = "Gtpb5sdQmb82sgVkT2GnS2n+Kx4dlFwbeMYcDlD395aEvsLCSQXJJcHt7oJ2LrGxDEAeiOkK79Zv2A8Pzt6CFg==";
      };
    };
    "gcp-metadata-3.2.0" = {
      name = "gcp-metadata";
      packageName = "gcp-metadata";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gcp-metadata/-/gcp-metadata-3.2.0.tgz";
        sha512 = "ympv+yQ6k5QuWCuwQqnGEvFGS7MBKdcQdj1i188v3bW9QLFIchTGaBCEZxSQapT0jffdn1vdt8oJhB5VBWQO1Q==";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "glob-7.1.4" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.4.tgz";
        sha512 = "hkLPepehmnKk41pUGm3sYxoFs/umurYfYJCerbXEyFIWcAzvpipAgVkBqqT9RBKMGjnq6kMuyYwha6csxbiM1A==";
      };
    };
    "google-auth-library-5.5.0" = {
      name = "google-auth-library";
      packageName = "google-auth-library";
      version = "5.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/google-auth-library/-/google-auth-library-5.5.0.tgz";
        sha512 = "TNeraw4miu6/FhO0jDrHiJuRx3SBrAhxHSPj7+rhif43bKE34UItXX9lejKxo3E8FNytuY4LIVIvpcqMQHSYZw==";
      };
    };
    "google-p12-pem-2.0.2" = {
      name = "google-p12-pem";
      packageName = "google-p12-pem";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/google-p12-pem/-/google-p12-pem-2.0.2.tgz";
        sha512 = "UfnEARfJKI6pbmC1hfFFm+UAcZxeIwTiEcHfqKe/drMsXD/ilnVjF7zgOGpHXyhuvX6jNJK3S8A0hOQjwtFxEw==";
      };
    };
    "googleapis-43.0.0" = {
      name = "googleapis";
      packageName = "googleapis";
      version = "43.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/googleapis/-/googleapis-43.0.0.tgz";
        sha512 = "4b38mlTdDCA3KiyRTQmfPpeTxznC5ufgqx3AvKaEIoVm+iWeVLfwYs++/+OcGJJriH9bcs0gPbU7CR8DU6Oevg==";
      };
    };
    "googleapis-common-3.1.1" = {
      name = "googleapis-common";
      packageName = "googleapis-common";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/googleapis-common/-/googleapis-common-3.1.1.tgz";
        sha512 = "sXNS9oJifZOk2Pa6SzxoSfv0Mj9y/qIOsVV7D8WHuH//90CXNnpR/nCYVa+KcPMDT9ONq21sbtvjfKATMV1Bug==";
      };
    };
    "gtoken-4.1.0" = {
      name = "gtoken";
      packageName = "gtoken";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/gtoken/-/gtoken-4.1.0.tgz";
        sha512 = "wqyn2gf5buzEZN4QNmmiiW2i2JkEdZnL7Z/9p44RtZqgt4077m4khRgAYNuu8cBwHWCc6MsP6eDUn/KkF6jFIw==";
      };
    };
    "har-schema-2.0.0" = {
      name = "har-schema";
      packageName = "har-schema";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-schema/-/har-schema-2.0.0.tgz";
        sha1 = "a94c2224ebcac04782a0d9035521f24735b7ec92";
      };
    };
    "har-validator-5.1.3" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "5.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-5.1.3.tgz";
        sha512 = "sNvOCzEQNr/qrvJgc3UG/kD4QtlHycrzwS+6mfTrrSq97BvaYcPZZI1ZSqGSPR73Cxn4LKTD4PttRwfU7jWq5g==";
      };
    };
    "has-1.0.3" = {
      name = "has";
      packageName = "has";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/has/-/has-1.0.3.tgz";
        sha512 = "f2dvO0VU6Oej7RkWJGrehjbzMAjFp5/VKPp5tTpWIV4JHHZK1/BxbFRtf/siA2SWTe09caDmVtYYzWEIbBS4zw==";
      };
    };
    "has-symbols-1.0.0" = {
      name = "has-symbols";
      packageName = "has-symbols";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-symbols/-/has-symbols-1.0.0.tgz";
        sha1 = "ba1a8f1af2a0fc39650f5c850367704122063b44";
      };
    };
    "http-signature-1.2.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.2.0.tgz";
        sha1 = "9aecd925114772f3d95b65a60abb8f7c18fbace1";
      };
    };
    "https-proxy-agent-3.0.0" = {
      name = "https-proxy-agent";
      packageName = "https-proxy-agent";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/https-proxy-agent/-/https-proxy-agent-3.0.0.tgz";
        sha512 = "y4jAxNEihqvBI5F3SaO2rtsjIOnnNA8sEbuiP+UhJZJHeM2NRm6c09ax2tgqme+SgUUvjao2fJXF4h3D6Cb2HQ==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "interpret-1.2.0" = {
      name = "interpret";
      packageName = "interpret";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/interpret/-/interpret-1.2.0.tgz";
        sha512 = "mT34yGKMNceBQUoVn7iCDKDntA7SC6gycMAWzGx1z/CMCTV7b2AAtXlo3nRyHZ1FelRkQbQjprHSYGwzLtkVbw==";
      };
    };
    "ipaddr.js-1.9.1" = {
      name = "ipaddr.js";
      packageName = "ipaddr.js";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ipaddr.js/-/ipaddr.js-1.9.1.tgz";
        sha512 = "0KI/607xoxSToH7GjN1FfSbLoU0+btTicjsQSWQlh/hZykN8KpmMf7uYwPW3R+akZ6R/w18ZlXSHBYXiYUPO3g==";
      };
    };
    "is-callable-1.1.4" = {
      name = "is-callable";
      packageName = "is-callable";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-callable/-/is-callable-1.1.4.tgz";
        sha512 = "r5p9sxJjYnArLjObpjA4xu5EKI3CuKHkJXMhT7kwbpUyIFD1n5PMAsoPvWnvtZiNz7LjkYDRZhd7FlI0eMijEA==";
      };
    };
    "is-date-object-1.0.1" = {
      name = "is-date-object";
      packageName = "is-date-object";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-date-object/-/is-date-object-1.0.1.tgz";
        sha1 = "9aa20eb6aeebbff77fbd33e74ca01b33581d3a16";
      };
    };
    "is-regex-1.0.4" = {
      name = "is-regex";
      packageName = "is-regex";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-regex/-/is-regex-1.0.4.tgz";
        sha1 = "5517489b547091b0930e095654ced25ee97e9491";
      };
    };
    "is-stream-2.0.0" = {
      name = "is-stream";
      packageName = "is-stream";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-stream/-/is-stream-2.0.0.tgz";
        sha512 = "XCoy+WlUr7d1+Z8GgSuXmpuUFC9fOhRXglJMx+dwLKTkL44Cjd4W1Z5P+BQZpr+cR93aGP4S/s7Ftw6Nd/kiEw==";
      };
    };
    "is-symbol-1.0.2" = {
      name = "is-symbol";
      packageName = "is-symbol";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-symbol/-/is-symbol-1.0.2.tgz";
        sha512 = "HS8bZ9ox60yCJLH9snBpIwv9pYUAkcuLhSA1oero1UB5y9aiQpRA8y2ex945AOtCZL1lJDeIk3G5LthswI46Lw==";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "isbuffer-0.0.0" = {
      name = "isbuffer";
      packageName = "isbuffer";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isbuffer/-/isbuffer-0.0.0.tgz";
        sha1 = "38c146d9df528b8bf9b0701c3d43cf12df3fc39b";
      };
    };
    "isomorphic-ws-4.0.1" = {
      name = "isomorphic-ws";
      packageName = "isomorphic-ws";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isomorphic-ws/-/isomorphic-ws-4.0.1.tgz";
        sha512 = "BhBvN2MBpWTaSHdWRb/bwdZJ1WaehQ2L1KngkCkfLUGF0mAWAT1sQUQacEmQ0jXkFw/czDXPNQSL5u2/Krsz1w==";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "js-yaml-3.13.1" = {
      name = "js-yaml";
      packageName = "js-yaml";
      version = "3.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/js-yaml/-/js-yaml-3.13.1.tgz";
        sha512 = "YfbcO7jXDdyj0DGxYVSlSeQNHbD7XPWvrVWeVUujrQEoZzWJIRrCPoyk6kL6IAjAG2IolMK4T0hNUe0HOUs5Jw==";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "json-bigint-0.3.0" = {
      name = "json-bigint";
      packageName = "json-bigint";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-bigint/-/json-bigint-0.3.0.tgz";
        sha1 = "0ccd912c4b8270d05f056fbd13814b53d3825b1e";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "json-schema-traverse-0.4.1" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-0.4.1.tgz";
        sha512 = "xbbCH5dCYU5T8LcEhhuh7HJ88HXuW3qsI3Y0zOZFKfZEHcpWiHU/Jxzk629Brsab/mMiHQti9wMP+845RPe3Vg==";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "json5-0.4.0" = {
      name = "json5";
      packageName = "json5";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json5/-/json5-0.4.0.tgz";
        sha1 = "054352e4c4c80c86c0923877d449de176a732c8d";
      };
    };
    "jsonparse-0.0.5" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-0.0.5.tgz";
        sha1 = "330542ad3f0a654665b778f3eb2d9a9fa507ac64";
      };
    };
    "jsonpath-1.0.2" = {
      name = "jsonpath";
      packageName = "jsonpath";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpath/-/jsonpath-1.0.2.tgz";
        sha512 = "rmzlgFZiQPc6q4HDyK8s9Qb4oxBnI5sF61y/Co5PV0lc3q2bIuRsNdueVbhoSHdKM4fxeimphOAtfz47yjCfeA==";
      };
    };
    "jsprim-1.4.1" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.1.tgz";
        sha1 = "313e66bc1e5cc06e438bc1b7499c2e5c56acb6a2";
      };
    };
    "jwa-1.4.1" = {
      name = "jwa";
      packageName = "jwa";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jwa/-/jwa-1.4.1.tgz";
        sha512 = "qiLX/xhEEFKUAJ6FiBMbes3w9ATzyk5W7Hvzpa/SLYdxNtng+gcurvrI7TbACjIXlsJyr05/S1oUhZrc63evQA==";
      };
    };
    "jws-3.2.2" = {
      name = "jws";
      packageName = "jws";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jws/-/jws-3.2.2.tgz";
        sha512 = "YHlZCB6lMTllWDtSPHz/ZXTsi8S00usEV6v1tjq8tOUZzw7DpSDWVXjXDre6ed1w/pd495ODpHZYSdkRTsa0HA==";
      };
    };
    "kurento-client-core-6.13.0" = {
      name = "kurento-client-core";
      packageName = "kurento-client-core";
      version = "6.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kurento-client-core/-/kurento-client-core-6.13.0.tgz";
        sha512 = "ox8FiQ28L5wjc7lGfdMVpXy4HsLn1dK5pFn79sshUB817qQaWewLLNtAt9D00B0nSfzCqqRio178u1l/0M7+wA==";
      };
    };
    "kurento-client-elements-6.13.0" = {
      name = "kurento-client-elements";
      packageName = "kurento-client-elements";
      version = "6.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kurento-client-elements/-/kurento-client-elements-6.13.0.tgz";
        sha512 = "iiAbe1Ts5Xp5NXWgmyQour9UYzPiCpLGG0drLhLGwpeWn8lbkJneYAsI2GG8tXlxVJTi9Uxv4FLwniO+26+lwg==";
      };
    };
    "kurento-client-filters-6.13.0" = {
      name = "kurento-client-filters";
      packageName = "kurento-client-filters";
      version = "6.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kurento-client-filters/-/kurento-client-filters-6.13.0.tgz";
        sha512 = "hpM57St5VvRT+c2pv7DE/rTo3d1QayTdCWTqICR/6OtbRgP/rmP+eGY2LmqO/OpR+t2Koz4fzLcLMII03UZ16Q==";
      };
    };
    "kurento-client-git+https://github.com/Kurento/kurento-client-js.git#da7b2f6433d52eb8689e65e8e6e3990b90dc40a1" = {
      name = "kurento-client";
      packageName = "kurento-client";
      version = "6.13.0";
      src = fetchgit {
        url = "https://github.com/Kurento/kurento-client-js.git";
        rev = "da7b2f6433d52eb8689e65e8e6e3990b90dc40a1";
        sha256 = "bd0eaa0460ef4c87c74327a3667d245dfff550e8ff78c5bb65c6c48b1cded0c9";
      };
    };
    "kurento-jsonrpc-6.13.0" = {
      name = "kurento-jsonrpc";
      packageName = "kurento-jsonrpc";
      version = "6.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/kurento-jsonrpc/-/kurento-jsonrpc-6.13.0.tgz";
        sha512 = "irHHeXGtEwc/0UNNmUtFl480enC8m6W1x6F/MEeMmb8DAsxWO9NOvp2E0ZScqYZomPx+K63kqoLGF619bV4J5w==";
      };
    };
    "levn-0.3.0" = {
      name = "levn";
      packageName = "levn";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/levn/-/levn-0.3.0.tgz";
        sha1 = "3b09924edf9f083c0490fdd4c0bc4421e04764ee";
      };
    };
    "lodash-4.17.15" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.15.tgz";
        sha512 = "8xOcRHvCjnocdS5cpwXQXVzmmh5e5+saE2QGoeQmbKmRS6J3VQppPOIt0MnmE+4xlZoumy0GPG0D0MVIQbNA1A==";
      };
    };
    "lru-cache-5.1.1" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "5.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-5.1.1.tgz";
        sha512 = "KpNARQA3Iwv+jTA0utUVVbrh+Jlrr1Fv0e56GGzAFOXN7dk/FviaDW8LHmK52DlcH4WP2n6gI8vN1aesBFgo9w==";
      };
    };
    "mcs-js-git+https://github.com/mconftec/mcs-js.git#94292a211164704f850128e95602d6d99056bf55" = {
      name = "mcs-js";
      packageName = "mcs-js";
      version = "0.0.9";
      src = fetchgit {
        url = "https://github.com/mconftec/mcs-js.git";
        rev = "94292a211164704f850128e95602d6d99056bf55";
        sha256 = "e12c87f756cd60a319f412d9d7a74c29faff30ebe235cae888cbd07020ea0acb";
      };
    };
    "memorystream-0.3.1" = {
      name = "memorystream";
      packageName = "memorystream";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/memorystream/-/memorystream-0.3.1.tgz";
        sha1 = "86d7090b30ce455d63fbae12dda51a47ddcaf9b2";
      };
    };
    "mime-2.4.4" = {
      name = "mime";
      packageName = "mime";
      version = "2.4.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime/-/mime-2.4.4.tgz";
        sha512 = "LRxmNwziLPT828z+4YkNzloCFC2YM4wrB99k+AV5ZbEyfGNWfG8SO1FUXLmLDBSo89NrJZ4DIWeLjy1CHGhMGA==";
      };
    };
    "mime-db-1.40.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.40.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.40.0.tgz";
        sha512 = "jYdeOMPy9vnxEqFRRo6ZvTZ8d9oPb+k18PKoYNYUe2stVEBPPwsln/qWzdbmaIvnhZ9v2P+CuecK+fpUfsV2mA==";
      };
    };
    "mime-types-2.1.24" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.24";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.24.tgz";
        sha512 = "WaFHS3MCl5fapm3oLxU4eYDw77IQM2ACcxQ9RIxfaC3ooc6PFuBMGZZsYpvoXS5D5QTWPieo1jjLdAm3TBP3cQ==";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "modesl-1.2.1" = {
      name = "modesl";
      packageName = "modesl";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/modesl/-/modesl-1.2.1.tgz";
        sha512 = "B4ROC+xyZ9guF91dYSMQFLccHogjbMOA5Z3z17DLX1i2Dx8H+fIrTfoc1LWLAltqGf0WlnXZoosbC8BEPYY31w==";
      };
    };
    "ms-2.0.0" = {
      name = "ms";
      packageName = "ms";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.0.0.tgz";
        sha1 = "5608aeadfc00be6c2901df5f9861788de0d597c8";
      };
    };
    "ms-2.1.2" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.2.tgz";
        sha512 = "sGkPx+VjMtmA6MX27oA4FBFELFCZZ4S4XqeGOXCv68tT+jb3vk/RyaKWP0PTKyWtmLSM0b+adUTEvbs1PEaH2w==";
      };
    };
    "nan-1.0.0" = {
      name = "nan";
      packageName = "nan";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-1.0.0.tgz";
        sha1 = "ae24f8850818d662fcab5acf7f3b95bfaa2ccf38";
      };
    };
    "nanoid-1.3.4" = {
      name = "nanoid";
      packageName = "nanoid";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/nanoid/-/nanoid-1.3.4.tgz";
        sha512 = "4ug4BsuHxiVHoRUe1ud6rUFT3WUMmjXt1W0quL0CviZQANdan7D8kqN5/maw53hmAApY/jfzMRkC57BNNs60ZQ==";
      };
    };
    "node-docker-api-1.1.22" = {
      name = "node-docker-api";
      packageName = "node-docker-api";
      version = "1.1.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-docker-api/-/node-docker-api-1.1.22.tgz";
        sha1 = "230327efd309a6ec7302bf3f404ab760040a5806";
      };
    };
    "node-fetch-2.6.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.6.0.tgz";
        sha512 = "8dG4H5ujfvFiqDmVu9fQ5bOHUC15JMjMY/Zumv26oOvvVJjM67KF8koCWIabKQ1GJIa9r2mMZscBq/TbdOcmNA==";
      };
    };
    "node-forge-0.9.1" = {
      name = "node-forge";
      packageName = "node-forge";
      version = "0.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-forge/-/node-forge-0.9.1.tgz";
        sha512 = "G6RlQt5Sb4GMBzXvhfkeFmbqR6MzhtnT7VTHuLadjkii3rdYHNdw0m8zA4BTxVIh68FicCQ2NSUANpsqkr9jvQ==";
      };
    };
    "node-gyp-build-3.7.0" = {
      name = "node-gyp-build";
      packageName = "node-gyp-build";
      version = "3.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp-build/-/node-gyp-build-3.7.0.tgz";
        sha512 = "L/Eg02Epx6Si2NXmedx+Okg+4UHqmaf3TNcxd50SF9NQGcJaON3AtU++kax69XV7YWz4tUspqZSAsVofhFKG2w==";
      };
    };
    "oauth-sign-0.9.0" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.9.0.tgz";
        sha512 = "fexhUFFPTGV8ybAtSIGbV6gOkSv8UtRbDBnAyLQw4QPKkgNlsH2ByPGtMUqdWkos6YCRmAqViwgZrJc/mRDzZQ==";
      };
    };
    "object-inspect-1.6.0" = {
      name = "object-inspect";
      packageName = "object-inspect";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-inspect/-/object-inspect-1.6.0.tgz";
        sha512 = "GJzfBZ6DgDAmnuaM3104jR4s1Myxr3Y3zfIyN4z3UdqN69oSRacNK8UhnobDdC+7J2AHCjGwxQubNJfE70SXXQ==";
      };
    };
    "object-keys-1.1.1" = {
      name = "object-keys";
      packageName = "object-keys";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-keys/-/object-keys-1.1.1.tgz";
        sha512 = "NuAESUOUMrlIXOfHKzD6bpPu3tYt3xvjNdRIQ+FeT0lNb4K8WR70CaDxhuNguS2XG+GjkyMwOzsN5ZktImfhLA==";
      };
    };
    "object.getownpropertydescriptors-2.0.3" = {
      name = "object.getownpropertydescriptors";
      packageName = "object.getownpropertydescriptors";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/object.getownpropertydescriptors/-/object.getownpropertydescriptors-2.0.3.tgz";
        sha1 = "8758c846f5b407adab0f236e0986f14b051caa16";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "optionator-0.8.2" = {
      name = "optionator";
      packageName = "optionator";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/optionator/-/optionator-0.8.2.tgz";
        sha1 = "364c5e409d3f4d6301d6c0b4c05bba50180aeb64";
      };
    };
    "options-0.0.6" = {
      name = "options";
      packageName = "options";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/options/-/options-0.0.6.tgz";
        sha1 = "ec22d312806bb53e731773e7cdaefcf1c643128f";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "path-parse-1.0.6" = {
      name = "path-parse";
      packageName = "path-parse";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-parse/-/path-parse-1.0.6.tgz";
        sha512 = "GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==";
      };
    };
    "pegjs-0.8.0" = {
      name = "pegjs";
      packageName = "pegjs";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/pegjs/-/pegjs-0.8.0.tgz";
        sha1 = "976f067da13e5c5b1501c017925668a253811561";
      };
    };
    "performance-now-2.1.0" = {
      name = "performance-now";
      packageName = "performance-now";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/performance-now/-/performance-now-2.1.0.tgz";
        sha1 = "6309f4e0e5fa913ec1c69307ae364b4b377c9e7b";
      };
    };
    "prelude-ls-1.1.2" = {
      name = "prelude-ls";
      packageName = "prelude-ls";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/prelude-ls/-/prelude-ls-1.1.2.tgz";
        sha1 = "21932a549f5e52ffd9a827f570e04be62a97da54";
      };
    };
    "promiscuous-0.6.0" = {
      name = "promiscuous";
      packageName = "promiscuous";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promiscuous/-/promiscuous-0.6.0.tgz";
        sha1 = "54014cd3d62cafe831e3354990c05ff5b78c8892";
      };
    };
    "promise-7.1.1" = {
      name = "promise";
      packageName = "promise";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/promise/-/promise-7.1.1.tgz";
        sha1 = "489654c692616b8aa55b0724fa809bb7db49c5bf";
      };
    };
    "promisecallback-0.0.4" = {
      name = "promisecallback";
      packageName = "promisecallback";
      version = "0.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/promisecallback/-/promisecallback-0.0.4.tgz";
        sha1 = "b934f13c04e443622b4d66de4e42ea5f6ce66e74";
      };
    };
    "psl-1.4.0" = {
      name = "psl";
      packageName = "psl";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/psl/-/psl-1.4.0.tgz";
        sha512 = "HZzqCGPecFLyoRj5HLfuDSKYTJkAfB5thKBIkRHtGjWwY7p1dAyveIbXIq4tO0KYfDF2tHqPUgY9SDnGm00uFw==";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "punycode-2.1.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-2.1.1.tgz";
        sha512 = "XRsRjdf+j5ml+y/6GKHPZbrF/8p2Yga0JPtdqTIY2Xe5ohJPD9saDJJLPvp9+NSBprVvevdXZybnj2cv8OEd0A==";
      };
    };
    "qs-6.5.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.5.2.tgz";
        sha512 = "N5ZAX4/LxJmF+7wN74pUD6qAh9/wnvdQcjq9TZjevvXzSUo7bfmw91saqMjzGS2xq91/odN2dW/WOl7qQHNDGA==";
      };
    };
    "qs-6.9.0" = {
      name = "qs";
      packageName = "qs";
      version = "6.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.9.0.tgz";
        sha512 = "27RP4UotQORTpmNQDX8BHPukOnBP3p1uUJY5UnDhaJB+rMt9iMsok724XL+UHU23bEFOHRMQ2ZhI99qOWUMGFA==";
      };
    };
    "readable-id-1.0.0" = {
      name = "readable-id";
      packageName = "readable-id";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-id/-/readable-id-1.0.0.tgz";
        sha512 = "RXwuv4YQNYByl+PpQVA4PR4H+aGTWOtpRx56LrxJ2Ypxf96u9WaIdKGOCqu7MPBt8iqQkYPQUk4KGbL55n78YQ==";
      };
    };
    "readable-stream-1.0.34" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.0.34";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.0.34.tgz";
        sha1 = "125820e34bc842d2f2aaafafe4c2916ee32c157c";
      };
    };
    "rechoir-0.6.2" = {
      name = "rechoir";
      packageName = "rechoir";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/rechoir/-/rechoir-0.6.2.tgz";
        sha1 = "85204b54dba82d5742e28c96756ef43af50e3384";
      };
    };
    "reconnect-core-git://github.com/kurentoforks/reconnect-core#921d43e91578abb2fb2613f585c010c1939cf734" = {
      name = "reconnect-core";
      packageName = "reconnect-core";
      version = "1.0.0";
      src = fetchgit {
        url = "git://github.com/kurentoforks/reconnect-core";
        rev = "921d43e91578abb2fb2613f585c010c1939cf734";
        sha256 = "03341b99f9373f70fee254e507357461231fa98f086cccba6bc54688cfccd6e7";
      };
    };
    "reconnect-ws-git://github.com/kurentoforks/reconnect-ws#f287385d75861654528c352e60221f95c9209f8a" = {
      name = "reconnect-ws";
      packageName = "reconnect-ws";
      version = "0.0.0";
      src = fetchgit {
        url = "git://github.com/kurentoforks/reconnect-ws";
        rev = "f287385d75861654528c352e60221f95c9209f8a";
        sha256 = "3739bfef3fea45d7c914aa5adc7111c4fd281dbe720fb3041ab1935a99c43506";
      };
    };
    "redis-2.8.0" = {
      name = "redis";
      packageName = "redis";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis/-/redis-2.8.0.tgz";
        sha512 = "M1OkonEQwtRmZv4tEWF2VgpG0JWJ8Fv1PhlgT5+B+uNq2cA3Rt1Yt/ryoR+vQNOQcIEgdCdfH0jr3bDpihAw1A==";
      };
    };
    "redis-commands-1.5.0" = {
      name = "redis-commands";
      packageName = "redis-commands";
      version = "1.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-commands/-/redis-commands-1.5.0.tgz";
        sha512 = "6KxamqpZ468MeQC3bkWmCB1fp56XL64D4Kf0zJSwDZbVLLm7KFkoIcHrgRvQ+sk8dnhySs7+yBg94yIkAK7aJg==";
      };
    };
    "redis-parser-2.6.0" = {
      name = "redis-parser";
      packageName = "redis-parser";
      version = "2.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/redis-parser/-/redis-parser-2.6.0.tgz";
        sha1 = "52ed09dacac108f1a631c07e9b69941e7a19504b";
      };
    };
    "request-2.88.0" = {
      name = "request";
      packageName = "request";
      version = "2.88.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.88.0.tgz";
        sha512 = "NAqBSrijGLZdM0WZNsInLJpkJokL72XYjUpnB0iwsRgxh7dB6COrHnTBNwN0E+lHDAJzu7kLAkDeY08z2/A0hg==";
      };
    };
    "request-promise-4.2.5" = {
      name = "request-promise";
      packageName = "request-promise";
      version = "4.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-promise/-/request-promise-4.2.5.tgz";
        sha512 = "ZgnepCykFdmpq86fKGwqntyTiUrHycALuGggpyCZwMvGaZWgxW6yagT0FHkgo5LzYvOaCNvxYwWYIjevSH1EDg==";
      };
    };
    "request-promise-core-1.1.3" = {
      name = "request-promise-core";
      packageName = "request-promise-core";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-promise-core/-/request-promise-core-1.1.3.tgz";
        sha512 = "QIs2+ArIGQVp5ZYbWD5ZLCY29D5CfWizP8eWnm8FoGD1TX61veauETVQbrV60662V0oFBkrDOuaBI8XgtuyYAQ==";
      };
    };
    "resolve-1.12.0" = {
      name = "resolve";
      packageName = "resolve";
      version = "1.12.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve/-/resolve-1.12.0.tgz";
        sha512 = "B/dOmuoAik5bKcD6s6nXDCjzUKnaDvdkRyAk6rsmsKLipWj4797iothd7jmmUhWTfinVMU+wc56rYKsit2Qy4w==";
      };
    };
    "safe-buffer-5.1.2" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.1.2.tgz";
        sha512 = "Gd2UZBJDkXlY7GbJxfsE8/nvKkUEU1G38c1siN6QP6a9PT9MmHB8GnpscSmMJSoF8LOIrt8ud/wPtojys4G6+g==";
      };
    };
    "safe-buffer-5.2.0" = {
      name = "safe-buffer";
      packageName = "safe-buffer";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-buffer/-/safe-buffer-5.2.0.tgz";
        sha512 = "fZEwUGbVl7kouZs1jCdMLdt95hdIv0ZeHg6L7qPeciMZhZ+/gdesW4wgTARkrFWEpspjEATAzUGPG8N2jJiwbg==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "sax-1.2.4" = {
      name = "sax";
      packageName = "sax";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/sax/-/sax-1.2.4.tgz";
        sha512 = "NqVDv9TpANUjFm0N8uM5GxL36UgKi9/atZw+x7YFnQ8ckwFGKrl4xX4yWtrey3UJm5nP1kUbnYgLopqWNSRhWw==";
      };
    };
    "sdp-transform-2.13.0" = {
      name = "sdp-transform";
      packageName = "sdp-transform";
      version = "2.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sdp-transform/-/sdp-transform-2.13.0.tgz";
        sha512 = "3zT7pcjR090E0WCV9eOtFX06iojoNKsyMXqXs7clOs8sy+RoegR0cebmCuCrTKdY2jw1XhT9jkraygJrqAUwzA==";
      };
    };
    "sha1-1.1.1" = {
      name = "sha1";
      packageName = "sha1";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha1/-/sha1-1.1.1.tgz";
        sha1 = "addaa7a93168f393f19eb2b15091618e2700f848";
      };
    };
    "shelljs-0.8.3" = {
      name = "shelljs";
      packageName = "shelljs";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/shelljs/-/shelljs-0.8.3.tgz";
        sha512 = "fc0BKlAWiLpwZljmOvAOTE/gXawtCoNrP5oaY7KIaQbbyHeQVg01pSEuEGvGh3HEdBU4baCD7wQBwADmM/7f7A==";
      };
    };
    "sip.js-git+https://github.com/mconf/sip.js.git#587a1fc3e6e831cb954d65eb4fe2a623a02b72a8" = {
      name = "sip.js";
      packageName = "sip.js";
      version = "0.7.5";
      src = fetchgit {
        url = "https://github.com/mconf/sip.js.git";
        rev = "587a1fc3e6e831cb954d65eb4fe2a623a02b72a8";
        sha256 = "36c0e8a51b37dff2d2da457ed6179987e8945af6a44ec16d2a762616b1af8503";
      };
    };
    "source-map-0.6.1" = {
      name = "source-map";
      packageName = "source-map";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/source-map/-/source-map-0.6.1.tgz";
        sha512 = "UjgapumWlbMhkBgzT7Ykc5YXUT46F0iKu8SGXq0bcwP5dz/h0Plj6enJqjz1Zbq2l5WaqYnrVbwWOWMyF3F47g==";
      };
    };
    "split-ca-1.0.1" = {
      name = "split-ca";
      packageName = "split-ca";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/split-ca/-/split-ca-1.0.1.tgz";
        sha1 = "6c83aff3692fa61256e0cd197e05e9de157691a6";
      };
    };
    "sprintf-js-1.0.3" = {
      name = "sprintf-js";
      packageName = "sprintf-js";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sprintf-js/-/sprintf-js-1.0.3.tgz";
        sha1 = "04e6926f662895354f3dd015203633b857297e2c";
      };
    };
    "sshpk-1.16.1" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.16.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.16.1.tgz";
        sha512 = "HXXqVUq7+pcKeLqqZj6mHFUMvXtOJt1uoUx09pFW6011inTMxqI8BA8PM95myrIyyKwdnzjdFjLiE6KBPVtJIg==";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "static-eval-2.0.2" = {
      name = "static-eval";
      packageName = "static-eval";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/static-eval/-/static-eval-2.0.2.tgz";
        sha512 = "N/D219Hcr2bPjLxPiV+TQE++Tsmrady7TqAJugLy7Xk1EumfDWS/f5dtBbkRCGE7wKKXuYockQoj8Rm2/pVKyg==";
      };
    };
    "stealthy-require-1.1.1" = {
      name = "stealthy-require";
      packageName = "stealthy-require";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/stealthy-require/-/stealthy-require-1.1.1.tgz";
        sha1 = "35b09875b4ff49f26a777e509b3090a3226bf24b";
      };
    };
    "string.prototype.trimleft-2.1.0" = {
      name = "string.prototype.trimleft";
      packageName = "string.prototype.trimleft";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimleft/-/string.prototype.trimleft-2.1.0.tgz";
        sha512 = "FJ6b7EgdKxxbDxc79cOlok6Afd++TTs5szo+zJTUyow3ycrRfJVE2pq3vcN53XexvKZu/DJMDfeI/qMiZTrjTw==";
      };
    };
    "string.prototype.trimright-2.1.0" = {
      name = "string.prototype.trimright";
      packageName = "string.prototype.trimright";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string.prototype.trimright/-/string.prototype.trimright-2.1.0.tgz";
        sha512 = "fXZTSV55dNBwv16uw+hh5jkghxSnc5oHq+5K/gXgizHwAvMetdAJlHqqoFC1FSDVPYWLkAKl2cxpUT41sV7nSg==";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "tinycolor-0.0.1" = {
      name = "tinycolor";
      packageName = "tinycolor";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinycolor/-/tinycolor-0.0.1.tgz";
        sha1 = "320b5a52d83abb5978d81a3e887d4aefb15a6164";
      };
    };
    "tough-cookie-2.4.3" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.4.3.tgz";
        sha512 = "Q5srk/4vDM54WJsJio3XNn6K2sCG+CQ8G5Wz6bZhRZoAe/+TxjWB/GlFAnYEbkYVlON9FMk/fE3h2RLpPXo4lQ==";
      };
    };
    "tslib-1.10.0" = {
      name = "tslib";
      packageName = "tslib";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tslib/-/tslib-1.10.0.tgz";
        sha512 = "qOebF53frne81cf0S9B41ByenJ3/IuH8yJKngAX35CmiZySA0khhkovshKK+jGCaMnVomla7gVlIcc3EvKPbTQ==";
      };
    };
    "tunnel-agent-0.6.0" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.6.0.tgz";
        sha1 = "27a5dea06b36b04a0a9966774b290868f0fc40fd";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "type-check-0.3.2" = {
      name = "type-check";
      packageName = "type-check";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/type-check/-/type-check-0.3.2.tgz";
        sha1 = "5884cab512cf1d355e3fb784f30804b2b520db72";
      };
    };
    "ultron-1.1.1" = {
      name = "ultron";
      packageName = "ultron";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ultron/-/ultron-1.1.1.tgz";
        sha512 = "UIEXBNeYmKptWH6z8ZnqTeS8fV74zG0/eRU9VGkpzz+LIJNs8W/zM/L+7ctCkRrgbNnnR0xxw4bKOr0cW0N0Og==";
      };
    };
    "underscore-1.7.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.7.0.tgz";
        sha1 = "6bbaf0877500d36be34ecaa584e0db9fef035209";
      };
    };
    "underscore-1.9.1" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.9.1.tgz";
        sha512 = "5/4etnCkd9c8gwgowi5/om/mYO5ajCaOgdzj/oW+0eQV9WxKBDZw5+ycmKmeaTXjInS/W0BzpGLo2xR2aBwZdg==";
      };
    };
    "uri-js-4.2.2" = {
      name = "uri-js";
      packageName = "uri-js";
      version = "4.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uri-js/-/uri-js-4.2.2.tgz";
        sha512 = "KY9Frmirql91X2Qgjry0Wd4Y+YTdrdZheS8TFwvkbLWf/G5KNJDCh6pKL5OZctEW4+0Baa5idK2ZQuELRwPznQ==";
      };
    };
    "url-template-2.0.8" = {
      name = "url-template";
      packageName = "url-template";
      version = "2.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/url-template/-/url-template-2.0.8.tgz";
        sha1 = "fc565a3cccbff7730c775f5641f9555791439f21";
      };
    };
    "util.promisify-1.0.0" = {
      name = "util.promisify";
      packageName = "util.promisify";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/util.promisify/-/util.promisify-1.0.0.tgz";
        sha512 = "i+6qA2MPhvoKLuxnJNpXAGhg7HphQOSUq2LKMZD0m15EiskXUkMvKdF4Uui0WYeCUGea+o2cw/ZuwehtfsrNkA==";
      };
    };
    "uuid-3.3.2" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.2.tgz";
        sha512 = "yXJmeNaw3DnnKAOKJE51sL/ZaYfWJRl1pK9dr19YFCu0ObS231AB1/LbqTKRAQ5kw8A90rA6fr4riOUpTZvQZA==";
      };
    };
    "uuid-3.3.3" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.3.3.tgz";
        sha512 = "pW0No1RGHgzlpHJO1nsVrHKpOEIxkGg1xB+v0ZmdNH5OAeAwzAVrCnI2/6Mtx+Uys6iaylxa+D3g4j63IKKjSQ==";
      };
    };
    "verror-1.10.0" = {
      name = "verror";
      packageName = "verror";
      version = "1.10.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.10.0.tgz";
        sha1 = "3a105ca17053af55d6e270c1f8288682e18da400";
      };
    };
    "websocket-stream-0.5.1" = {
      name = "websocket-stream";
      packageName = "websocket-stream";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/websocket-stream/-/websocket-stream-0.5.1.tgz";
        sha1 = "622cd1f0566fb84ce0a4d6f854526f3dc4d70e48";
      };
    };
    "winston-2.4.2" = {
      name = "winston";
      packageName = "winston";
      version = "2.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-2.4.2.tgz";
        sha512 = "4S/Ad4ZfSNl8OccCLxnJmNISWcm2joa6Q0YGDxlxMzH0fgSwWsjMt+SmlNwCqdpaPg3ev1HKkMBsIiXeSUwpbA==";
      };
    };
    "wordwrap-1.0.0" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-1.0.0.tgz";
        sha1 = "27584810891456a4171c8d0226441ade90cbcaeb";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "ws-0.4.32" = {
      name = "ws";
      packageName = "ws";
      version = "0.4.32";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-0.4.32.tgz";
        sha1 = "787a6154414f3c99ed83c5772153b20feb0cec32";
      };
    };
    "ws-3.3.3" = {
      name = "ws";
      packageName = "ws";
      version = "3.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-3.3.3.tgz";
        sha512 = "nnWLa/NwZSt4KQJu51MYlCcSQ5g7INpOrOMt4XV8j4dqTXdmlUmSHQ8/oLC069ckre0fRsgfvsKwbTdtKLCDkA==";
      };
    };
    "ws-6.1.2" = {
      name = "ws";
      packageName = "ws";
      version = "6.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-6.1.2.tgz";
        sha512 = "rfUqzvz0WxmSXtJpPMX2EeASXabOrSMk1ruMOV3JBTBjo4ac2lDjGGsbQSyxj8Odhw5fBib8ZKEjDNvgouNKYw==";
      };
    };
    "ws-6.2.1" = {
      name = "ws";
      packageName = "ws";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-6.2.1.tgz";
        sha512 = "GIyAXC2cB7LjvpgMt9EKS2ldqr0MTrORaleiOno6TweZ6r3TKtoFQWay/2PceJ3RuBasOHzXNn5Lrw1X0bEjqA==";
      };
    };
    "ws-7.2.1" = {
      name = "ws";
      packageName = "ws";
      version = "7.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ws/-/ws-7.2.1.tgz";
        sha512 = "sucePNSafamSKoOqoNfBd8V0StlkzJKL2ZAhGQinCfNQ+oacw+Pk7lcdAElecBF2VkLNZRiIb5Oi1Q5lVUVt2A==";
      };
    };
    "xml2js-0.4.22" = {
      name = "xml2js";
      packageName = "xml2js";
      version = "0.4.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js/-/xml2js-0.4.22.tgz";
        sha512 = "MWTbxAQqclRSTnehWWe5nMKzI3VmJ8ltiJEco8akcC6j3miOhjjfzKum5sId+CWhfxdOs/1xauYr8/ZDBtQiRw==";
      };
    };
    "xml2js-es6-promise-1.1.1" = {
      name = "xml2js-es6-promise";
      packageName = "xml2js-es6-promise";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xml2js-es6-promise/-/xml2js-es6-promise-1.1.1.tgz";
        sha1 = "cd5688d9d6344e67c908f71e5b0a3d88d128e9a2";
      };
    };
    "xmlbuilder-11.0.1" = {
      name = "xmlbuilder";
      packageName = "xmlbuilder";
      version = "11.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xmlbuilder/-/xmlbuilder-11.0.1.tgz";
        sha512 = "fDlsI/kFEx7gLvbecc0/ohLG50fugQp8ryHzMTuW9vSa1GJ0XYWKnhsUx7oie3G98+r56aTQIUB4kht42R3JvA==";
      };
    };
    "yallist-3.1.1" = {
      name = "yallist";
      packageName = "yallist";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-3.1.1.tgz";
        sha512 = "a4UGQaWPH59mOXUYnAG2ewncQS4i4F43Tv3JoAM+s2VDAmS9NsK8GpDMLrCHPksFT7h3K6TOoUNn2pb7RoXx4g==";
      };
    };
  };
  args = {
    name = "bbb-webrtc-sfu";
    packageName = "bbb-webrtc-sfu";
    version = "2.4.15";
    src = ./.;
    dependencies = [
      (sources."@kubernetes/client-node-0.8.2" // {
        dependencies = [
          sources."ws-6.2.1"
        ];
      })
      sources."@types/caseless-0.12.2"
      sources."@types/js-yaml-3.12.1"
      sources."@types/node-10.14.20"
      sources."@types/request-2.48.3"
      sources."@types/tough-cookie-2.3.5"
      sources."@types/underscore-1.9.3"
      sources."@types/ws-6.0.3"
      sources."JSONStream-0.10.0"
      sources."abort-controller-3.0.0"
      sources."agent-base-4.3.0"
      sources."ajv-6.10.2"
      sources."argparse-1.0.10"
      sources."arrify-2.0.1"
      sources."asap-2.0.6"
      sources."asn1-0.2.4"
      sources."assert-plus-1.0.0"
      sources."async-2.6.3"
      sources."async-limiter-1.0.1"
      sources."asynckit-0.4.0"
      sources."aws-sign2-0.7.0"
      sources."aws4-1.8.0"
      sources."backoff-2.3.0"
      sources."balanced-match-1.0.0"
      sources."base64-js-1.3.1"
      sources."bbb-promise-1.2.0"
      sources."bcrypt-pbkdf-1.0.2"
      sources."bignumber.js-7.2.1"
      sources."bluebird-3.7.1"
      sources."brace-expansion-1.1.11"
      sources."buffer-equal-constant-time-1.0.1"
      sources."bufferutil-4.0.1"
      sources."build-url-1.3.3"
      sources."byline-5.0.0"
      sources."caseless-0.12.0"
      sources."charenc-0.0.2"
      sources."colors-1.0.3"
      sources."combined-stream-1.0.8"
      sources."commander-2.1.0"
      sources."concat-map-0.0.1"
      sources."config-1.30.0"
      sources."core-util-is-1.0.2"
      sources."crypt-0.0.2"
      sources."cycle-1.0.3"
      sources."dashdash-1.14.1"
      (sources."debug-3.2.6" // {
        dependencies = [
          sources."ms-2.1.2"
        ];
      })
      sources."deep-is-0.1.3"
      sources."define-properties-1.1.3"
      sources."delayed-stream-1.0.0"
      (sources."docker-modem-0.3.7" // {
        dependencies = [
          sources."debug-2.6.9"
        ];
      })
      sources."double-ended-queue-2.1.0-0"
      sources."ecc-jsbn-0.1.2"
      sources."ecdsa-sig-formatter-1.0.11"
      sources."error-tojson-0.0.1"
      sources."es-abstract-1.15.0"
      sources."es-to-primitive-1.2.0"
      sources."es6-promise-4.2.8"
      sources."es6-promisify-5.0.0"
      (sources."escodegen-1.12.0" // {
        dependencies = [
          sources."esprima-3.1.3"
        ];
      })
      sources."esprima-4.0.1"
      sources."estraverse-4.3.0"
      sources."esutils-2.0.3"
      sources."event-target-shim-5.0.1"
      sources."eventemitter2-4.1.2"
      sources."extend-3.0.2"
      sources."extsprintf-1.3.0"
      sources."eyes-0.1.8"
      sources."fast-deep-equal-2.0.1"
      sources."fast-json-stable-stringify-2.0.0"
      sources."fast-levenshtein-2.0.6"
      sources."fast-text-encoding-1.0.0"
      sources."forever-agent-0.6.1"
      sources."form-data-2.5.1"
      sources."fs.realpath-1.0.0"
      sources."function-bind-1.1.1"
      sources."gaxios-2.1.0"
      sources."gcp-metadata-3.2.0"
      sources."getpass-0.1.7"
      sources."glob-7.1.4"
      sources."google-auth-library-5.5.0"
      sources."google-p12-pem-2.0.2"
      sources."googleapis-43.0.0"
      (sources."googleapis-common-3.1.1" // {
        dependencies = [
          sources."qs-6.9.0"
        ];
      })
      sources."gtoken-4.1.0"
      sources."har-schema-2.0.0"
      sources."har-validator-5.1.3"
      sources."has-1.0.3"
      sources."has-symbols-1.0.0"
      sources."http-signature-1.2.0"
      sources."https-proxy-agent-3.0.0"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."interpret-1.2.0"
      sources."ipaddr.js-1.9.1"
      sources."is-callable-1.1.4"
      sources."is-date-object-1.0.1"
      sources."is-regex-1.0.4"
      sources."is-stream-2.0.0"
      sources."is-symbol-1.0.2"
      sources."is-typedarray-1.0.0"
      sources."isarray-0.0.1"
      sources."isbuffer-0.0.0"
      sources."isomorphic-ws-4.0.1"
      sources."isstream-0.1.2"
      sources."js-yaml-3.13.1"
      sources."jsbn-0.1.1"
      sources."json-bigint-0.3.0"
      sources."json-schema-0.2.3"
      sources."json-schema-traverse-0.4.1"
      sources."json-stringify-safe-5.0.1"
      sources."json5-0.4.0"
      sources."jsonparse-0.0.5"
      (sources."jsonpath-1.0.2" // {
        dependencies = [
          sources."esprima-1.2.2"
          sources."underscore-1.7.0"
        ];
      })
      sources."jsprim-1.4.1"
      sources."jwa-1.4.1"
      sources."jws-3.2.2"
      sources."kurento-client-git+https://github.com/Kurento/kurento-client-js.git#da7b2f6433d52eb8689e65e8e6e3990b90dc40a1"
      sources."kurento-client-core-6.13.0"
      sources."kurento-client-elements-6.13.0"
      sources."kurento-client-filters-6.13.0"
      (sources."kurento-jsonrpc-6.13.0" // {
        dependencies = [
          sources."ws-7.2.1"
        ];
      })
      sources."levn-0.3.0"
      sources."lodash-4.17.15"
      sources."lru-cache-5.1.1"
      (sources."mcs-js-git+https://github.com/mconftec/mcs-js.git#94292a211164704f850128e95602d6d99056bf55" // {
        dependencies = [
          sources."uuid-3.3.2"
          sources."ws-6.1.2"
        ];
      })
      sources."memorystream-0.3.1"
      sources."mime-2.4.4"
      sources."mime-db-1.40.0"
      sources."mime-types-2.1.24"
      sources."minimatch-3.0.4"
      sources."minimist-1.2.0"
      sources."modesl-1.2.1"
      sources."ms-2.0.0"
      sources."nan-1.0.0"
      sources."nanoid-1.3.4"
      sources."node-docker-api-1.1.22"
      sources."node-fetch-2.6.0"
      sources."node-forge-0.9.1"
      sources."node-gyp-build-3.7.0"
      sources."oauth-sign-0.9.0"
      sources."object-inspect-1.6.0"
      sources."object-keys-1.1.1"
      sources."object.getownpropertydescriptors-2.0.3"
      sources."once-1.4.0"
      sources."optionator-0.8.2"
      sources."options-0.0.6"
      sources."os-homedir-1.0.2"
      sources."path-is-absolute-1.0.1"
      sources."path-parse-1.0.6"
      sources."pegjs-0.8.0"
      sources."performance-now-2.1.0"
      sources."prelude-ls-1.1.2"
      sources."promiscuous-0.6.0"
      sources."promise-7.1.1"
      sources."promisecallback-0.0.4"
      sources."psl-1.4.0"
      sources."punycode-2.1.1"
      sources."qs-6.5.2"
      sources."readable-id-1.0.0"
      sources."readable-stream-1.0.34"
      sources."rechoir-0.6.2"
      sources."reconnect-core-git://github.com/kurentoforks/reconnect-core#921d43e91578abb2fb2613f585c010c1939cf734"
      sources."reconnect-ws-git://github.com/kurentoforks/reconnect-ws#f287385d75861654528c352e60221f95c9209f8a"
      sources."redis-2.8.0"
      sources."redis-commands-1.5.0"
      sources."redis-parser-2.6.0"
      (sources."request-2.88.0" // {
        dependencies = [
          sources."form-data-2.3.3"
        ];
      })
      sources."request-promise-4.2.5"
      sources."request-promise-core-1.1.3"
      sources."resolve-1.12.0"
      sources."safe-buffer-5.2.0"
      sources."safer-buffer-2.1.2"
      sources."sax-1.2.4"
      sources."sdp-transform-2.13.0"
      sources."sha1-1.1.1"
      sources."shelljs-0.8.3"
      (sources."sip.js-git+https://github.com/mconf/sip.js.git#587a1fc3e6e831cb954d65eb4fe2a623a02b72a8" // {
        dependencies = [
          sources."ws-6.2.1"
        ];
      })
      sources."source-map-0.6.1"
      sources."split-ca-1.0.1"
      sources."sprintf-js-1.0.3"
      sources."sshpk-1.16.1"
      sources."stack-trace-0.0.10"
      sources."static-eval-2.0.2"
      sources."stealthy-require-1.1.1"
      sources."string.prototype.trimleft-2.1.0"
      sources."string.prototype.trimright-2.1.0"
      sources."string_decoder-0.10.31"
      sources."through-2.3.8"
      sources."tinycolor-0.0.1"
      (sources."tough-cookie-2.4.3" // {
        dependencies = [
          sources."punycode-1.4.1"
        ];
      })
      sources."tslib-1.10.0"
      sources."tunnel-agent-0.6.0"
      sources."tweetnacl-0.14.5"
      sources."type-check-0.3.2"
      sources."ultron-1.1.1"
      sources."underscore-1.9.1"
      sources."uri-js-4.2.2"
      sources."url-template-2.0.8"
      sources."util.promisify-1.0.0"
      sources."uuid-3.3.3"
      sources."verror-1.10.0"
      (sources."websocket-stream-0.5.1" // {
        dependencies = [
          sources."ws-0.4.32"
        ];
      })
      (sources."winston-2.4.2" // {
        dependencies = [
          sources."async-1.0.0"
        ];
      })
      sources."wordwrap-1.0.0"
      sources."wrappy-1.0.2"
      (sources."ws-3.3.3" // {
        dependencies = [
          sources."safe-buffer-5.1.2"
        ];
      })
      sources."xml2js-0.4.22"
      sources."xml2js-es6-promise-1.1.1"
      sources."xmlbuilder-11.0.1"
      sources."yallist-3.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = false;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}